// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable





using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace DemoClientV4.ODataDemo;


[ODataEntitySet("PersonDetails")]
public partial class PersonDetail  : IODataEntitySet
{

    [ODataMember("PersonID")]
    public int PersonID { get; set; }

    [ODataMember("Age")]
    public byte Age { get; set; }

    [ODataMember("Gender")]
    public bool Gender { get; set; }

    [ODataMember("Phone")]
    public string Phone { get; set; }

    [ODataMember("Address")]
    public ODataDemo.Address? Address { get; set; }

    [ODataMember("Photo")]
    public object Photo { get; set; }



    [ODataMember("Person")]
    public Person? Person { get; set; }

}

