// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: AppOverridableSettingInfo
/// </summary>


public partial class AppOverridableSettingInfo 
{
    [ODataMember("AppUniqueName")]
    public string? AppUniqueName { get; set; }
    [ODataMember("AppDisplayName")]
    public string? AppDisplayName { get; set; }
    [ODataMember("AppId")]
    public Guid? AppId { get; set; }
    [ODataMember("OverriddenValue")]
    public string? OverriddenValue { get; set; }
    [ODataMember("OverriddenPublishedValue")]
    public string? OverriddenPublishedValue { get; set; }
    [ODataMember("AppSettingId")]
    public Guid? AppSettingId { get; set; }
    [ODataMember("IsCustomizable")]
    public bool? IsCustomizable { get; set; }
    [ODataMember("IsManaged")]
    public bool? IsManaged { get; set; }
    [ODataMember("IsPublished")]
    public bool? IsPublished { get; set; }
    
    //Navigations



}

