// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: DependentRelationshipCollection
/// </summary>


public partial class DependentRelationshipCollection 
{
    [ODataMember("DependentRelationships", true)]
    public List<DependentRelationship>? DependentRelationships { get; set; }
    
    //Navigations



}

