// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: importmap
/// </summary>

[ODataEntitySet("importmaps")]
public partial class importmap : crmbaseentity, ILargeEntitySet, IimportmapKeys
{
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("source")]
    public string? source { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("sourcetype")]
    public int? sourcetype { get; set; }
    [ODataMember("entitiesperfile")]
    public int? entitiesperfile { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("isvalidforimport")]
    public bool? isvalidforimport { get; set; }
    [ODataMember("sourceuseridentifierforsourcecrmuserlink")]
    public string? sourceuseridentifierforsourcecrmuserlink { get; set; }
    [ODataMember("targetuseridentifierforsourcecrmuserlink")]
    public string? targetuseridentifierforsourcecrmuserlink { get; set; }
    [ODataMember("sourceuseridentifierforsourcedatasourceuserlink")]
    public string? sourceuseridentifierforsourcedatasourceuserlink { get; set; }
    [ODataMember("importmapid")]
    public Guid? importmapid { get; set; }
    [ODataMember("iswizardcreated")]
    public bool? iswizardcreated { get; set; }
    [ODataMember("targetentity")]
    public int? targetentity { get; set; }
    [ODataMember("importmapidunique")]
    public Guid? importmapidunique { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("introducedversion")]
    public string? introducedversion { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("mapcustomizations")]
    public string? mapcustomizations { get; set; }
    [ODataMember("description")]
    public string? description { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("importmaptype")]
    public int? importmaptype { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    
    //Navigations
    [ODataMember("ImportMap_SyncErrors", true)]
    public List<syncerror>? ImportMap_SyncErrors { get; set; }
    [ODataMember("ColumnMapping_ImportMap", true)]
    public List<columnmapping>? ColumnMapping_ImportMap { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("ImportMap_AsyncOperations", true)]
    public List<asyncoperation>? ImportMap_AsyncOperations { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("ImportEntityMapping_ImportMap", true)]
    public List<importentitymapping>? ImportEntityMapping_ImportMap { get; set; }
    [ODataMember("ImportMap_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? ImportMap_BulkDeleteFailures { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("OwnerMapping_ImportMap", true)]
    public List<ownermapping>? OwnerMapping_ImportMap { get; set; }
    [ODataMember("ImportMap_ImportFile", true)]
    public List<importfile>? ImportMap_ImportFile { get; set; }
    [ODataMember("TransformationMapping_ImportMap", true)]
    public List<transformationmapping>? TransformationMapping_ImportMap { get; set; }

 public string __Key => $"importmapid={importmapid}"; 


}

public interface IimportmapKeys
{
	Guid? importmapid { get; set; }
    }
