// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: mobileofflineprofileitemfilter
/// </summary>

[ODataEntitySet("mobileofflineprofileitemfilters")]
public partial class mobileofflineprofileitemfilter : crmbaseentity, ILargeEntitySet, ImobileofflineprofileitemfilterKeys
{
    [ODataMember("subtype")]
    public int? subtype { get; set; }
    [ODataMember("outerfetchXml")]
    public string? outerfetchXml { get; set; }
    [ODataMember("mobileofflineprofileitemfilterid")]
    public Guid? mobileofflineprofileitemfilterid { get; set; }
    [ODataMember("_mobileofflineprofileid_value")]
    public Guid? _mobileofflineprofileid_value { get; set; }
    [ODataMember("fetchxml")]
    public string? fetchxml { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("type")]
    public int? @type { get; set; }
    [ODataMember("mobileofflineprofileitemid")]
    public Guid? mobileofflineprofileitemid { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("isactivity")]
    public bool? isactivity { get; set; }
    [ODataMember("offlinesql")]
    public string? offlinesql { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("isintersect")]
    public bool? isintersect { get; set; }
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("returnedtypecode")]
    public string? returnedtypecode { get; set; }
    
    //Navigations
    [ODataMember("mobileofflineprofileid", true)]
    public mobileofflineprofile? mobileofflineprofileid { get; set; }

 public string __Key => $"mobileofflineprofileitemfilterid={mobileofflineprofileitemfilterid}"; 


}

public interface ImobileofflineprofileitemfilterKeys
{
	Guid? mobileofflineprofileitemfilterid { get; set; }
    }
