// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_productinventory
/// </summary>

[ODataEntitySet("msdyn_productinventories")]
public partial class msdyn_productinventory : crmbaseentity, ILargeEntitySet, Imsdyn_productinventoryKeys
{
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_row")]
    public string? msdyn_row { get; set; }
    [ODataMember("msdyn_qtyavailable")]
    public double? msdyn_qtyavailable { get; set; }
    [ODataMember("_msdyn_warehouse_value")]
    public Guid? _msdyn_warehouse_value { get; set; }
    [ODataMember("msdyn_qtyallocated")]
    public double? msdyn_qtyallocated { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_qtyonhand")]
    public double? msdyn_qtyonhand { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("msdyn_productinventoryid")]
    public Guid? msdyn_productinventoryid { get; set; }
    [ODataMember("msdyn_reorderpoint")]
    public double? msdyn_reorderpoint { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_msdyn_unit_value")]
    public Guid? _msdyn_unit_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("zync_m3warehouse")]
    public string? zync_m3warehouse { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_qtyonorder")]
    public double? msdyn_qtyonorder { get; set; }
    [ODataMember("_msdyn_product_value")]
    public Guid? _msdyn_product_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_bin")]
    public string? msdyn_bin { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("msdyn_internalflags")]
    public string? msdyn_internalflags { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_productinventory_ActivityPointers", true)]
    public List<activitypointer>? msdyn_productinventory_ActivityPointers { get; set; }
    [ODataMember("msdyn_productinventory_li_inmails", true)]
    public List<li_inmail>? msdyn_productinventory_li_inmails { get; set; }
    [ODataMember("msdyn_productinventory_msfp_surveyinvites", true)]
    public List<msfp_surveyinvite>? msdyn_productinventory_msfp_surveyinvites { get; set; }
    [ODataMember("msdyn_productinventory_li_messages", true)]
    public List<li_message>? msdyn_productinventory_li_messages { get; set; }
    [ODataMember("msdyn_productinventory_msfp_alerts", true)]
    public List<msfp_alert>? msdyn_productinventory_msfp_alerts { get; set; }
    [ODataMember("msdyn_productinventory_msdyn_bookingalerts", true)]
    public List<msdyn_bookingalert>? msdyn_productinventory_msdyn_bookingalerts { get; set; }
    [ODataMember("msdyn_productinventory_li_pointdrivepresentationvieweds", true)]
    public List<li_pointdrivepresentationviewed>? msdyn_productinventory_li_pointdrivepresentationvieweds { get; set; }
    [ODataMember("msdyn_productinventory_zync_logs", true)]
    public List<zync_log>? msdyn_productinventory_zync_logs { get; set; }
    [ODataMember("msdyn_productinventory_msfp_surveyresponses", true)]
    public List<msfp_surveyresponse>? msdyn_productinventory_msfp_surveyresponses { get; set; }
    [ODataMember("msdyn_productinventory_SyncErrors", true)]
    public List<syncerror>? msdyn_productinventory_SyncErrors { get; set; }
    [ODataMember("msdyn_productinventory_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_productinventory_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_productinventory_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_productinventory_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_productinventory_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_productinventory_AsyncOperations { get; set; }
    [ODataMember("msdyn_productinventory_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_productinventory_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_productinventory_ProcessSession", true)]
    public List<processsession>? msdyn_productinventory_ProcessSession { get; set; }
    [ODataMember("msdyn_productinventory_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_productinventory_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_productinventory_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_productinventory_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_productinventory_Appointments", true)]
    public List<appointment>? msdyn_productinventory_Appointments { get; set; }
    [ODataMember("msdyn_productinventory_Emails", true)]
    public List<email>? msdyn_productinventory_Emails { get; set; }
    [ODataMember("msdyn_productinventory_Faxes", true)]
    public List<fax>? msdyn_productinventory_Faxes { get; set; }
    [ODataMember("msdyn_productinventory_Letters", true)]
    public List<letter>? msdyn_productinventory_Letters { get; set; }
    [ODataMember("msdyn_productinventory_PhoneCalls", true)]
    public List<phonecall>? msdyn_productinventory_PhoneCalls { get; set; }
    [ODataMember("msdyn_productinventory_Tasks", true)]
    public List<task>? msdyn_productinventory_Tasks { get; set; }
    [ODataMember("msdyn_productinventory_RecurringAppointmentMasters", true)]
    public List<recurringappointmentmaster>? msdyn_productinventory_RecurringAppointmentMasters { get; set; }
    [ODataMember("msdyn_productinventory_SocialActivities", true)]
    public List<socialactivity>? msdyn_productinventory_SocialActivities { get; set; }
    [ODataMember("msdyn_productinventory_connections1", true)]
    public List<connection>? msdyn_productinventory_connections1 { get; set; }
    [ODataMember("msdyn_productinventory_connections2", true)]
    public List<connection>? msdyn_productinventory_connections2 { get; set; }
    [ODataMember("msdyn_productinventory_Annotations", true)]
    public List<annotation>? msdyn_productinventory_Annotations { get; set; }
    [ODataMember("msdyn_productinventory_ServiceAppointments", true)]
    public List<serviceappointment>? msdyn_productinventory_ServiceAppointments { get; set; }
    [ODataMember("msdyn_warehouse", true)]
    public msdyn_warehouse? msdyn_warehouse { get; set; }
    [ODataMember("msdyn_product", true)]
    public product? msdyn_product { get; set; }
    [ODataMember("msdyn_unit", true)]
    public uom? msdyn_unit { get; set; }
    [ODataMember("msdyn_productinventory_adx_alertsubscriptions", true)]
    public List<adx_alertsubscription>? msdyn_productinventory_adx_alertsubscriptions { get; set; }
    [ODataMember("msdyn_productinventory_adx_inviteredemptions", true)]
    public List<adx_inviteredemption>? msdyn_productinventory_adx_inviteredemptions { get; set; }
    [ODataMember("msdyn_productinventory_adx_portalcomments", true)]
    public List<adx_portalcomment>? msdyn_productinventory_adx_portalcomments { get; set; }
    [ODataMember("msdyn_productinventory_chats", true)]
    public List<chat>? msdyn_productinventory_chats { get; set; }
    [ODataMember("msdyn_productinventory_msdyn_ocliveworkitems", true)]
    public List<msdyn_ocliveworkitem>? msdyn_productinventory_msdyn_ocliveworkitems { get; set; }
    [ODataMember("msdyn_productinventory_msdyn_ocsessions", true)]
    public List<msdyn_ocsession>? msdyn_productinventory_msdyn_ocsessions { get; set; }
    [ODataMember("msdyn_productinventory_msdyn_copilottranscripts", true)]
    public List<msdyn_copilottranscript>? msdyn_productinventory_msdyn_copilottranscripts { get; set; }
    [ODataMember("msdyn_productinventory_zync_customerassetnotes", true)]
    public List<zync_customerassetnote>? msdyn_productinventory_zync_customerassetnotes { get; set; }

 public string __Key => $"msdyn_productinventoryid={msdyn_productinventoryid}"; 


}

public interface Imsdyn_productinventoryKeys
{
	Guid? msdyn_productinventoryid { get; set; }
    }
