// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_templatecontextvariable_msdyn_template
/// </summary>

[ODataEntitySet("msdyn_templatecontextvariable_msdyn_templateset")]
public partial class msdyn_templatecontextvariable_msdyn_template : crmbaseentity, ILargeEntitySet, Imsdyn_templatecontextvariable_msdyn_templateKeys
{
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("msdyn_templatecontextvariableid")]
    public Guid? msdyn_templatecontextvariableid { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("msdyn_templatecontextvariable_msdyn_templateid")]
    public Guid? msdyn_templatecontextvariable_msdyn_templateid { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("msdyn_templaterulesetid")]
    public Guid? msdyn_templaterulesetid { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    
    //Navigations

 public string __Key => $"msdyn_templatecontextvariable_msdyn_templateid={msdyn_templatecontextvariable_msdyn_templateid}"; 


}

public interface Imsdyn_templatecontextvariable_msdyn_templateKeys
{
	Guid? msdyn_templatecontextvariable_msdyn_templateid { get; set; }
    }
