// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_attributeinfluencestatistics
/// </summary>

[ODataEntitySet("msdyn_attributeinfluencestatisticses")]
public partial class msdyn_attributeinfluencestatistics : crmbaseentity, ILargeEntitySet, Imsdyn_attributeinfluencestatisticsKeys
{
    [ODataMember("msdyn_entityname")]
    public string? msdyn_entityname { get; set; }
    [ODataMember("msdyn_ignoreifblank")]
    public bool? msdyn_ignoreifblank { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_importance")]
    public decimal? msdyn_importance { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("msdyn_predictionid")]
    public string? msdyn_predictionid { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_modelid")]
    public string? msdyn_modelid { get; set; }
    [ODataMember("msdyn_statistics")]
    public string? msdyn_statistics { get; set; }
    [ODataMember("msdyn_isvalid")]
    public bool? msdyn_isvalid { get; set; }
    [ODataMember("msdyn_attributeinfluencestatisticsid")]
    public Guid? msdyn_attributeinfluencestatisticsid { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_notselectedreason")]
    public int? msdyn_notselectedreason { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_attributename")]
    public string? msdyn_attributename { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("msdyn_iscrmattribute")]
    public bool? msdyn_iscrmattribute { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("msdyn_submodelid")]
    public string? msdyn_submodelid { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_isrecommended")]
    public bool? msdyn_isrecommended { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_SyncErrors", true)]
    public List<syncerror>? msdyn_attributeinfluencestatistics_SyncErrors { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_attributeinfluencestatistics_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_attributeinfluencestatistics_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_attributeinfluencestatistics_AsyncOperations { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_attributeinfluencestatistics_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_ProcessSession", true)]
    public List<processsession>? msdyn_attributeinfluencestatistics_ProcessSession { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_attributeinfluencestatistics_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_attributeinfluencestatistics_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_attributeinfluencestatistics_PrincipalObjectAttributeAccesses { get; set; }

 public string __Key => $"msdyn_attributeinfluencestatisticsid={msdyn_attributeinfluencestatisticsid}"; 


}

public interface Imsdyn_attributeinfluencestatisticsKeys
{
	Guid? msdyn_attributeinfluencestatisticsid { get; set; }
    }
