// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_conversationdispositioncodemap
/// </summary>

[ODataEntitySet("msdyn_conversationdispositioncodemaps")]
public partial class msdyn_conversationdispositioncodemap : crmbaseentity, ILargeEntitySet, Imsdyn_conversationdispositioncodemapKeys
{
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("msdyn_dispositioncodevalue")]
    public string? msdyn_dispositioncodevalue { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("_msdyn_ocliveworkitemid_value")]
    public Guid? _msdyn_ocliveworkitemid_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemapid")]
    public Guid? msdyn_conversationdispositioncodemapid { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_SyncErrors", true)]
    public List<syncerror>? msdyn_conversationdispositioncodemap_SyncErrors { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_conversationdispositioncodemap_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_conversationdispositioncodemap_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_conversationdispositioncodemap_AsyncOperations { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_conversationdispositioncodemap_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_ProcessSession", true)]
    public List<processsession>? msdyn_conversationdispositioncodemap_ProcessSession { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_conversationdispositioncodemap_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_conversationdispositioncodemap_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_conversationdispositioncodemap_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_ocliveworkitemid", true)]
    public msdyn_ocliveworkitem? msdyn_ocliveworkitemid { get; set; }

 public string __Key => $"msdyn_conversationdispositioncodemapid={msdyn_conversationdispositioncodemapid}"; 


}

public interface Imsdyn_conversationdispositioncodemapKeys
{
	Guid? msdyn_conversationdispositioncodemapid { get; set; }
    }
