// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_occhannelstateconfiguration
/// </summary>

[ODataEntitySet("msdyn_occhannelstateconfigurations")]
public partial class msdyn_occhannelstateconfiguration : crmbaseentity, ILargeEntitySet, Imsdyn_occhannelstateconfigurationKeys
{
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("msdyn_ocliveworkitemstate")]
    public int? msdyn_ocliveworkitemstate { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("msdyn_showconfirmationonsessionclose")]
    public bool? msdyn_showconfirmationonsessionclose { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_occhannelstateconfigurationid")]
    public Guid? msdyn_occhannelstateconfigurationid { get; set; }
    [ODataMember("_msdyn_occhannelconfigurationid_value")]
    public Guid? _msdyn_occhannelconfigurationid_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_autocloseliveworkitemafter")]
    public int? msdyn_autocloseliveworkitemafter { get; set; }
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_SyncErrors", true)]
    public List<syncerror>? msdyn_occhannelstateconfiguration_SyncErrors { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_occhannelstateconfiguration_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_occhannelstateconfiguration_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_occhannelstateconfiguration_AsyncOperations { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_occhannelstateconfiguration_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_ProcessSession", true)]
    public List<processsession>? msdyn_occhannelstateconfiguration_ProcessSession { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_occhannelstateconfiguration_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_occhannelstateconfiguration_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_occhannelstateconfiguration_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_occhannelconfigurationid", true)]
    public msdyn_occhannelconfiguration? msdyn_occhannelconfigurationid { get; set; }

 public string __Key => $"msdyn_occhannelstateconfigurationid={msdyn_occhannelstateconfigurationid}"; 


}

public interface Imsdyn_occhannelstateconfigurationKeys
{
	Guid? msdyn_occhannelstateconfigurationid { get; set; }
    }
