// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_maskingrule
/// </summary>

[ODataEntitySet("msdyn_maskingrules")]
public partial class msdyn_maskingrule : crmbaseentity, ILargeEntitySet, Imsdyn_maskingruleKeys
{
    [ODataMember("msdyn_description")]
    public string? msdyn_description { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_maskingruleid")]
    public Guid? msdyn_maskingruleid { get; set; }
    [ODataMember("msdyn_masked_test_data")]
    public string? msdyn_masked_test_data { get; set; }
    [ODataMember("msdyn_regular_expression")]
    public string? msdyn_regular_expression { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("msdyn_enter_test_data")]
    public string? msdyn_enter_test_data { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("msdyn_masked_character")]
    public string? msdyn_masked_character { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_maskingrule_SyncErrors", true)]
    public List<syncerror>? msdyn_maskingrule_SyncErrors { get; set; }
    [ODataMember("msdyn_maskingrule_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_maskingrule_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_maskingrule_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_maskingrule_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_maskingrule_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_maskingrule_AsyncOperations { get; set; }
    [ODataMember("msdyn_maskingrule_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_maskingrule_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_maskingrule_ProcessSession", true)]
    public List<processsession>? msdyn_maskingrule_ProcessSession { get; set; }
    [ODataMember("msdyn_maskingrule_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_maskingrule_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_maskingrule_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_maskingrule_PrincipalObjectAttributeAccesses { get; set; }

 public string __Key => $"msdyn_maskingruleid={msdyn_maskingruleid}"; 


}

public interface Imsdyn_maskingruleKeys
{
	Guid? msdyn_maskingruleid { get; set; }
    }
