// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_agreementbookingproduct
/// </summary>

[ODataEntitySet("msdyn_agreementbookingproducts")]
public partial class msdyn_agreementbookingproduct : crmbaseentity, ILargeEntitySet, Imsdyn_agreementbookingproductKeys
{
    [ODataMember("msdyn_quantity")]
    public double? msdyn_quantity { get; set; }
    [ODataMember("_transactioncurrencyid_value")]
    public Guid? _transactioncurrencyid_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("msdyn_currency")]
    public decimal? msdyn_currency { get; set; }
    [ODataMember("msdyn_currency_base")]
    public decimal? msdyn_currency_base { get; set; }
    [ODataMember("_msdyn_customerasset_value")]
    public Guid? _msdyn_customerasset_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("msdyn_lineorder")]
    public int? msdyn_lineorder { get; set; }
    [ODataMember("_msdyn_agreementbookingsetup_value")]
    public Guid? _msdyn_agreementbookingsetup_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("msdyn_agreementbookingproductid")]
    public Guid? msdyn_agreementbookingproductid { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("msdyn_qtytobill")]
    public double? msdyn_qtytobill { get; set; }
    [ODataMember("msdyn_unitamount")]
    public decimal? msdyn_unitamount { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_unitamount_base")]
    public decimal? msdyn_unitamount_base { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("_msdyn_agreement_value")]
    public Guid? _msdyn_agreement_value { get; set; }
    [ODataMember("_msdyn_agreementbookingincident_value")]
    public Guid? _msdyn_agreementbookingincident_value { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_iscopied")]
    public bool? msdyn_iscopied { get; set; }
    [ODataMember("_msdyn_product_value")]
    public Guid? _msdyn_product_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("exchangerate")]
    public decimal? exchangerate { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("_msdyn_unit_value")]
    public Guid? _msdyn_unit_value { get; set; }
    [ODataMember("_msdyn_pricelist_value")]
    public Guid? _msdyn_pricelist_value { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_ActivityPointers", true)]
    public List<activitypointer>? msdyn_agreementbookingproduct_ActivityPointers { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_li_inmails", true)]
    public List<li_inmail>? msdyn_agreementbookingproduct_li_inmails { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msfp_surveyinvites", true)]
    public List<msfp_surveyinvite>? msdyn_agreementbookingproduct_msfp_surveyinvites { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_li_messages", true)]
    public List<li_message>? msdyn_agreementbookingproduct_li_messages { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msfp_alerts", true)]
    public List<msfp_alert>? msdyn_agreementbookingproduct_msfp_alerts { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msdyn_bookingalerts", true)]
    public List<msdyn_bookingalert>? msdyn_agreementbookingproduct_msdyn_bookingalerts { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_li_pointdrivepresentationvieweds", true)]
    public List<li_pointdrivepresentationviewed>? msdyn_agreementbookingproduct_li_pointdrivepresentationvieweds { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_zync_logs", true)]
    public List<zync_log>? msdyn_agreementbookingproduct_zync_logs { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msfp_surveyresponses", true)]
    public List<msfp_surveyresponse>? msdyn_agreementbookingproduct_msfp_surveyresponses { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_SyncErrors", true)]
    public List<syncerror>? msdyn_agreementbookingproduct_SyncErrors { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_agreementbookingproduct_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_agreementbookingproduct_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_agreementbookingproduct_AsyncOperations { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_agreementbookingproduct_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_ProcessSession", true)]
    public List<processsession>? msdyn_agreementbookingproduct_ProcessSession { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_agreementbookingproduct_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_agreementbookingproduct_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("transactioncurrencyid", true)]
    public transactioncurrency? transactioncurrencyid { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Appointments", true)]
    public List<appointment>? msdyn_agreementbookingproduct_Appointments { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Emails", true)]
    public List<email>? msdyn_agreementbookingproduct_Emails { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Faxes", true)]
    public List<fax>? msdyn_agreementbookingproduct_Faxes { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Letters", true)]
    public List<letter>? msdyn_agreementbookingproduct_Letters { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_PhoneCalls", true)]
    public List<phonecall>? msdyn_agreementbookingproduct_PhoneCalls { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Tasks", true)]
    public List<task>? msdyn_agreementbookingproduct_Tasks { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_RecurringAppointmentMasters", true)]
    public List<recurringappointmentmaster>? msdyn_agreementbookingproduct_RecurringAppointmentMasters { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_SocialActivities", true)]
    public List<socialactivity>? msdyn_agreementbookingproduct_SocialActivities { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_connections1", true)]
    public List<connection>? msdyn_agreementbookingproduct_connections1 { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_connections2", true)]
    public List<connection>? msdyn_agreementbookingproduct_connections2 { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_Annotations", true)]
    public List<annotation>? msdyn_agreementbookingproduct_Annotations { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_ServiceAppointments", true)]
    public List<serviceappointment>? msdyn_agreementbookingproduct_ServiceAppointments { get; set; }
    [ODataMember("msdyn_agreement", true)]
    public msdyn_agreement? msdyn_agreement { get; set; }
    [ODataMember("msdyn_agreementbookingincident", true)]
    public msdyn_agreementbookingincident? msdyn_agreementbookingincident { get; set; }
    [ODataMember("msdyn_msdyn_agreementbookingproduct_msdyn_workorderproduct_AgreementBookingProduct", true)]
    public List<msdyn_workorderproduct>? msdyn_msdyn_agreementbookingproduct_msdyn_workorderproduct_AgreementBookingProduct { get; set; }
    [ODataMember("msdyn_agreementbookingsetup", true)]
    public msdyn_agreementbookingsetup? msdyn_agreementbookingsetup { get; set; }
    [ODataMember("msdyn_product", true)]
    public product? msdyn_product { get; set; }
    [ODataMember("msdyn_customerasset", true)]
    public msdyn_customerasset? msdyn_customerasset { get; set; }
    [ODataMember("msdyn_pricelist", true)]
    public pricelevel? msdyn_pricelist { get; set; }
    [ODataMember("msdyn_unit", true)]
    public uom? msdyn_unit { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_adx_alertsubscriptions", true)]
    public List<adx_alertsubscription>? msdyn_agreementbookingproduct_adx_alertsubscriptions { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_adx_inviteredemptions", true)]
    public List<adx_inviteredemption>? msdyn_agreementbookingproduct_adx_inviteredemptions { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_adx_portalcomments", true)]
    public List<adx_portalcomment>? msdyn_agreementbookingproduct_adx_portalcomments { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_chats", true)]
    public List<chat>? msdyn_agreementbookingproduct_chats { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msdyn_ocliveworkitems", true)]
    public List<msdyn_ocliveworkitem>? msdyn_agreementbookingproduct_msdyn_ocliveworkitems { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msdyn_ocsessions", true)]
    public List<msdyn_ocsession>? msdyn_agreementbookingproduct_msdyn_ocsessions { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_msdyn_copilottranscripts", true)]
    public List<msdyn_copilottranscript>? msdyn_agreementbookingproduct_msdyn_copilottranscripts { get; set; }
    [ODataMember("msdyn_agreementbookingproduct_zync_customerassetnotes", true)]
    public List<zync_customerassetnote>? msdyn_agreementbookingproduct_zync_customerassetnotes { get; set; }

 public string __Key => $"msdyn_agreementbookingproductid={msdyn_agreementbookingproductid}"; 


}

public interface Imsdyn_agreementbookingproductKeys
{
	Guid? msdyn_agreementbookingproductid { get; set; }
    }
