// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_accountkpiitem
/// </summary>

[ODataEntitySet("msdyn_accountkpiitems")]
public partial class msdyn_accountkpiitem : crmbaseentity, ILargeEntitySet, Imsdyn_accountkpiitemKeys
{
    [ODataMember("msdyn_emaillinksclicked")]
    public decimal? msdyn_emaillinksclicked { get; set; }
    [ODataMember("msdyn_accountkpiitemid")]
    public Guid? msdyn_accountkpiitemid { get; set; }
    [ODataMember("msdyn_responseratebythem")]
    public decimal? msdyn_responseratebythem { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("msdyn_emailssent")]
    public int? msdyn_emailssent { get; set; }
    [ODataMember("msdyn_averagefirstresponsetimebytheminhrs")]
    public decimal? msdyn_averagefirstresponsetimebytheminhrs { get; set; }
    [ODataMember("_msdyn_accountid_value")]
    public Guid? _msdyn_accountid_value { get; set; }
    [ODataMember("msdyn_meetingssent")]
    public int? msdyn_meetingssent { get; set; }
    [ODataMember("msdyn_relationshiphealthscorestate")]
    public int? msdyn_relationshiphealthscorestate { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_phonecallsmade")]
    public int? msdyn_phonecallsmade { get; set; }
    [ODataMember("msdyn_meetingsreceived")]
    public int? msdyn_meetingsreceived { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("msdyn_responseratebyus")]
    public decimal? msdyn_responseratebyus { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("msdyn_acilastupdatetimestamp")]
    public DateTimeOffset? msdyn_acilastupdatetimestamp { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_openedemails")]
    public decimal? msdyn_openedemails { get; set; }
    [ODataMember("msdyn_timespentbycustomer_calculated")]
    public decimal? msdyn_timespentbycustomer_calculated { get; set; }
    [ODataMember("msdyn_timespentbycustomer")]
    public int? msdyn_timespentbycustomer { get; set; }
    [ODataMember("msdyn_timespentbyteam")]
    public int? msdyn_timespentbyteam { get; set; }
    [ODataMember("msdyn_timespentbyteam_calculated")]
    public decimal? msdyn_timespentbyteam_calculated { get; set; }
    [ODataMember("msdyn_phonecallsreceived")]
    public int? msdyn_phonecallsreceived { get; set; }
    [ODataMember("msdyn_emailsreceived")]
    public int? msdyn_emailsreceived { get; set; }
    [ODataMember("msdyn_emailattachmentopens")]
    public decimal? msdyn_emailattachmentopens { get; set; }
    [ODataMember("msdyn_relationshiphealthscorevalue")]
    public int? msdyn_relationshiphealthscorevalue { get; set; }
    [ODataMember("msdyn_averagefirstresponsetimebyusinhrs")]
    public decimal? msdyn_averagefirstresponsetimebyusinhrs { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("msdyn_relationshiphealthtrend")]
    public int? msdyn_relationshiphealthtrend { get; set; }
    [ODataMember("msdyn_liemailssent")]
    public int? msdyn_liemailssent { get; set; }
    [ODataMember("msdyn_facetimewithcustomer")]
    public int? msdyn_facetimewithcustomer { get; set; }
    [ODataMember("msft_datastate")]
    public int? msft_datastate { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("msdyn_date")]
    public DateTimeOffset? msdyn_date { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_computationaccuracy")]
    public int? msdyn_computationaccuracy { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_accountkpiitem_SyncErrors", true)]
    public List<syncerror>? msdyn_accountkpiitem_SyncErrors { get; set; }
    [ODataMember("msdyn_accountkpiitem_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_accountkpiitem_AsyncOperations { get; set; }
    [ODataMember("msdyn_accountkpiitem_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_accountkpiitem_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_accountkpiitem_ProcessSession", true)]
    public List<processsession>? msdyn_accountkpiitem_ProcessSession { get; set; }
    [ODataMember("msdyn_accountkpiitem_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_accountkpiitem_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_accountkpiitem_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_accountkpiitem_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_accountid", true)]
    public account? msdyn_accountid { get; set; }
    [ODataMember("msdyn_msdyn_accountkpiitem_account_accountkpiid", true)]
    public List<account>? msdyn_msdyn_accountkpiitem_account_accountkpiid { get; set; }

 public string __Key => $"msdyn_accountkpiitemid={msdyn_accountkpiitemid}"; 


}

public interface Imsdyn_accountkpiitemKeys
{
	Guid? msdyn_accountkpiitemid { get; set; }
    }
