// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_msdyn_ocrichobject_liveworkstream
/// </summary>

[ODataEntitySet("msdyn_msdyn_ocrichobject_liveworkstreamset")]
public partial class msdyn_msdyn_ocrichobject_liveworkstream : crmbaseentity, ILargeEntitySet, Imsdyn_msdyn_ocrichobject_liveworkstreamKeys
{
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("msdyn_liveworkstreamid")]
    public Guid? msdyn_liveworkstreamid { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("msdyn_msdyn_ocrichobject_liveworkstreamid")]
    public Guid? msdyn_msdyn_ocrichobject_liveworkstreamid { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("msdyn_ocrichobjectid")]
    public Guid? msdyn_ocrichobjectid { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    
    //Navigations

 public string __Key => $"msdyn_msdyn_ocrichobject_liveworkstreamid={msdyn_msdyn_ocrichobject_liveworkstreamid}"; 


}

public interface Imsdyn_msdyn_ocrichobject_liveworkstreamKeys
{
	Guid? msdyn_msdyn_ocrichobject_liveworkstreamid { get; set; }
    }
