// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_quotebookingsetup
/// </summary>

[ODataEntitySet("msdyn_quotebookingsetups")]
public partial class msdyn_quotebookingsetup : crmbaseentity, ILargeEntitySet, Imsdyn_quotebookingsetupKeys
{
    [ODataMember("msdyn_estimatedmargin")]
    public decimal? msdyn_estimatedmargin { get; set; }
    [ODataMember("_msdyn_workordertype_value")]
    public Guid? _msdyn_workordertype_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_estimatedcost")]
    public decimal? msdyn_estimatedcost { get; set; }
    [ODataMember("msdyn_estimatedservicecost_base")]
    public decimal? msdyn_estimatedservicecost_base { get; set; }
    [ODataMember("msdyn_estimatedproductrevenue")]
    public decimal? msdyn_estimatedproductrevenue { get; set; }
    [ODataMember("msdyn_workordersummary")]
    public string? msdyn_workordersummary { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("msdyn_estimatedmarginperwo")]
    public decimal? msdyn_estimatedmarginperwo { get; set; }
    [ODataMember("msdyn_longitude")]
    public double? msdyn_longitude { get; set; }
    [ODataMember("msdyn_preferredstarttime")]
    public DateTimeOffset? msdyn_preferredstarttime { get; set; }
    [ODataMember("msdyn_estimatedrevenueperwo")]
    public decimal? msdyn_estimatedrevenueperwo { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_recurrencesettings")]
    public string? msdyn_recurrencesettings { get; set; }
    [ODataMember("msdyn_autogeneratebooking")]
    public bool? msdyn_autogeneratebooking { get; set; }
    [ODataMember("msdyn_postponegenerationuntil")]
    public DateTimeOffset? msdyn_postponegenerationuntil { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_Internalflags")]
    public string? msdyn_Internalflags { get; set; }
    [ODataMember("msdyn_revision")]
    public int? msdyn_revision { get; set; }
    [ODataMember("msdyn_timewindowend")]
    public DateTimeOffset? msdyn_timewindowend { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("msdyn_estimatedproductrevenue_base")]
    public decimal? msdyn_estimatedproductrevenue_base { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("msdyn_latitude")]
    public double? msdyn_latitude { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_transactioncurrencyid_value")]
    public Guid? _transactioncurrencyid_value { get; set; }
    [ODataMember("msdyn_estimatedservicerevenue_base")]
    public decimal? msdyn_estimatedservicerevenue_base { get; set; }
    [ODataMember("_msdyn_preferredresource_value")]
    public Guid? _msdyn_preferredresource_value { get; set; }
    [ODataMember("_stageid_value")]
    public Guid? _stageid_value { get; set; }
    [ODataMember("msdyn_estimatedcost_base")]
    public decimal? msdyn_estimatedcost_base { get; set; }
    [ODataMember("msdyn_worklocation")]
    public int? msdyn_worklocation { get; set; }
    [ODataMember("processid")]
    public Guid? processid { get; set; }
    [ODataMember("_msdyn_priority_value")]
    public Guid? _msdyn_priority_value { get; set; }
    [ODataMember("msdyn_estimatedduration")]
    public int? msdyn_estimatedduration { get; set; }
    [ODataMember("msdyn_quotedetailid")]
    public string? msdyn_quotedetailid { get; set; }
    [ODataMember("msdyn_estimatedrevenue_base")]
    public decimal? msdyn_estimatedrevenue_base { get; set; }
    [ODataMember("msdyn_description")]
    public string? msdyn_description { get; set; }
    [ODataMember("msdyn_timewindowstart")]
    public DateTimeOffset? msdyn_timewindowstart { get; set; }
    [ODataMember("msdyn_generateworkorderdaysinadvance")]
    public int? msdyn_generateworkorderdaysinadvance { get; set; }
    [ODataMember("msdyn_margin")]
    public decimal? msdyn_margin { get; set; }
    [ODataMember("msdyn_estimatedproductcost")]
    public decimal? msdyn_estimatedproductcost { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_postbookingflexibility")]
    public int? msdyn_postbookingflexibility { get; set; }
    [ODataMember("msdyn_quotebookingsetupid")]
    public Guid? msdyn_quotebookingsetupid { get; set; }
    [ODataMember("msft_datastate")]
    public int? msft_datastate { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("msdyn_numberofwo")]
    public int? msdyn_numberofwo { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_msdyn_quote_value")]
    public Guid? _msdyn_quote_value { get; set; }
    [ODataMember("msdyn_estimatedrevenue")]
    public decimal? msdyn_estimatedrevenue { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("msdyn_estimatedproductcost_base")]
    public decimal? msdyn_estimatedproductcost_base { get; set; }
    [ODataMember("_msdyn_quotedetail_msdyn_quotebookingset_value")]
    public Guid? _msdyn_quotedetail_msdyn_quotebookingset_value { get; set; }
    [ODataMember("traversedpath")]
    public string? traversedpath { get; set; }
    [ODataMember("exchangerate")]
    public decimal? exchangerate { get; set; }
    [ODataMember("msdyn_estimatedrevenueperwo_base")]
    public decimal? msdyn_estimatedrevenueperwo_base { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_prebookingflexibility")]
    public int? msdyn_prebookingflexibility { get; set; }
    [ODataMember("msdyn_estimatedservicerevenue")]
    public decimal? msdyn_estimatedservicerevenue { get; set; }
    [ODataMember("msdyn_autogenerateworkorder")]
    public bool? msdyn_autogenerateworkorder { get; set; }
    [ODataMember("msdyn_estimatedservicecost")]
    public decimal? msdyn_estimatedservicecost { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_quotebookingsetup_SyncErrors", true)]
    public List<syncerror>? msdyn_quotebookingsetup_SyncErrors { get; set; }
    [ODataMember("msdyn_quotebookingsetup_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_quotebookingsetup_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_quotebookingsetup_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_quotebookingsetup_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_quotebookingsetup_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_quotebookingsetup_AsyncOperations { get; set; }
    [ODataMember("msdyn_quotebookingsetup_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_quotebookingsetup_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_quotebookingsetup_ProcessSession", true)]
    public List<processsession>? msdyn_quotebookingsetup_ProcessSession { get; set; }
    [ODataMember("msdyn_quotebookingsetup_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_quotebookingsetup_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("stageid", true)]
    public processstage? stageid { get; set; }
    [ODataMember("transactioncurrencyid", true)]
    public transactioncurrency? transactioncurrencyid { get; set; }
    [ODataMember("msdyn_priority", true)]
    public msdyn_priority? msdyn_priority { get; set; }
    [ODataMember("msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup", true)]
    public List<msdyn_quotebookingincident>? msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup { get; set; }
    [ODataMember("msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup", true)]
    public List<msdyn_quotebookingproduct>? msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup { get; set; }
    [ODataMember("msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup", true)]
    public List<msdyn_quotebookingservice>? msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup { get; set; }
    [ODataMember("msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup", true)]
    public List<msdyn_quotebookingservicetask>? msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup { get; set; }
    [ODataMember("msdyn_preferredresource", true)]
    public bookableresource? msdyn_preferredresource { get; set; }
    [ODataMember("msdyn_workordertype", true)]
    public msdyn_workordertype? msdyn_workordertype { get; set; }
    [ODataMember("msdyn_quote", true)]
    public quote? msdyn_quote { get; set; }
    [ODataMember("msdyn_quotedetail_msdyn_quotebookingset", true)]
    public quotedetail? msdyn_quotedetail_msdyn_quotebookingset { get; set; }

 public string __Key => $"msdyn_quotebookingsetupid={msdyn_quotebookingsetupid}"; 


}

public interface Imsdyn_quotebookingsetupKeys
{
	Guid? msdyn_quotebookingsetupid { get; set; }
    }
