// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_virtualtablecolumncandidate
/// </summary>

[ODataEntitySet("msdyn_virtualtablecolumncandidates")]
public partial class msdyn_virtualtablecolumncandidate : crmbaseentity, ILargeEntitySet, Imsdyn_virtualtablecolumncandidateKeys
{
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("msdyn_externalname")]
    public string? msdyn_externalname { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidateid")]
    public Guid? msdyn_virtualtablecolumncandidateid { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("msdyn_schemaname")]
    public string? msdyn_schemaname { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_displayname")]
    public string? msdyn_displayname { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_SyncErrors", true)]
    public List<syncerror>? msdyn_virtualtablecolumncandidate_SyncErrors { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_virtualtablecolumncandidate_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_virtualtablecolumncandidate_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_virtualtablecolumncandidate_AsyncOperations { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_virtualtablecolumncandidate_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_ProcessSession", true)]
    public List<processsession>? msdyn_virtualtablecolumncandidate_ProcessSession { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_virtualtablecolumncandidate_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_virtualtablecolumncandidate_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_virtualtablecolumncandidate_PrincipalObjectAttributeAccesses { get; set; }

 public string __Key => $"msdyn_virtualtablecolumncandidateid={msdyn_virtualtablecolumncandidateid}"; 


}

public interface Imsdyn_virtualtablecolumncandidateKeys
{
	Guid? msdyn_virtualtablecolumncandidateid { get; set; }
    }
