// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_consoleapplicationtype
/// </summary>

[ODataEntitySet("msdyn_consoleapplicationtypes")]
public partial class msdyn_consoleapplicationtype : crmbaseentity, ILargeEntitySet, Imsdyn_consoleapplicationtypeKeys
{
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_templateparameters")]
    public string? msdyn_templateparameters { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_consoleapplicationtypeid")]
    public Guid? msdyn_consoleapplicationtypeid { get; set; }
    [ODataMember("msdyn_displayname")]
    public string? msdyn_displayname { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_renderingorder")]
    public int? msdyn_renderingorder { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_SyncErrors", true)]
    public List<syncerror>? msdyn_consoleapplicationtype_SyncErrors { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_consoleapplicationtype_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_consoleapplicationtype_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_consoleapplicationtype_AsyncOperations { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_consoleapplicationtype_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_ProcessSession", true)]
    public List<processsession>? msdyn_consoleapplicationtype_ProcessSession { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_consoleapplicationtype_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_consoleapplicationtype_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_consoleapplicationtype_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_msdyn_consoleapplicationtype_msdyn_consol", true)]
    public List<msdyn_consoleappparameterdefinition>? msdyn_msdyn_consoleapplicationtype_msdyn_consol { get; set; }
    [ODataMember("msdyn_msdyn_consoleapplicationtype_msdyn_consoleapplicationtemplate_PageType", true)]
    public List<msdyn_consoleapplicationtemplate>? msdyn_msdyn_consoleapplicationtype_msdyn_consoleapplicationtemplate_PageType { get; set; }

 public string __Key => $"msdyn_consoleapplicationtypeid={msdyn_consoleapplicationtypeid}"; 


}

public interface Imsdyn_consoleapplicationtypeKeys
{
	Guid? msdyn_consoleapplicationtypeid { get; set; }
    }
