// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_playbooktemplate
/// </summary>

[ODataEntitySet("msdyn_playbooktemplates")]
public partial class msdyn_playbooktemplate : crmbaseentity, ILargeEntitySet, Imsdyn_playbooktemplateKeys
{
    [ODataMember("msdyn_estimatedduration")]
    public int? msdyn_estimatedduration { get; set; }
    [ODataMember("msdyn_fullentitylist")]
    public string? msdyn_fullentitylist { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("msdyn_trackprogress")]
    public bool? msdyn_trackprogress { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("msdyn_playbooktemplateid")]
    public Guid? msdyn_playbooktemplateid { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("msdyn_relatedentitylist")]
    public string? msdyn_relatedentitylist { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("_msdyn_categoryid_value")]
    public Guid? _msdyn_categoryid_value { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("msdyn_description")]
    public string? msdyn_description { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_playbooktemplate_SyncErrors", true)]
    public List<syncerror>? msdyn_playbooktemplate_SyncErrors { get; set; }
    [ODataMember("msdyn_playbooktemplate_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_playbooktemplate_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_playbooktemplate_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_playbooktemplate_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_playbooktemplate_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_playbooktemplate_AsyncOperations { get; set; }
    [ODataMember("msdyn_playbooktemplate_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_playbooktemplate_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_playbooktemplate_ProcessSession", true)]
    public List<processsession>? msdyn_playbooktemplate_ProcessSession { get; set; }
    [ODataMember("msdyn_playbooktemplate_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_playbooktemplate_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_playbooktemplate_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_playbooktemplate_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_playbooktemplate_Annotations", true)]
    public List<annotation>? msdyn_playbooktemplate_Annotations { get; set; }
    [ODataMember("msdyn_playbooktemplate_msdyn_playbookinstance", true)]
    public List<msdyn_playbookinstance>? msdyn_playbooktemplate_msdyn_playbookinstance { get; set; }
    [ODataMember("msdyn_categoryid", true)]
    public msdyn_playbookcategory? msdyn_categoryid { get; set; }
    [ODataMember("msdyn_playbooktemplate_msdyn_playbookactivity", true)]
    public List<msdyn_playbookactivity>? msdyn_playbooktemplate_msdyn_playbookactivity { get; set; }
    [ODataMember("msdyn_callablecontext_msdyn_playbooktemplate", true)]
    public List<msdyn_callablecontext>? msdyn_callablecontext_msdyn_playbooktemplate { get; set; }

 public string __Key => $"msdyn_playbooktemplateid={msdyn_playbooktemplateid}"; 


}

public interface Imsdyn_playbooktemplateKeys
{
	Guid? msdyn_playbooktemplateid { get; set; }
    }
