// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_msdyn_paneconfig_msdyn_appconfig
/// </summary>

[ODataEntitySet("msdyn_msdyn_paneconfig_msdyn_appconfigset")]
public partial class msdyn_msdyn_paneconfig_msdyn_appconfig : crmbaseentity, ILargeEntitySet, Imsdyn_msdyn_paneconfig_msdyn_appconfigKeys
{
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("msdyn_appconfigurationid")]
    public Guid? msdyn_appconfigurationid { get; set; }
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("msdyn_paneconfigurationid")]
    public Guid? msdyn_paneconfigurationid { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("msdyn_msdyn_paneconfig_msdyn_appconfigid")]
    public Guid? msdyn_msdyn_paneconfig_msdyn_appconfigid { get; set; }
    
    //Navigations

 public string __Key => $"msdyn_msdyn_paneconfig_msdyn_appconfigid={msdyn_msdyn_paneconfig_msdyn_appconfigid}"; 


}

public interface Imsdyn_msdyn_paneconfig_msdyn_appconfigKeys
{
	Guid? msdyn_msdyn_paneconfig_msdyn_appconfigid { get; set; }
    }
