// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_aitemplate
/// </summary>

[ODataEntitySet("msdyn_aitemplates")]
public partial class msdyn_aitemplate : crmbaseentity, ILargeEntitySet, Imsdyn_aitemplateKeys
{
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("introducedversion")]
    public string? introducedversion { get; set; }
    [ODataMember("msdyn_databinding")]
    public string? msdyn_databinding { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("msdyn_aitemplateid")]
    public Guid? msdyn_aitemplateid { get; set; }
    [ODataMember("msdyn_runconfigschema")]
    public string? msdyn_runconfigschema { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_resourceinfo")]
    public string? msdyn_resourceinfo { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("msdyn_defaultrunschedulingoptions")]
    public string? msdyn_defaultrunschedulingoptions { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("msdyn_uniquename")]
    public string? msdyn_uniquename { get; set; }
    [ODataMember("msdyn_trainingdataspecification")]
    public string? msdyn_trainingdataspecification { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("msdyn_modelaction")]
    public string? msdyn_modelaction { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_uxconfiguration")]
    public string? msdyn_uxconfiguration { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("msdyn_rundataspecification")]
    public string? msdyn_rundataspecification { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("msdyn_trainingconfigschema")]
    public string? msdyn_trainingconfigschema { get; set; }
    [ODataMember("msdyn_aitemplateidunique")]
    public Guid? msdyn_aitemplateidunique { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("msdyn_istrainable")]
    public bool? msdyn_istrainable { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("msdyn_templateversion")]
    public int? msdyn_templateversion { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_aitemplate_SyncErrors", true)]
    public List<syncerror>? msdyn_aitemplate_SyncErrors { get; set; }
    [ODataMember("msdyn_aitemplate_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_aitemplate_AsyncOperations { get; set; }
    [ODataMember("msdyn_aitemplate_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_aitemplate_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_aitemplate_ProcessSession", true)]
    public List<processsession>? msdyn_aitemplate_ProcessSession { get; set; }
    [ODataMember("msdyn_aitemplate_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_aitemplate_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_aitemplate_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_aitemplate_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_aitemplate_msdyn_aimodel", true)]
    public List<msdyn_aimodel>? msdyn_aitemplate_msdyn_aimodel { get; set; }

 public string __Key => $"msdyn_aitemplateid={msdyn_aitemplateid}"; 


}

public interface Imsdyn_aitemplateKeys
{
	Guid? msdyn_aitemplateid { get; set; }
    }
