// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_attribute
/// </summary>

[ODataEntitySet("msdyn_attribute")]
public partial class msdyn_attribute : crmbaseentity, ILargeEntitySet, Imsdyn_attributeKeys
{
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("msdyn_linkedattributename")]
    public string? msdyn_linkedattributename { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("msdyn_attributeid")]
    public Guid? msdyn_attributeid { get; set; }
    [ODataMember("msdyn_autogenerateattributevalues")]
    public bool? msdyn_autogenerateattributevalues { get; set; }
    [ODataMember("msdyn_linkedobjecttypecode")]
    public int? msdyn_linkedobjecttypecode { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("msdyn_reviewstatus")]
    public int? msdyn_reviewstatus { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_attribute_SyncErrors", true)]
    public List<syncerror>? msdyn_attribute_SyncErrors { get; set; }
    [ODataMember("msdyn_attribute_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_attribute_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_attribute_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_attribute_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_attribute_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_attribute_AsyncOperations { get; set; }
    [ODataMember("msdyn_attribute_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_attribute_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_attribute_ProcessSession", true)]
    public List<processsession>? msdyn_attribute_ProcessSession { get; set; }
    [ODataMember("msdyn_attribute_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_attribute_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_attribute_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_attribute_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_attributeparent", true)]
    public List<msdyn_attributevalue>? msdyn_attributeparent { get; set; }

 public string __Key => $"msdyn_attributeid={msdyn_attributeid}"; 


}

public interface Imsdyn_attributeKeys
{
	Guid? msdyn_attributeid { get; set; }
    }
