// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_timeoffrequest
/// </summary>

[ODataEntitySet("msdyn_timeoffrequests")]
public partial class msdyn_timeoffrequest : crmbaseentity, ILargeEntitySet, Imsdyn_timeoffrequestKeys
{
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("msdyn_timeoffrequestid")]
    public Guid? msdyn_timeoffrequestid { get; set; }
    [ODataMember("_msdyn_approvedby_value")]
    public Guid? _msdyn_approvedby_value { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_duration")]
    public int? msdyn_duration { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("msdyn_starttime")]
    public DateTimeOffset? msdyn_starttime { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("msdyn_name")]
    public string? msdyn_name { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("msdyn_internalflags")]
    public string? msdyn_internalflags { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("msdyn_endtime")]
    public DateTimeOffset? msdyn_endtime { get; set; }
    [ODataMember("_msdyn_resource_value")]
    public Guid? _msdyn_resource_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_timeoffrequest_ActivityPointers", true)]
    public List<activitypointer>? msdyn_timeoffrequest_ActivityPointers { get; set; }
    [ODataMember("msdyn_timeoffrequest_li_inmails", true)]
    public List<li_inmail>? msdyn_timeoffrequest_li_inmails { get; set; }
    [ODataMember("msdyn_timeoffrequest_msfp_surveyinvites", true)]
    public List<msfp_surveyinvite>? msdyn_timeoffrequest_msfp_surveyinvites { get; set; }
    [ODataMember("msdyn_timeoffrequest_li_messages", true)]
    public List<li_message>? msdyn_timeoffrequest_li_messages { get; set; }
    [ODataMember("msdyn_timeoffrequest_msfp_alerts", true)]
    public List<msfp_alert>? msdyn_timeoffrequest_msfp_alerts { get; set; }
    [ODataMember("msdyn_timeoffrequest_msdyn_bookingalerts", true)]
    public List<msdyn_bookingalert>? msdyn_timeoffrequest_msdyn_bookingalerts { get; set; }
    [ODataMember("msdyn_timeoffrequest_li_pointdrivepresentationvieweds", true)]
    public List<li_pointdrivepresentationviewed>? msdyn_timeoffrequest_li_pointdrivepresentationvieweds { get; set; }
    [ODataMember("msdyn_timeoffrequest_zync_logs", true)]
    public List<zync_log>? msdyn_timeoffrequest_zync_logs { get; set; }
    [ODataMember("msdyn_timeoffrequest_msfp_surveyresponses", true)]
    public List<msfp_surveyresponse>? msdyn_timeoffrequest_msfp_surveyresponses { get; set; }
    [ODataMember("msdyn_timeoffrequest_SyncErrors", true)]
    public List<syncerror>? msdyn_timeoffrequest_SyncErrors { get; set; }
    [ODataMember("msdyn_timeoffrequest_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? msdyn_timeoffrequest_DuplicateMatchingRecord { get; set; }
    [ODataMember("msdyn_timeoffrequest_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? msdyn_timeoffrequest_DuplicateBaseRecord { get; set; }
    [ODataMember("msdyn_timeoffrequest_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_timeoffrequest_AsyncOperations { get; set; }
    [ODataMember("msdyn_timeoffrequest_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_timeoffrequest_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_timeoffrequest_ProcessSession", true)]
    public List<processsession>? msdyn_timeoffrequest_ProcessSession { get; set; }
    [ODataMember("msdyn_timeoffrequest_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_timeoffrequest_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_timeoffrequest_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_timeoffrequest_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_timeoffrequest_Appointments", true)]
    public List<appointment>? msdyn_timeoffrequest_Appointments { get; set; }
    [ODataMember("msdyn_timeoffrequest_Emails", true)]
    public List<email>? msdyn_timeoffrequest_Emails { get; set; }
    [ODataMember("msdyn_timeoffrequest_Faxes", true)]
    public List<fax>? msdyn_timeoffrequest_Faxes { get; set; }
    [ODataMember("msdyn_timeoffrequest_Letters", true)]
    public List<letter>? msdyn_timeoffrequest_Letters { get; set; }
    [ODataMember("msdyn_timeoffrequest_PhoneCalls", true)]
    public List<phonecall>? msdyn_timeoffrequest_PhoneCalls { get; set; }
    [ODataMember("msdyn_timeoffrequest_Tasks", true)]
    public List<task>? msdyn_timeoffrequest_Tasks { get; set; }
    [ODataMember("msdyn_timeoffrequest_RecurringAppointmentMasters", true)]
    public List<recurringappointmentmaster>? msdyn_timeoffrequest_RecurringAppointmentMasters { get; set; }
    [ODataMember("msdyn_timeoffrequest_SocialActivities", true)]
    public List<socialactivity>? msdyn_timeoffrequest_SocialActivities { get; set; }
    [ODataMember("msdyn_timeoffrequest_connections1", true)]
    public List<connection>? msdyn_timeoffrequest_connections1 { get; set; }
    [ODataMember("msdyn_timeoffrequest_connections2", true)]
    public List<connection>? msdyn_timeoffrequest_connections2 { get; set; }
    [ODataMember("msdyn_timeoffrequest_Annotations", true)]
    public List<annotation>? msdyn_timeoffrequest_Annotations { get; set; }
    [ODataMember("msdyn_timeoffrequest_ServiceAppointments", true)]
    public List<serviceappointment>? msdyn_timeoffrequest_ServiceAppointments { get; set; }
    [ODataMember("msdyn_resource", true)]
    public bookableresource? msdyn_resource { get; set; }
    [ODataMember("msdyn_approvedby", true)]
    public systemuser? msdyn_approvedby { get; set; }
    [ODataMember("msdyn_msdyn_timeoffrequest_msdyn_timeentry", true)]
    public List<msdyn_timeentry>? msdyn_msdyn_timeoffrequest_msdyn_timeentry { get; set; }
    [ODataMember("msdyn_timeoffrequest_adx_alertsubscriptions", true)]
    public List<adx_alertsubscription>? msdyn_timeoffrequest_adx_alertsubscriptions { get; set; }
    [ODataMember("msdyn_timeoffrequest_adx_inviteredemptions", true)]
    public List<adx_inviteredemption>? msdyn_timeoffrequest_adx_inviteredemptions { get; set; }
    [ODataMember("msdyn_timeoffrequest_adx_portalcomments", true)]
    public List<adx_portalcomment>? msdyn_timeoffrequest_adx_portalcomments { get; set; }
    [ODataMember("msdyn_timeoffrequest_chats", true)]
    public List<chat>? msdyn_timeoffrequest_chats { get; set; }
    [ODataMember("msdyn_timeoffrequest_msdyn_ocliveworkitems", true)]
    public List<msdyn_ocliveworkitem>? msdyn_timeoffrequest_msdyn_ocliveworkitems { get; set; }
    [ODataMember("msdyn_timeoffrequest_msdyn_ocsessions", true)]
    public List<msdyn_ocsession>? msdyn_timeoffrequest_msdyn_ocsessions { get; set; }
    [ODataMember("msdyn_timeoffrequest_msdyn_copilottranscripts", true)]
    public List<msdyn_copilottranscript>? msdyn_timeoffrequest_msdyn_copilottranscripts { get; set; }
    [ODataMember("msdyn_timeoffrequest_zync_customerassetnotes", true)]
    public List<zync_customerassetnote>? msdyn_timeoffrequest_zync_customerassetnotes { get; set; }

 public string __Key => $"msdyn_timeoffrequestid={msdyn_timeoffrequestid}"; 


}

public interface Imsdyn_timeoffrequestKeys
{
	Guid? msdyn_timeoffrequestid { get; set; }
    }
