// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: msdyn_dispositioncodecategory
/// </summary>

[ODataEntitySet("msdyn_dispositioncodecategories")]
public partial class msdyn_dispositioncodecategory : crmbaseentity, ILargeEntitySet, Imsdyn_dispositioncodecategoryKeys
{
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("msdyn_categoryname")]
    public string? msdyn_categoryname { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("msdyn_dispositioncodecategoryid")]
    public Guid? msdyn_dispositioncodecategoryid { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_SyncErrors", true)]
    public List<syncerror>? msdyn_dispositioncodecategory_SyncErrors { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_AsyncOperations", true)]
    public List<asyncoperation>? msdyn_dispositioncodecategory_AsyncOperations { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? msdyn_dispositioncodecategory_MailboxTrackingFolders { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_ProcessSession", true)]
    public List<processsession>? msdyn_dispositioncodecategory_ProcessSession { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? msdyn_dispositioncodecategory_BulkDeleteFailures { get; set; }
    [ODataMember("msdyn_dispositioncodecategory_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? msdyn_dispositioncodecategory_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("msdyn_ocdispositioncode_dispositioncodecategoryid_msdyn_dispositioncodecategory", true)]
    public List<msdyn_ocdispositioncode>? msdyn_ocdispositioncode_dispositioncodecategoryid_msdyn_dispositioncodecategory { get; set; }

 public string __Key => $"msdyn_dispositioncodecategoryid={msdyn_dispositioncodecategoryid}"; 


}

public interface Imsdyn_dispositioncodecategoryKeys
{
	Guid? msdyn_dispositioncodecategoryid { get; set; }
    }
