// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: mspcat_packagestore
/// </summary>

[ODataEntitySet("mspcat_packagestores")]
public partial class mspcat_packagestore : crmbaseentity, ILargeEntitySet, Imspcat_packagestoreKeys
{
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("mspcat_packagestoreid")]
    public Guid? mspcat_packagestoreid { get; set; }
    [ODataMember("mspcat_solutionuniquename")]
    public string? mspcat_solutionuniquename { get; set; }
    [ODataMember("mspcat_name")]
    public string? mspcat_name { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("mspcat_operation")]
    public int? mspcat_operation { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("mspcat_processingmessage")]
    public string? mspcat_processingmessage { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("mspcat_packagefile_name")]
    public string? mspcat_packagefile_name { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("mspcat_asyncoperationid")]
    public string? mspcat_asyncoperationid { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("mspcat_packagefile")]
    public byte[]? mspcat_packagefile { get; set; }
    [ODataMember("mspcat_intendeddeploymenttype")]
    public int? mspcat_intendeddeploymenttype { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("mspcat_packagestore_SyncErrors", true)]
    public List<syncerror>? mspcat_packagestore_SyncErrors { get; set; }
    [ODataMember("mspcat_packagestore_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? mspcat_packagestore_DuplicateMatchingRecord { get; set; }
    [ODataMember("mspcat_packagestore_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? mspcat_packagestore_DuplicateBaseRecord { get; set; }
    [ODataMember("mspcat_packagestore_AsyncOperations", true)]
    public List<asyncoperation>? mspcat_packagestore_AsyncOperations { get; set; }
    [ODataMember("mspcat_packagestore_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? mspcat_packagestore_MailboxTrackingFolders { get; set; }
    [ODataMember("mspcat_packagestore_ProcessSession", true)]
    public List<processsession>? mspcat_packagestore_ProcessSession { get; set; }
    [ODataMember("mspcat_packagestore_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? mspcat_packagestore_BulkDeleteFailures { get; set; }
    [ODataMember("mspcat_packagestore_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? mspcat_packagestore_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("mspcat_packagestore_FileAttachments", true)]
    public List<fileattachment>? mspcat_packagestore_FileAttachments { get; set; }
    [ODataMember("mspcat_mspcat_catalogsubmissionfiles_PackageStor", true)]
    public List<mspcat_catalogsubmissionfiles>? mspcat_mspcat_catalogsubmissionfiles_PackageStor { get; set; }

 public string __Key => $"mspcat_packagestoreid={mspcat_packagestoreid}"; 


}

public interface Imspcat_packagestoreKeys
{
	Guid? mspcat_packagestoreid { get; set; }
    }
