// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: nlsqregistration
/// </summary>

[ODataEntitySet("nlsqregistrations")]
public partial class nlsqregistration : crmbaseentity, ILargeEntitySet, InlsqregistrationKeys
{
    [ODataMember("registrationstatus")]
    public int? registrationstatus { get; set; }
    [ODataMember("errormessage")]
    public string? errormessage { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("partitionid")]
    public string? partitionid { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("nlsqregistrationid")]
    public Guid? nlsqregistrationid { get; set; }
    [ODataMember("objecttype")]
    public string? objecttype { get; set; }
    [ODataMember("ttlinseconds")]
    public int? ttlinseconds { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("objectid")]
    public string? objectid { get; set; }
    [ODataMember("_skill_value")]
    public Guid? _skill_value { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("objectpartitionid")]
    public string? objectpartitionid { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("allowedentitylist")]
    public string? allowedentitylist { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("objecttypedisplayname")]
    public string? objecttypedisplayname { get; set; }
    [ODataMember("entitylist")]
    public string? entitylist { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("objecttypeid")]
    public string? objecttypeid { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }

 public string __Key => $"nlsqregistrationid={nlsqregistrationid}"; 


}

public interface InlsqregistrationKeys
{
	Guid? nlsqregistrationid { get; set; }
    }
