// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: plannerbusinessscenario
/// </summary>

[ODataEntitySet("plannerbusinessscenarios")]
public partial class plannerbusinessscenario : crmbaseentity, ILargeEntitySet, IplannerbusinessscenarioKeys
{
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("uniquename")]
    public string? uniquename { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("webresourcename")]
    public string? webresourcename { get; set; }
    [ODataMember("syncenabled")]
    public bool? syncenabled { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("displayname")]
    public string? displayname { get; set; }
    [ODataMember("plannerbusinessscenarioid")]
    public Guid? plannerbusinessscenarioid { get; set; }
    [ODataMember("buckets")]
    public string? buckets { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    
    //Navigations
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("plannerbusinessscenario_SyncErrors", true)]
    public List<syncerror>? plannerbusinessscenario_SyncErrors { get; set; }
    [ODataMember("plannerbusinessscenario_AsyncOperations", true)]
    public List<asyncoperation>? plannerbusinessscenario_AsyncOperations { get; set; }
    [ODataMember("plannerbusinessscenario_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? plannerbusinessscenario_MailboxTrackingFolders { get; set; }
    [ODataMember("plannerbusinessscenario_ProcessSession", true)]
    public List<processsession>? plannerbusinessscenario_ProcessSession { get; set; }
    [ODataMember("plannerbusinessscenario_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? plannerbusinessscenario_BulkDeleteFailures { get; set; }
    [ODataMember("plannerbusinessscenario_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? plannerbusinessscenario_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("plannerbusinessscenario_plannersyncaction_plannerbusinessscenarioid", true)]
    public List<plannersyncaction>? plannerbusinessscenario_plannersyncaction_plannerbusinessscenarioid { get; set; }

 public string __Key => $"plannerbusinessscenarioid={plannerbusinessscenarioid}"; 


}

public interface IplannerbusinessscenarioKeys
{
	Guid? plannerbusinessscenarioid { get; set; }
    }
