// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: PowerAutomateProxyResponse
/// </summary>


public partial class PowerAutomateProxyResponse 
{
    [ODataMember("HttpStatusCode")]
    public int? HttpStatusCode { get; set; }
    [ODataMember("ResponseHeaders")]
    public string? ResponseHeaders { get; set; }
    [ODataMember("ResponseBody")]
    public string? ResponseBody { get; set; }
    
    //Navigations



}

