// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: processtrigger
/// </summary>

[ODataEntitySet("processtriggers")]
public partial class processtrigger : crmbaseentity, ILargeEntitySet, IprocesstriggerKeys
{
    [ODataMember("processtriggerid")]
    public Guid? processtriggerid { get; set; }
    [ODataMember("_formid_value")]
    public Guid? _formid_value { get; set; }
    [ODataMember("methodid")]
    public Guid? methodid { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("controltype")]
    public int? controltype { get; set; }
    [ODataMember("scope")]
    public int? scope { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("owninguser")]
    public Guid? owninguser { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("processtriggeridunique")]
    public Guid? processtriggeridunique { get; set; }
    [ODataMember("_processid_value")]
    public Guid? _processid_value { get; set; }
    [ODataMember("primaryentitytypecode")]
    public string? primaryentitytypecode { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("owningbusinessunit")]
    public Guid? owningbusinessunit { get; set; }
    [ODataMember("pipelinestage")]
    public int? pipelinestage { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("event")]
    public string? @event { get; set; }
    [ODataMember("controlname")]
    public string? controlname { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    
    //Navigations
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("ProcessTrigger_SyncErrors", true)]
    public List<syncerror>? ProcessTrigger_SyncErrors { get; set; }
    [ODataMember("formid", true)]
    public systemform? formid { get; set; }
    [ODataMember("processid", true)]
    public workflow? processid { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }

 public string __Key => $"processtriggerid={processtriggerid}"; 


}

public interface IprocesstriggerKeys
{
	Guid? processtriggerid { get; set; }
    }
