// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: savingrule
/// </summary>

[ODataEntitySet("savingrules")]
public partial class savingrule : crmbaseentity, ILargeEntitySet, IsavingruleKeys
{
    [ODataMember("_workqueueid_value")]
    public Guid? _workqueueid_value { get; set; }
    [ODataMember("componentstate")]
    public int? componentstate { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("solutionid")]
    public Guid? solutionid { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("ruledata")]
    public string? ruledata { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("ismanaged")]
    public bool? ismanaged { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("componentidunique")]
    public Guid? componentidunique { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("savingruleid")]
    public Guid? savingruleid { get; set; }
    [ODataMember("iscustomizable", true)]
    public BooleanManagedProperty? iscustomizable { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_workflowid_value")]
    public Guid? _workflowid_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("startedon")]
    public DateTimeOffset? startedon { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("overwritetime")]
    public DateTimeOffset? overwritetime { get; set; }
    [ODataMember("endedon")]
    public DateTimeOffset? endedon { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("savingrule_SyncErrors", true)]
    public List<syncerror>? savingrule_SyncErrors { get; set; }
    [ODataMember("savingrule_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? savingrule_DuplicateMatchingRecord { get; set; }
    [ODataMember("savingrule_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? savingrule_DuplicateBaseRecord { get; set; }
    [ODataMember("savingrule_AsyncOperations", true)]
    public List<asyncoperation>? savingrule_AsyncOperations { get; set; }
    [ODataMember("savingrule_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? savingrule_MailboxTrackingFolders { get; set; }
    [ODataMember("savingrule_ProcessSession", true)]
    public List<processsession>? savingrule_ProcessSession { get; set; }
    [ODataMember("savingrule_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? savingrule_BulkDeleteFailures { get; set; }
    [ODataMember("savingrule_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? savingrule_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("workqueueid_workqueue", true)]
    public workqueue? workqueueid_workqueue { get; set; }
    [ODataMember("workflowid_Workflow", true)]
    public workflow? workflowid_Workflow { get; set; }

 public string __Key => $"savingruleid={savingruleid}"; 


}

public interface IsavingruleKeys
{
	Guid? savingruleid { get; set; }
    }
