// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: searchattributesettings
/// </summary>

[ODataEntitySet("searchattributesettingses")]
public partial class searchattributesettings : crmbaseentity, ILargeEntitySet, IsearchattributesettingsKeys
{
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("settings")]
    public string? settings { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("searchattributesettingsid")]
    public Guid? searchattributesettingsid { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("entityname")]
    public string? entityname { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("attributename")]
    public string? attributename { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("searchattributesettings_SyncErrors", true)]
    public List<syncerror>? searchattributesettings_SyncErrors { get; set; }
    [ODataMember("searchattributesettings_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? searchattributesettings_DuplicateMatchingRecord { get; set; }
    [ODataMember("searchattributesettings_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? searchattributesettings_DuplicateBaseRecord { get; set; }
    [ODataMember("searchattributesettings_AsyncOperations", true)]
    public List<asyncoperation>? searchattributesettings_AsyncOperations { get; set; }
    [ODataMember("searchattributesettings_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? searchattributesettings_MailboxTrackingFolders { get; set; }
    [ODataMember("searchattributesettings_ProcessSession", true)]
    public List<processsession>? searchattributesettings_ProcessSession { get; set; }
    [ODataMember("searchattributesettings_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? searchattributesettings_BulkDeleteFailures { get; set; }
    [ODataMember("searchattributesettings_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? searchattributesettings_PrincipalObjectAttributeAccesses { get; set; }

 public string __Key => $"searchattributesettingsid={searchattributesettingsid}"; 


}

public interface IsearchattributesettingsKeys
{
	Guid? searchattributesettingsid { get; set; }
    }
