// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: SolutionValidationResult
/// </summary>


public partial class SolutionValidationResult 
{
    [ODataMember("SolutionValidationResultType", true)]
    public SolutionValidationResultType? SolutionValidationResultType { get; set; }
    [ODataMember("Message")]
    public string? Message { get; set; }
    [ODataMember("ErrorCode")]
    public int? ErrorCode { get; set; }
    [ODataMember("AdditionalInfo")]
    public string? AdditionalInfo { get; set; }
    
    //Navigations



}

