// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: synapselinkexternaltablestate
/// </summary>

[ODataEntitySet("synapselinkexternaltablestates")]
public partial class synapselinkexternaltablestate : crmbaseentity, ILargeEntitySet, IsynapselinkexternaltablestateKeys
{
    [ODataMember("trinostate")]
    public int? trinostate { get; set; }
    [ODataMember("entityname")]
    public string? entityname { get; set; }
    [ODataMember("lakehouseshortcutstate")]
    public int? lakehouseshortcutstate { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_organizationid_value")]
    public Guid? _organizationid_value { get; set; }
    [ODataMember("recordcount")]
    public long? recordcount { get; set; }
    [ODataMember("metadataversion")]
    public string? metadataversion { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("tablestate")]
    public int? tablestate { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("_datalakefolder_value")]
    public Guid? _datalakefolder_value { get; set; }
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("schemamodifiedon")]
    public DateTimeOffset? schemamodifiedon { get; set; }
    [ODataMember("name")]
    public string? name { get; set; }
    [ODataMember("synapseworkspacename")]
    public string? synapseworkspacename { get; set; }
    [ODataMember("synapselinkexternaltablestateid")]
    public Guid? synapselinkexternaltablestateid { get; set; }
    [ODataMember("maxrecordversion")]
    public long? maxrecordversion { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("lastsynchronizedon")]
    public DateTimeOffset? lastsynchronizedon { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("minsynceddataversion")]
    public long? minsynceddataversion { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("synapsedatabasename")]
    public string? synapsedatabasename { get; set; }
    [ODataMember("lastsyncstate")]
    public int? lastsyncstate { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("organizationid", true)]
    public organization? organizationid { get; set; }
    [ODataMember("synapselinkexternaltablestate_SyncErrors", true)]
    public List<syncerror>? synapselinkexternaltablestate_SyncErrors { get; set; }
    [ODataMember("synapselinkexternaltablestate_DuplicateMatchingRecord", true)]
    public List<duplicaterecord>? synapselinkexternaltablestate_DuplicateMatchingRecord { get; set; }
    [ODataMember("synapselinkexternaltablestate_DuplicateBaseRecord", true)]
    public List<duplicaterecord>? synapselinkexternaltablestate_DuplicateBaseRecord { get; set; }
    [ODataMember("synapselinkexternaltablestate_AsyncOperations", true)]
    public List<asyncoperation>? synapselinkexternaltablestate_AsyncOperations { get; set; }
    [ODataMember("synapselinkexternaltablestate_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? synapselinkexternaltablestate_MailboxTrackingFolders { get; set; }
    [ODataMember("synapselinkexternaltablestate_ProcessSession", true)]
    public List<processsession>? synapselinkexternaltablestate_ProcessSession { get; set; }
    [ODataMember("synapselinkexternaltablestate_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? synapselinkexternaltablestate_BulkDeleteFailures { get; set; }
    [ODataMember("synapselinkexternaltablestate_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? synapselinkexternaltablestate_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("datalakefolder", true)]
    public datalakefolder? datalakefolder { get; set; }

 public string __Key => $"synapselinkexternaltablestateid={synapselinkexternaltablestateid}"; 


}

public interface IsynapselinkexternaltablestateKeys
{
	Guid? synapselinkexternaltablestateid { get; set; }
    }
