// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
using Linq2OData.Core;
using System.Text.Json.Serialization;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// ODataName: zync_productinsight
/// </summary>

[ODataEntitySet("zync_productinsights")]
public partial class zync_productinsight : crmbaseentity, ILargeEntitySet, Izync_productinsightKeys
{
    [ODataMember("createdon")]
    public DateTimeOffset? createdon { get; set; }
    [ODataMember("_zync_projectid_value")]
    public Guid? _zync_projectid_value { get; set; }
    [ODataMember("timezoneruleversionnumber")]
    public int? timezoneruleversionnumber { get; set; }
    [ODataMember("zync_value")]
    public string? zync_value { get; set; }
    [ODataMember("statuscode")]
    public int? statuscode { get; set; }
    [ODataMember("modifiedon")]
    public DateTimeOffset? modifiedon { get; set; }
    [ODataMember("zync_actualvalue_base")]
    public decimal? zync_actualvalue_base { get; set; }
    [ODataMember("exchangerate")]
    public decimal? exchangerate { get; set; }
    [ODataMember("_modifiedonbehalfby_value")]
    public Guid? _modifiedonbehalfby_value { get; set; }
    [ODataMember("_ownerid_value")]
    public Guid? _ownerid_value { get; set; }
    [ODataMember("_zync_projectphase_value")]
    public Guid? _zync_projectphase_value { get; set; }
    [ODataMember("_createdby_value")]
    public Guid? _createdby_value { get; set; }
    [ODataMember("versionnumber")]
    public long? versionnumber { get; set; }
    [ODataMember("_owningteam_value")]
    public Guid? _owningteam_value { get; set; }
    [ODataMember("_transactioncurrencyid_value")]
    public Guid? _transactioncurrencyid_value { get; set; }
    [ODataMember("_owninguser_value")]
    public Guid? _owninguser_value { get; set; }
    [ODataMember("zync_businessarea")]
    public string? zync_businessarea { get; set; }
    [ODataMember("zync_name")]
    public string? zync_name { get; set; }
    [ODataMember("importsequencenumber")]
    public int? importsequencenumber { get; set; }
    [ODataMember("zync_businessunit")]
    public string? zync_businessunit { get; set; }
    [ODataMember("_owningbusinessunit_value")]
    public Guid? _owningbusinessunit_value { get; set; }
    [ODataMember("zync_actualvalue")]
    public decimal? zync_actualvalue { get; set; }
    [ODataMember("zync_newcolumn")]
    public string? zync_newcolumn { get; set; }
    [ODataMember("_createdonbehalfby_value")]
    public Guid? _createdonbehalfby_value { get; set; }
    [ODataMember("overriddencreatedon")]
    public DateTimeOffset? overriddencreatedon { get; set; }
    [ODataMember("zync_businesscode")]
    public string? zync_businesscode { get; set; }
    [ODataMember("utcconversiontimezonecode")]
    public int? utcconversiontimezonecode { get; set; }
    [ODataMember("statecode")]
    public int? statecode { get; set; }
    [ODataMember("zync_productinsightid")]
    public Guid? zync_productinsightid { get; set; }
    [ODataMember("_modifiedby_value")]
    public Guid? _modifiedby_value { get; set; }
    
    //Navigations
    [ODataMember("createdby", true)]
    public systemuser? createdby { get; set; }
    [ODataMember("createdonbehalfby", true)]
    public systemuser? createdonbehalfby { get; set; }
    [ODataMember("modifiedby", true)]
    public systemuser? modifiedby { get; set; }
    [ODataMember("modifiedonbehalfby", true)]
    public systemuser? modifiedonbehalfby { get; set; }
    [ODataMember("owninguser", true)]
    public systemuser? owninguser { get; set; }
    [ODataMember("owningteam", true)]
    public team? owningteam { get; set; }
    [ODataMember("ownerid", true)]
    public principal? ownerid { get; set; }
    [ODataMember("owningbusinessunit", true)]
    public businessunit? owningbusinessunit { get; set; }
    [ODataMember("zync_productinsight_SyncErrors", true)]
    public List<syncerror>? zync_productinsight_SyncErrors { get; set; }
    [ODataMember("zync_productinsight_AsyncOperations", true)]
    public List<asyncoperation>? zync_productinsight_AsyncOperations { get; set; }
    [ODataMember("zync_productinsight_MailboxTrackingFolders", true)]
    public List<mailboxtrackingfolder>? zync_productinsight_MailboxTrackingFolders { get; set; }
    [ODataMember("zync_productinsight_ProcessSession", true)]
    public List<processsession>? zync_productinsight_ProcessSession { get; set; }
    [ODataMember("zync_productinsight_BulkDeleteFailures", true)]
    public List<bulkdeletefailure>? zync_productinsight_BulkDeleteFailures { get; set; }
    [ODataMember("zync_productinsight_PrincipalObjectAttributeAccesses", true)]
    public List<principalobjectattributeaccess>? zync_productinsight_PrincipalObjectAttributeAccesses { get; set; }
    [ODataMember("transactioncurrencyid", true)]
    public transactioncurrency? transactioncurrencyid { get; set; }
    [ODataMember("zync_projectid", true)]
    public opportunity? zync_projectid { get; set; }
    [ODataMember("zync_projectphase", true)]
    public zync_projectphase? zync_projectphase { get; set; }

 public string __Key => $"zync_productinsightid={zync_productinsightid}"; 


}

public interface Izync_productinsightKeys
{
	Guid? zync_productinsightid { get; set; }
    }
