// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: adx_webfile
/// </summary>
public partial class adx_webfileInput : ODataInputBase
{
	// IsEnumType: False
    public DateTimeOffset? adx_expirationdate 
	{
		get => GetValue<DateTimeOffset?>("adx_expirationdate");
		set => SetValue("adx_expirationdate", value);
	}
	// IsEnumType: False
    public int? adx_contentdisposition 
	{
		get => GetValue<int?>("adx_contentdisposition");
		set => SetValue("adx_contentdisposition", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public bool? adx_hiddenfromsitemap 
	{
		get => GetValue<bool?>("adx_hiddenfromsitemap");
		set => SetValue("adx_hiddenfromsitemap", value);
	}
	// IsEnumType: False
    public string? adx_cloudblobaddress 
	{
		get => GetValue<string?>("adx_cloudblobaddress");
		set => SetValue("adx_cloudblobaddress", value);
	}
	// IsEnumType: False
    public bool? adx_migratedtofilecontent 
	{
		get => GetValue<bool?>("adx_migratedtofilecontent");
		set => SetValue("adx_migratedtofilecontent", value);
	}
	// IsEnumType: False
    public string? adx_createdbyipaddress 
	{
		get => GetValue<string?>("adx_createdbyipaddress");
		set => SetValue("adx_createdbyipaddress", value);
	}
	// IsEnumType: False
    public DateTimeOffset? adx_releasedate 
	{
		get => GetValue<DateTimeOffset?>("adx_releasedate");
		set => SetValue("adx_releasedate", value);
	}
	// IsEnumType: False
    public string? adx_modifiedbyipaddress 
	{
		get => GetValue<string?>("adx_modifiedbyipaddress");
		set => SetValue("adx_modifiedbyipaddress", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? _adx_parentpageid_value 
	{
		get => GetValue<Guid?>("_adx_parentpageid_value");
		set => SetValue("_adx_parentpageid_value", value);
	}
	// IsEnumType: False
    public string? adx_filecontent_name 
	{
		get => GetValue<string?>("adx_filecontent_name");
		set => SetValue("adx_filecontent_name", value);
	}
	// IsEnumType: False
    public Guid? _adx_masterwebfileid_value 
	{
		get => GetValue<Guid?>("_adx_masterwebfileid_value");
		set => SetValue("_adx_masterwebfileid_value", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public byte[]? adx_filecontent 
	{
		get => GetValue<byte[]?>("adx_filecontent");
		set => SetValue("adx_filecontent", value);
	}
	// IsEnumType: False
    public DateTimeOffset? adx_displaydate 
	{
		get => GetValue<DateTimeOffset?>("adx_displaydate");
		set => SetValue("adx_displaydate", value);
	}
	// IsEnumType: False
    public string? adx_createdbyusername 
	{
		get => GetValue<string?>("adx_createdbyusername");
		set => SetValue("adx_createdbyusername", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public string? adx_modifiedbyusername 
	{
		get => GetValue<string?>("adx_modifiedbyusername");
		set => SetValue("adx_modifiedbyusername", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public string? adx_name 
	{
		get => GetValue<string?>("adx_name");
		set => SetValue("adx_name", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public int? adx_displayorder 
	{
		get => GetValue<int?>("adx_displayorder");
		set => SetValue("adx_displayorder", value);
	}
	// IsEnumType: False
    public Guid? _adx_publishingstateid_value 
	{
		get => GetValue<Guid?>("_adx_publishingstateid_value");
		set => SetValue("_adx_publishingstateid_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? adx_alloworigin 
	{
		get => GetValue<string?>("adx_alloworigin");
		set => SetValue("adx_alloworigin", value);
	}
	// IsEnumType: False
    public bool? adx_enabletracking 
	{
		get => GetValue<bool?>("adx_enabletracking");
		set => SetValue("adx_enabletracking", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public bool? adx_excludefromsearch 
	{
		get => GetValue<bool?>("adx_excludefromsearch");
		set => SetValue("adx_excludefromsearch", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? _adx_subjectid_value 
	{
		get => GetValue<Guid?>("_adx_subjectid_value");
		set => SetValue("_adx_subjectid_value", value);
	}
	// IsEnumType: False
    public string? adx_partialurl 
	{
		get => GetValue<string?>("adx_partialurl");
		set => SetValue("adx_partialurl", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public Guid? adx_webfileid 
	{
		get => GetValue<Guid?>("adx_webfileid");
		set => SetValue("adx_webfileid", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _adx_websiteid_value 
	{
		get => GetValue<Guid?>("_adx_websiteid_value");
		set => SetValue("_adx_websiteid_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? adx_title 
	{
		get => GetValue<string?>("adx_title");
		set => SetValue("adx_title", value);
	}
	// IsEnumType: False
    public string? adx_summary 
	{
		get => GetValue<string?>("adx_summary");
		set => SetValue("adx_summary", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? adx_webfile_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("adx_webfile_SyncErrors");
		set => SetValue("adx_webfile_SyncErrors", value);
	}
    public List<asyncoperationInput>? adx_webfile_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("adx_webfile_AsyncOperations");
		set => SetValue("adx_webfile_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? adx_webfile_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("adx_webfile_MailboxTrackingFolders");
		set => SetValue("adx_webfile_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? adx_webfile_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("adx_webfile_ProcessSession");
		set => SetValue("adx_webfile_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? adx_webfile_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("adx_webfile_BulkDeleteFailures");
		set => SetValue("adx_webfile_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? adx_webfile_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("adx_webfile_PrincipalObjectAttributeAccesses");
		set => SetValue("adx_webfile_PrincipalObjectAttributeAccesses", value);
	}
    public List<annotationInput>? adx_webfile_Annotations 
	{
		get => GetValue<List<annotationInput>?>("adx_webfile_Annotations");
		set => SetValue("adx_webfile_Annotations", value);
	}
    public subjectInput? adx_subjectid 
	{
		get => GetValue<subjectInput?>("adx_subjectid");
		set => SetValue("adx_subjectid", value);
	}
    public adx_webpageInput? adx_parentpageid 
	{
		get => GetValue<adx_webpageInput?>("adx_parentpageid");
		set => SetValue("adx_parentpageid", value);
	}
    public adx_websiteInput? adx_websiteid 
	{
		get => GetValue<adx_websiteInput?>("adx_websiteid");
		set => SetValue("adx_websiteid", value);
	}
    public adx_publishingstateInput? adx_publishingstateid 
	{
		get => GetValue<adx_publishingstateInput?>("adx_publishingstateid");
		set => SetValue("adx_publishingstateid", value);
	}
    public List<adx_adInput>? adx_redirectwebfile_ad 
	{
		get => GetValue<List<adx_adInput>?>("adx_redirectwebfile_ad");
		set => SetValue("adx_redirectwebfile_ad", value);
	}
    public List<adx_adInput>? adx_webfile_ad 
	{
		get => GetValue<List<adx_adInput>?>("adx_webfile_ad");
		set => SetValue("adx_webfile_ad", value);
	}
    public adx_webfileInput? adx_masterwebfileid 
	{
		get => GetValue<adx_webfileInput?>("adx_masterwebfileid");
		set => SetValue("adx_masterwebfileid", value);
	}
    public List<adx_webfileInput>? adx_webfile_masterwebfile 
	{
		get => GetValue<List<adx_webfileInput>?>("adx_webfile_masterwebfile");
		set => SetValue("adx_webfile_masterwebfile", value);
	}
    public List<adx_shortcutInput>? adx_webfile_shortcut 
	{
		get => GetValue<List<adx_shortcutInput>?>("adx_webfile_shortcut");
		set => SetValue("adx_webfile_shortcut", value);
	}
    public List<adx_urlhistoryInput>? adx_webfile_urlhistory 
	{
		get => GetValue<List<adx_urlhistoryInput>?>("adx_webfile_urlhistory");
		set => SetValue("adx_webfile_urlhistory", value);
	}
    public List<adx_webfilelogInput>? adx_webfile_webfilelog 
	{
		get => GetValue<List<adx_webfilelogInput>?>("adx_webfile_webfilelog");
		set => SetValue("adx_webfile_webfilelog", value);
	}
    public List<adx_webpageInput>? adx_webfile_webpage_image 
	{
		get => GetValue<List<adx_webpageInput>?>("adx_webfile_webpage_image");
		set => SetValue("adx_webfile_webpage_image", value);
	}
    public List<fileattachmentInput>? adx_webfile_FileAttachments 
	{
		get => GetValue<List<fileattachmentInput>?>("adx_webfile_FileAttachments");
		set => SetValue("adx_webfile_FileAttachments", value);
	}

}
