// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: adx_communityforumalert
/// </summary>
public partial class adx_communityforumalertInput : ODataInputBase
{
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _adx_threadid_value 
	{
		get => GetValue<Guid?>("_adx_threadid_value");
		set => SetValue("_adx_threadid_value", value);
	}
	// IsEnumType: False
    public Guid? _adx_subscriberid_value 
	{
		get => GetValue<Guid?>("_adx_subscriberid_value");
		set => SetValue("_adx_subscriberid_value", value);
	}
	// IsEnumType: False
    public Guid? adx_communityforumalertid 
	{
		get => GetValue<Guid?>("adx_communityforumalertid");
		set => SetValue("adx_communityforumalertid", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? adx_name 
	{
		get => GetValue<string?>("adx_name");
		set => SetValue("adx_name", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public int? msft_datastate 
	{
		get => GetValue<int?>("msft_datastate");
		set => SetValue("msft_datastate", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? adx_expirationdate 
	{
		get => GetValue<DateTimeOffset?>("adx_expirationdate");
		set => SetValue("adx_expirationdate", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<activitypointerInput>? adx_communityforumalert_ActivityPointers 
	{
		get => GetValue<List<activitypointerInput>?>("adx_communityforumalert_ActivityPointers");
		set => SetValue("adx_communityforumalert_ActivityPointers", value);
	}
    public List<li_inmailInput>? adx_communityforumalert_li_inmails 
	{
		get => GetValue<List<li_inmailInput>?>("adx_communityforumalert_li_inmails");
		set => SetValue("adx_communityforumalert_li_inmails", value);
	}
    public List<adx_alertsubscriptionInput>? adx_communityforumalert_adx_alertsubscriptions 
	{
		get => GetValue<List<adx_alertsubscriptionInput>?>("adx_communityforumalert_adx_alertsubscriptions");
		set => SetValue("adx_communityforumalert_adx_alertsubscriptions", value);
	}
    public List<msfp_surveyinviteInput>? adx_communityforumalert_msfp_surveyinvites 
	{
		get => GetValue<List<msfp_surveyinviteInput>?>("adx_communityforumalert_msfp_surveyinvites");
		set => SetValue("adx_communityforumalert_msfp_surveyinvites", value);
	}
    public List<li_messageInput>? adx_communityforumalert_li_messages 
	{
		get => GetValue<List<li_messageInput>?>("adx_communityforumalert_li_messages");
		set => SetValue("adx_communityforumalert_li_messages", value);
	}
    public List<msfp_alertInput>? adx_communityforumalert_msfp_alerts 
	{
		get => GetValue<List<msfp_alertInput>?>("adx_communityforumalert_msfp_alerts");
		set => SetValue("adx_communityforumalert_msfp_alerts", value);
	}
    public List<msdyn_bookingalertInput>? adx_communityforumalert_msdyn_bookingalerts 
	{
		get => GetValue<List<msdyn_bookingalertInput>?>("adx_communityforumalert_msdyn_bookingalerts");
		set => SetValue("adx_communityforumalert_msdyn_bookingalerts", value);
	}
    public List<li_pointdrivepresentationviewedInput>? adx_communityforumalert_li_pointdrivepresentationvieweds 
	{
		get => GetValue<List<li_pointdrivepresentationviewedInput>?>("adx_communityforumalert_li_pointdrivepresentationvieweds");
		set => SetValue("adx_communityforumalert_li_pointdrivepresentationvieweds", value);
	}
    public List<zync_logInput>? adx_communityforumalert_zync_logs 
	{
		get => GetValue<List<zync_logInput>?>("adx_communityforumalert_zync_logs");
		set => SetValue("adx_communityforumalert_zync_logs", value);
	}
    public List<adx_inviteredemptionInput>? adx_communityforumalert_adx_inviteredemptions 
	{
		get => GetValue<List<adx_inviteredemptionInput>?>("adx_communityforumalert_adx_inviteredemptions");
		set => SetValue("adx_communityforumalert_adx_inviteredemptions", value);
	}
    public List<msfp_surveyresponseInput>? adx_communityforumalert_msfp_surveyresponses 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("adx_communityforumalert_msfp_surveyresponses");
		set => SetValue("adx_communityforumalert_msfp_surveyresponses", value);
	}
    public List<syncerrorInput>? adx_communityforumalert_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("adx_communityforumalert_SyncErrors");
		set => SetValue("adx_communityforumalert_SyncErrors", value);
	}
    public List<duplicaterecordInput>? adx_communityforumalert_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("adx_communityforumalert_DuplicateMatchingRecord");
		set => SetValue("adx_communityforumalert_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? adx_communityforumalert_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("adx_communityforumalert_DuplicateBaseRecord");
		set => SetValue("adx_communityforumalert_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? adx_communityforumalert_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("adx_communityforumalert_AsyncOperations");
		set => SetValue("adx_communityforumalert_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? adx_communityforumalert_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("adx_communityforumalert_MailboxTrackingFolders");
		set => SetValue("adx_communityforumalert_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? adx_communityforumalert_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("adx_communityforumalert_ProcessSession");
		set => SetValue("adx_communityforumalert_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? adx_communityforumalert_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("adx_communityforumalert_BulkDeleteFailures");
		set => SetValue("adx_communityforumalert_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? adx_communityforumalert_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("adx_communityforumalert_PrincipalObjectAttributeAccesses");
		set => SetValue("adx_communityforumalert_PrincipalObjectAttributeAccesses", value);
	}
    public List<appointmentInput>? adx_communityforumalert_Appointments 
	{
		get => GetValue<List<appointmentInput>?>("adx_communityforumalert_Appointments");
		set => SetValue("adx_communityforumalert_Appointments", value);
	}
    public List<emailInput>? adx_communityforumalert_Emails 
	{
		get => GetValue<List<emailInput>?>("adx_communityforumalert_Emails");
		set => SetValue("adx_communityforumalert_Emails", value);
	}
    public List<faxInput>? adx_communityforumalert_Faxes 
	{
		get => GetValue<List<faxInput>?>("adx_communityforumalert_Faxes");
		set => SetValue("adx_communityforumalert_Faxes", value);
	}
    public List<letterInput>? adx_communityforumalert_Letters 
	{
		get => GetValue<List<letterInput>?>("adx_communityforumalert_Letters");
		set => SetValue("adx_communityforumalert_Letters", value);
	}
    public List<phonecallInput>? adx_communityforumalert_PhoneCalls 
	{
		get => GetValue<List<phonecallInput>?>("adx_communityforumalert_PhoneCalls");
		set => SetValue("adx_communityforumalert_PhoneCalls", value);
	}
    public List<taskInput>? adx_communityforumalert_Tasks 
	{
		get => GetValue<List<taskInput>?>("adx_communityforumalert_Tasks");
		set => SetValue("adx_communityforumalert_Tasks", value);
	}
    public List<recurringappointmentmasterInput>? adx_communityforumalert_RecurringAppointmentMasters 
	{
		get => GetValue<List<recurringappointmentmasterInput>?>("adx_communityforumalert_RecurringAppointmentMasters");
		set => SetValue("adx_communityforumalert_RecurringAppointmentMasters", value);
	}
    public List<socialactivityInput>? adx_communityforumalert_SocialActivities 
	{
		get => GetValue<List<socialactivityInput>?>("adx_communityforumalert_SocialActivities");
		set => SetValue("adx_communityforumalert_SocialActivities", value);
	}
    public List<serviceappointmentInput>? adx_communityforumalert_ServiceAppointments 
	{
		get => GetValue<List<serviceappointmentInput>?>("adx_communityforumalert_ServiceAppointments");
		set => SetValue("adx_communityforumalert_ServiceAppointments", value);
	}
    public adx_communityforumthreadInput? adx_threadid 
	{
		get => GetValue<adx_communityforumthreadInput?>("adx_threadid");
		set => SetValue("adx_threadid", value);
	}
    public contactInput? adx_subscriberid 
	{
		get => GetValue<contactInput?>("adx_subscriberid");
		set => SetValue("adx_subscriberid", value);
	}
    public List<adx_portalcommentInput>? adx_communityforumalert_adx_portalcomments 
	{
		get => GetValue<List<adx_portalcommentInput>?>("adx_communityforumalert_adx_portalcomments");
		set => SetValue("adx_communityforumalert_adx_portalcomments", value);
	}
    public List<chatInput>? adx_communityforumalert_chats 
	{
		get => GetValue<List<chatInput>?>("adx_communityforumalert_chats");
		set => SetValue("adx_communityforumalert_chats", value);
	}
    public List<msdyn_ocliveworkitemInput>? adx_communityforumalert_msdyn_ocliveworkitems 
	{
		get => GetValue<List<msdyn_ocliveworkitemInput>?>("adx_communityforumalert_msdyn_ocliveworkitems");
		set => SetValue("adx_communityforumalert_msdyn_ocliveworkitems", value);
	}
    public List<msdyn_ocsessionInput>? adx_communityforumalert_msdyn_ocsessions 
	{
		get => GetValue<List<msdyn_ocsessionInput>?>("adx_communityforumalert_msdyn_ocsessions");
		set => SetValue("adx_communityforumalert_msdyn_ocsessions", value);
	}
    public List<msdyn_copilottranscriptInput>? adx_communityforumalert_msdyn_copilottranscripts 
	{
		get => GetValue<List<msdyn_copilottranscriptInput>?>("adx_communityforumalert_msdyn_copilottranscripts");
		set => SetValue("adx_communityforumalert_msdyn_copilottranscripts", value);
	}
    public List<zync_customerassetnoteInput>? adx_communityforumalert_zync_customerassetnotes 
	{
		get => GetValue<List<zync_customerassetnoteInput>?>("adx_communityforumalert_zync_customerassetnotes");
		set => SetValue("adx_communityforumalert_zync_customerassetnotes", value);
	}

}
