// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: competitorproduct
/// </summary>
public partial class competitorproductInput : ODataInputBase
{
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public Guid? productid 
	{
		get => GetValue<Guid?>("productid");
		set => SetValue("productid", value);
	}
	// IsEnumType: False
    public Guid? competitorid 
	{
		get => GetValue<Guid?>("competitorid");
		set => SetValue("competitorid", value);
	}
	// IsEnumType: False
    public Guid? competitorproductid 
	{
		get => GetValue<Guid?>("competitorproductid");
		set => SetValue("competitorproductid", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}

    //Navigations
    public List<asyncoperationInput>? competitorproduct_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("competitorproduct_AsyncOperations");
		set => SetValue("competitorproduct_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? competitorproduct_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("competitorproduct_MailboxTrackingFolders");
		set => SetValue("competitorproduct_MailboxTrackingFolders", value);
	}
    public List<bulkdeletefailureInput>? competitorproduct_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("competitorproduct_BulkDeleteFailures");
		set => SetValue("competitorproduct_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? competitorproduct_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("competitorproduct_PrincipalObjectAttributeAccesses");
		set => SetValue("competitorproduct_PrincipalObjectAttributeAccesses", value);
	}

}
