// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: customeraddress
/// </summary>
public partial class customeraddressInput : ODataInputBase
{
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public Guid? customeraddressid 
	{
		get => GetValue<Guid?>("customeraddressid");
		set => SetValue("customeraddressid", value);
	}
	// IsEnumType: False
    public string? postalcode 
	{
		get => GetValue<string?>("postalcode");
		set => SetValue("postalcode", value);
	}
	// IsEnumType: False
    public int? addressnumber 
	{
		get => GetValue<int?>("addressnumber");
		set => SetValue("addressnumber", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public int? shippingmethodcode 
	{
		get => GetValue<int?>("shippingmethodcode");
		set => SetValue("shippingmethodcode", value);
	}
	// IsEnumType: False
    public string? upszone 
	{
		get => GetValue<string?>("upszone");
		set => SetValue("upszone", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? telephone3 
	{
		get => GetValue<string?>("telephone3");
		set => SetValue("telephone3", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? stateorprovince 
	{
		get => GetValue<string?>("stateorprovince");
		set => SetValue("stateorprovince", value);
	}
	// IsEnumType: False
    public int? zync_country 
	{
		get => GetValue<int?>("zync_country");
		set => SetValue("zync_country", value);
	}
	// IsEnumType: False
    public string? fax 
	{
		get => GetValue<string?>("fax");
		set => SetValue("fax", value);
	}
	// IsEnumType: False
    public Guid? _parentid_value 
	{
		get => GetValue<Guid?>("_parentid_value");
		set => SetValue("_parentid_value", value);
	}
	// IsEnumType: False
    public string? country 
	{
		get => GetValue<string?>("country");
		set => SetValue("country", value);
	}
	// IsEnumType: False
    public string? line1 
	{
		get => GetValue<string?>("line1");
		set => SetValue("line1", value);
	}
	// IsEnumType: False
    public double? latitude 
	{
		get => GetValue<double?>("latitude");
		set => SetValue("latitude", value);
	}
	// IsEnumType: False
    public decimal? exchangerate 
	{
		get => GetValue<decimal?>("exchangerate");
		set => SetValue("exchangerate", value);
	}
	// IsEnumType: False
    public string? line3 
	{
		get => GetValue<string?>("line3");
		set => SetValue("line3", value);
	}
	// IsEnumType: False
    public string? county 
	{
		get => GetValue<string?>("county");
		set => SetValue("county", value);
	}
	// IsEnumType: False
    public int? msft_datastate 
	{
		get => GetValue<int?>("msft_datastate");
		set => SetValue("msft_datastate", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public string? primarycontactname 
	{
		get => GetValue<string?>("primarycontactname");
		set => SetValue("primarycontactname", value);
	}
	// IsEnumType: False
    public string? telephone1 
	{
		get => GetValue<string?>("telephone1");
		set => SetValue("telephone1", value);
	}
	// IsEnumType: False
    public double? longitude 
	{
		get => GetValue<double?>("longitude");
		set => SetValue("longitude", value);
	}
	// IsEnumType: False
    public string? composite 
	{
		get => GetValue<string?>("composite");
		set => SetValue("composite", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public string? postofficebox 
	{
		get => GetValue<string?>("postofficebox");
		set => SetValue("postofficebox", value);
	}
	// IsEnumType: False
    public string? line2 
	{
		get => GetValue<string?>("line2");
		set => SetValue("line2", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? utcoffset 
	{
		get => GetValue<int?>("utcoffset");
		set => SetValue("utcoffset", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public string? city 
	{
		get => GetValue<string?>("city");
		set => SetValue("city", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public int? freighttermscode 
	{
		get => GetValue<int?>("freighttermscode");
		set => SetValue("freighttermscode", value);
	}
	// IsEnumType: False
    public Guid? _transactioncurrencyid_value 
	{
		get => GetValue<Guid?>("_transactioncurrencyid_value");
		set => SetValue("_transactioncurrencyid_value", value);
	}
	// IsEnumType: False
    public string? objecttypecode 
	{
		get => GetValue<string?>("objecttypecode");
		set => SetValue("objecttypecode", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public int? addresstypecode 
	{
		get => GetValue<int?>("addresstypecode");
		set => SetValue("addresstypecode", value);
	}
	// IsEnumType: False
    public string? telephone2 
	{
		get => GetValue<string?>("telephone2");
		set => SetValue("telephone2", value);
	}

    //Navigations
    public List<bulkdeletefailureInput>? CustomerAddress_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("CustomerAddress_BulkDeleteFailures");
		set => SetValue("CustomerAddress_BulkDeleteFailures", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public transactioncurrencyInput? transactioncurrencyid 
	{
		get => GetValue<transactioncurrencyInput?>("transactioncurrencyid");
		set => SetValue("transactioncurrencyid", value);
	}
    public List<processsessionInput>? CustomerAddress_ProcessSessions 
	{
		get => GetValue<List<processsessionInput>?>("CustomerAddress_ProcessSessions");
		set => SetValue("CustomerAddress_ProcessSessions", value);
	}
    public accountInput? parentid_account 
	{
		get => GetValue<accountInput?>("parentid_account");
		set => SetValue("parentid_account", value);
	}
    public contactInput? parentid_contact 
	{
		get => GetValue<contactInput?>("parentid_contact");
		set => SetValue("parentid_contact", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public List<syncerrorInput>? CustomerAddress_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("CustomerAddress_SyncErrors");
		set => SetValue("CustomerAddress_SyncErrors", value);
	}
    public List<principalobjectattributeaccessInput>? customeraddress_principalobjectattributeaccess 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("customeraddress_principalobjectattributeaccess");
		set => SetValue("customeraddress_principalobjectattributeaccess", value);
	}
    public List<asyncoperationInput>? CustomerAddress_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("CustomerAddress_AsyncOperations");
		set => SetValue("CustomerAddress_AsyncOperations", value);
	}
    public List<contractInput>? customer_address_contracts_as_billing_address 
	{
		get => GetValue<List<contractInput>?>("customer_address_contracts_as_billing_address");
		set => SetValue("customer_address_contracts_as_billing_address", value);
	}
    public List<contractInput>? customer_address_contracts_as_service_address 
	{
		get => GetValue<List<contractInput>?>("customer_address_contracts_as_service_address");
		set => SetValue("customer_address_contracts_as_service_address", value);
	}
    public List<contractdetailInput>? customer_address_contract_line_items 
	{
		get => GetValue<List<contractdetailInput>?>("customer_address_contract_line_items");
		set => SetValue("customer_address_contract_line_items", value);
	}

}
