// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: dependency
/// </summary>
public partial class dependencyInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? requiredcomponentobjectid 
	{
		get => GetValue<Guid?>("requiredcomponentobjectid");
		set => SetValue("requiredcomponentobjectid", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? requiredcomponentparentid 
	{
		get => GetValue<Guid?>("requiredcomponentparentid");
		set => SetValue("requiredcomponentparentid", value);
	}
	// IsEnumType: False
    public Guid? dependentcomponentbasesolutionid 
	{
		get => GetValue<Guid?>("dependentcomponentbasesolutionid");
		set => SetValue("dependentcomponentbasesolutionid", value);
	}
	// IsEnumType: False
    public int? dependentcomponenttype 
	{
		get => GetValue<int?>("dependentcomponenttype");
		set => SetValue("dependentcomponenttype", value);
	}
	// IsEnumType: False
    public Guid? dependencyid 
	{
		get => GetValue<Guid?>("dependencyid");
		set => SetValue("dependencyid", value);
	}
	// IsEnumType: False
    public Guid? dependentcomponentparentid 
	{
		get => GetValue<Guid?>("dependentcomponentparentid");
		set => SetValue("dependentcomponentparentid", value);
	}
	// IsEnumType: False
    public Guid? _requiredcomponentnodeid_value 
	{
		get => GetValue<Guid?>("_requiredcomponentnodeid_value");
		set => SetValue("_requiredcomponentnodeid_value", value);
	}
	// IsEnumType: False
    public double? requiredcomponentintroducedversion 
	{
		get => GetValue<double?>("requiredcomponentintroducedversion");
		set => SetValue("requiredcomponentintroducedversion", value);
	}
	// IsEnumType: False
    public int? requiredcomponenttype 
	{
		get => GetValue<int?>("requiredcomponenttype");
		set => SetValue("requiredcomponenttype", value);
	}
	// IsEnumType: False
    public Guid? requiredcomponentbasesolutionid 
	{
		get => GetValue<Guid?>("requiredcomponentbasesolutionid");
		set => SetValue("requiredcomponentbasesolutionid", value);
	}
	// IsEnumType: False
    public int? dependencytype 
	{
		get => GetValue<int?>("dependencytype");
		set => SetValue("dependencytype", value);
	}
	// IsEnumType: False
    public Guid? dependentcomponentobjectid 
	{
		get => GetValue<Guid?>("dependentcomponentobjectid");
		set => SetValue("dependentcomponentobjectid", value);
	}
	// IsEnumType: False
    public Guid? _dependentcomponentnodeid_value 
	{
		get => GetValue<Guid?>("_dependentcomponentnodeid_value");
		set => SetValue("_dependentcomponentnodeid_value", value);
	}

    //Navigations

}
