// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: gitconfigurationretrievaldatasource
/// </summary>
public partial class gitconfigurationretrievaldatasourceInput : ODataInputBase
{
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public Guid? gitconfigurationretrievaldatasourceid 
	{
		get => GetValue<Guid?>("gitconfigurationretrievaldatasourceid");
		set => SetValue("gitconfigurationretrievaldatasourceid", value);
	}

    //Navigations

}
