// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: invoice
/// </summary>
public partial class invoiceInput : ODataInputBase
{
	// IsEnumType: False
    public decimal? totalamount 
	{
		get => GetValue<decimal?>("totalamount");
		set => SetValue("totalamount", value);
	}
	// IsEnumType: False
    public decimal? totallineitemamount_base 
	{
		get => GetValue<decimal?>("totallineitemamount_base");
		set => SetValue("totallineitemamount_base", value);
	}
	// IsEnumType: False
    public int? skippricecalculation 
	{
		get => GetValue<int?>("skippricecalculation");
		set => SetValue("skippricecalculation", value);
	}
	// IsEnumType: False
    public Guid? _contactid_value 
	{
		get => GetValue<Guid?>("_contactid_value");
		set => SetValue("_contactid_value", value);
	}
	// IsEnumType: False
    public Guid? _slainvokedid_value 
	{
		get => GetValue<Guid?>("_slainvokedid_value");
		set => SetValue("_slainvokedid_value", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? _transactioncurrencyid_value 
	{
		get => GetValue<Guid?>("_transactioncurrencyid_value");
		set => SetValue("_transactioncurrencyid_value", value);
	}
	// IsEnumType: False
    public string? entityimage_url 
	{
		get => GetValue<string?>("entityimage_url");
		set => SetValue("entityimage_url", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public int? onholdtime 
	{
		get => GetValue<int?>("onholdtime");
		set => SetValue("onholdtime", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_invoicedate 
	{
		get => GetValue<DateTimeOffset?>("msdyn_invoicedate");
		set => SetValue("msdyn_invoicedate", value);
	}
	// IsEnumType: False
    public bool? ispricelocked 
	{
		get => GetValue<bool?>("ispricelocked");
		set => SetValue("ispricelocked", value);
	}
	// IsEnumType: False
    public decimal? totalamountlessfreight_base 
	{
		get => GetValue<decimal?>("totalamountlessfreight_base");
		set => SetValue("totalamountlessfreight_base", value);
	}
	// IsEnumType: False
    public int? pricingerrorcode 
	{
		get => GetValue<int?>("pricingerrorcode");
		set => SetValue("pricingerrorcode", value);
	}
	// IsEnumType: False
    public decimal? discountpercentage 
	{
		get => GetValue<decimal?>("discountpercentage");
		set => SetValue("discountpercentage", value);
	}
	// IsEnumType: False
    public Guid? processid 
	{
		get => GetValue<Guid?>("processid");
		set => SetValue("processid", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public decimal? freightamount 
	{
		get => GetValue<decimal?>("freightamount");
		set => SetValue("freightamount", value);
	}
	// IsEnumType: False
    public string? shipto_postalcode 
	{
		get => GetValue<string?>("shipto_postalcode");
		set => SetValue("shipto_postalcode", value);
	}
	// IsEnumType: False
    public string? shipto_line2 
	{
		get => GetValue<string?>("shipto_line2");
		set => SetValue("shipto_line2", value);
	}
	// IsEnumType: False
    public decimal? totallineitemdiscountamount 
	{
		get => GetValue<decimal?>("totallineitemdiscountamount");
		set => SetValue("totallineitemdiscountamount", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? description 
	{
		get => GetValue<string?>("description");
		set => SetValue("description", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public string? shipto_composite 
	{
		get => GetValue<string?>("shipto_composite");
		set => SetValue("shipto_composite", value);
	}
	// IsEnumType: False
    public string? shipto_stateorprovince 
	{
		get => GetValue<string?>("shipto_stateorprovince");
		set => SetValue("shipto_stateorprovince", value);
	}
	// IsEnumType: False
    public string? shipto_line1 
	{
		get => GetValue<string?>("shipto_line1");
		set => SetValue("shipto_line1", value);
	}
	// IsEnumType: False
    public string? billto_stateorprovince 
	{
		get => GetValue<string?>("billto_stateorprovince");
		set => SetValue("billto_stateorprovince", value);
	}
	// IsEnumType: False
    public decimal? discountamount_base 
	{
		get => GetValue<decimal?>("discountamount_base");
		set => SetValue("discountamount_base", value);
	}
	// IsEnumType: False
    public decimal? totalamountlessfreight 
	{
		get => GetValue<decimal?>("totalamountlessfreight");
		set => SetValue("totalamountlessfreight", value);
	}
	// IsEnumType: False
    public string? billto_name 
	{
		get => GetValue<string?>("billto_name");
		set => SetValue("billto_name", value);
	}
	// IsEnumType: False
    public Guid? _opportunityid_value 
	{
		get => GetValue<Guid?>("_opportunityid_value");
		set => SetValue("_opportunityid_value", value);
	}
	// IsEnumType: False
    public decimal? totaldiscountamount_base 
	{
		get => GetValue<decimal?>("totaldiscountamount_base");
		set => SetValue("totaldiscountamount_base", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _accountid_value 
	{
		get => GetValue<Guid?>("_accountid_value");
		set => SetValue("_accountid_value", value);
	}
	// IsEnumType: False
    public string? shipto_telephone 
	{
		get => GetValue<string?>("shipto_telephone");
		set => SetValue("shipto_telephone", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public Guid? _slaid_value 
	{
		get => GetValue<Guid?>("_slaid_value");
		set => SetValue("_slaid_value", value);
	}
	// IsEnumType: False
    public decimal? discountamount 
	{
		get => GetValue<decimal?>("discountamount");
		set => SetValue("discountamount", value);
	}
	// IsEnumType: False
    public decimal? msdyn_amountdue_base 
	{
		get => GetValue<decimal?>("msdyn_amountdue_base");
		set => SetValue("msdyn_amountdue_base", value);
	}
	// IsEnumType: False
    public string? emailaddress 
	{
		get => GetValue<string?>("emailaddress");
		set => SetValue("emailaddress", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? traversedpath 
	{
		get => GetValue<string?>("traversedpath");
		set => SetValue("traversedpath", value);
	}
	// IsEnumType: False
    public int? prioritycode 
	{
		get => GetValue<int?>("prioritycode");
		set => SetValue("prioritycode", value);
	}
	// IsEnumType: False
    public string? billto_composite 
	{
		get => GetValue<string?>("billto_composite");
		set => SetValue("billto_composite", value);
	}
	// IsEnumType: False
    public Guid? _salesorderid_value 
	{
		get => GetValue<Guid?>("_salesorderid_value");
		set => SetValue("_salesorderid_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public decimal? msdyn_amountdue 
	{
		get => GetValue<decimal?>("msdyn_amountdue");
		set => SetValue("msdyn_amountdue", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public string? shipto_city 
	{
		get => GetValue<string?>("shipto_city");
		set => SetValue("shipto_city", value);
	}
	// IsEnumType: False
    public int? shippingmethodcode 
	{
		get => GetValue<int?>("shippingmethodcode");
		set => SetValue("shippingmethodcode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? datedelivered 
	{
		get => GetValue<DateTimeOffset?>("datedelivered");
		set => SetValue("datedelivered", value);
	}
	// IsEnumType: False
    public decimal? exchangerate 
	{
		get => GetValue<decimal?>("exchangerate");
		set => SetValue("exchangerate", value);
	}
	// IsEnumType: False
    public Guid? entityimageid 
	{
		get => GetValue<Guid?>("entityimageid");
		set => SetValue("entityimageid", value);
	}
	// IsEnumType: False
    public Guid? _pricelevelid_value 
	{
		get => GetValue<Guid?>("_pricelevelid_value");
		set => SetValue("_pricelevelid_value", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? billto_line3 
	{
		get => GetValue<string?>("billto_line3");
		set => SetValue("billto_line3", value);
	}
	// IsEnumType: False
    public string? billto_line2 
	{
		get => GetValue<string?>("billto_line2");
		set => SetValue("billto_line2", value);
	}
	// IsEnumType: False
    public string? shipto_line3 
	{
		get => GetValue<string?>("shipto_line3");
		set => SetValue("shipto_line3", value);
	}
	// IsEnumType: False
    public decimal? totaldiscountamount 
	{
		get => GetValue<decimal?>("totaldiscountamount");
		set => SetValue("totaldiscountamount", value);
	}
	// IsEnumType: False
    public Guid? stageid 
	{
		get => GetValue<Guid?>("stageid");
		set => SetValue("stageid", value);
	}
	// IsEnumType: False
    public string? billto_line1 
	{
		get => GetValue<string?>("billto_line1");
		set => SetValue("billto_line1", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? paymenttermscode 
	{
		get => GetValue<int?>("paymenttermscode");
		set => SetValue("paymenttermscode", value);
	}
	// IsEnumType: False
    public long? entityimage_timestamp 
	{
		get => GetValue<long?>("entityimage_timestamp");
		set => SetValue("entityimage_timestamp", value);
	}
	// IsEnumType: False
    public DateTimeOffset? lastonholdtime 
	{
		get => GetValue<DateTimeOffset?>("lastonholdtime");
		set => SetValue("lastonholdtime", value);
	}
	// IsEnumType: False
    public string? shipto_name 
	{
		get => GetValue<string?>("shipto_name");
		set => SetValue("shipto_name", value);
	}
	// IsEnumType: False
    public bool? willcall 
	{
		get => GetValue<bool?>("willcall");
		set => SetValue("willcall", value);
	}
	// IsEnumType: False
    public string? invoicenumber 
	{
		get => GetValue<string?>("invoicenumber");
		set => SetValue("invoicenumber", value);
	}
	// IsEnumType: False
    public string? billto_fax 
	{
		get => GetValue<string?>("billto_fax");
		set => SetValue("billto_fax", value);
	}
	// IsEnumType: False
    public string? billto_city 
	{
		get => GetValue<string?>("billto_city");
		set => SetValue("billto_city", value);
	}
	// IsEnumType: False
    public string? shipto_country 
	{
		get => GetValue<string?>("shipto_country");
		set => SetValue("shipto_country", value);
	}
	// IsEnumType: False
    public Guid? invoiceid 
	{
		get => GetValue<Guid?>("invoiceid");
		set => SetValue("invoiceid", value);
	}
	// IsEnumType: False
    public decimal? totallineitemamount 
	{
		get => GetValue<decimal?>("totallineitemamount");
		set => SetValue("totallineitemamount", value);
	}
	// IsEnumType: False
    public string? billto_country 
	{
		get => GetValue<string?>("billto_country");
		set => SetValue("billto_country", value);
	}
	// IsEnumType: False
    public string? shipto_fax 
	{
		get => GetValue<string?>("shipto_fax");
		set => SetValue("shipto_fax", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public decimal? freightamount_base 
	{
		get => GetValue<decimal?>("freightamount_base");
		set => SetValue("freightamount_base", value);
	}
	// IsEnumType: False
    public string? billto_telephone 
	{
		get => GetValue<string?>("billto_telephone");
		set => SetValue("billto_telephone", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public string? billto_postalcode 
	{
		get => GetValue<string?>("billto_postalcode");
		set => SetValue("billto_postalcode", value);
	}
	// IsEnumType: False
    public byte[]? entityimage 
	{
		get => GetValue<byte[]?>("entityimage");
		set => SetValue("entityimage", value);
	}
	// IsEnumType: False
    public decimal? totaltax_base 
	{
		get => GetValue<decimal?>("totaltax_base");
		set => SetValue("totaltax_base", value);
	}
	// IsEnumType: False
    public DateTimeOffset? lastbackofficesubmit 
	{
		get => GetValue<DateTimeOffset?>("lastbackofficesubmit");
		set => SetValue("lastbackofficesubmit", value);
	}
	// IsEnumType: False
    public int? shipto_freighttermscode 
	{
		get => GetValue<int?>("shipto_freighttermscode");
		set => SetValue("shipto_freighttermscode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? msdyn_ordertype 
	{
		get => GetValue<int?>("msdyn_ordertype");
		set => SetValue("msdyn_ordertype", value);
	}
	// IsEnumType: False
    public Guid? _customerid_value 
	{
		get => GetValue<Guid?>("_customerid_value");
		set => SetValue("_customerid_value", value);
	}
	// IsEnumType: False
    public decimal? totallineitemdiscountamount_base 
	{
		get => GetValue<decimal?>("totallineitemdiscountamount_base");
		set => SetValue("totallineitemdiscountamount_base", value);
	}
	// IsEnumType: False
    public decimal? totaltax 
	{
		get => GetValue<decimal?>("totaltax");
		set => SetValue("totaltax", value);
	}
	// IsEnumType: False
    public decimal? totalamount_base 
	{
		get => GetValue<decimal?>("totalamount_base");
		set => SetValue("totalamount_base", value);
	}
	// IsEnumType: False
    public DateOnly? duedate 
	{
		get => GetValue<DateOnly?>("duedate");
		set => SetValue("duedate", value);
	}

    //Navigations
    public List<zync_logInput>? invoice_zync_logs 
	{
		get => GetValue<List<zync_logInput>?>("invoice_zync_logs");
		set => SetValue("invoice_zync_logs", value);
	}
    public List<msfp_surveyinviteInput>? invoice_msfp_surveyinvites 
	{
		get => GetValue<List<msfp_surveyinviteInput>?>("invoice_msfp_surveyinvites");
		set => SetValue("invoice_msfp_surveyinvites", value);
	}
    public List<msfp_surveyresponseInput>? invoice_msfp_surveyresponses 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("invoice_msfp_surveyresponses");
		set => SetValue("invoice_msfp_surveyresponses", value);
	}
    public List<li_inmailInput>? invoice_li_inmails 
	{
		get => GetValue<List<li_inmailInput>?>("invoice_li_inmails");
		set => SetValue("invoice_li_inmails", value);
	}
    public List<li_messageInput>? invoice_li_messages 
	{
		get => GetValue<List<li_messageInput>?>("invoice_li_messages");
		set => SetValue("invoice_li_messages", value);
	}
    public List<li_pointdrivepresentationviewedInput>? invoice_li_pointdrivepresentationvieweds 
	{
		get => GetValue<List<li_pointdrivepresentationviewedInput>?>("invoice_li_pointdrivepresentationvieweds");
		set => SetValue("invoice_li_pointdrivepresentationvieweds", value);
	}
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? Invoice_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("Invoice_SyncErrors");
		set => SetValue("Invoice_SyncErrors", value);
	}
    public List<mailboxtrackingfolderInput>? Invoice_MailboxTrackingFolder 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("Invoice_MailboxTrackingFolder");
		set => SetValue("Invoice_MailboxTrackingFolder", value);
	}
    public List<appointmentInput>? Invoice_Appointments 
	{
		get => GetValue<List<appointmentInput>?>("Invoice_Appointments");
		set => SetValue("Invoice_Appointments", value);
	}
    public List<emailInput>? Invoice_Emails 
	{
		get => GetValue<List<emailInput>?>("Invoice_Emails");
		set => SetValue("Invoice_Emails", value);
	}
    public List<faxInput>? Invoice_Faxes 
	{
		get => GetValue<List<faxInput>?>("Invoice_Faxes");
		set => SetValue("Invoice_Faxes", value);
	}
    public List<letterInput>? Invoice_Letters 
	{
		get => GetValue<List<letterInput>?>("Invoice_Letters");
		set => SetValue("Invoice_Letters", value);
	}
    public List<phonecallInput>? Invoice_Phonecalls 
	{
		get => GetValue<List<phonecallInput>?>("Invoice_Phonecalls");
		set => SetValue("Invoice_Phonecalls", value);
	}
    public List<taskInput>? Invoice_Tasks 
	{
		get => GetValue<List<taskInput>?>("Invoice_Tasks");
		set => SetValue("Invoice_Tasks", value);
	}
    public List<recurringappointmentmasterInput>? Invoice_RecurringAppointmentMasters 
	{
		get => GetValue<List<recurringappointmentmasterInput>?>("Invoice_RecurringAppointmentMasters");
		set => SetValue("Invoice_RecurringAppointmentMasters", value);
	}
    public List<socialactivityInput>? Invoice_SocialActivities 
	{
		get => GetValue<List<socialactivityInput>?>("Invoice_SocialActivities");
		set => SetValue("Invoice_SocialActivities", value);
	}
    public List<connectionInput>? invoice_connections1 
	{
		get => GetValue<List<connectionInput>?>("invoice_connections1");
		set => SetValue("invoice_connections1", value);
	}
    public List<connectionInput>? invoice_connections2 
	{
		get => GetValue<List<connectionInput>?>("invoice_connections2");
		set => SetValue("invoice_connections2", value);
	}
    public List<serviceappointmentInput>? Invoice_ServiceAppointments 
	{
		get => GetValue<List<serviceappointmentInput>?>("Invoice_ServiceAppointments");
		set => SetValue("Invoice_ServiceAppointments", value);
	}
    public accountInput? customerid_account 
	{
		get => GetValue<accountInput?>("customerid_account");
		set => SetValue("customerid_account", value);
	}
    public List<contactInput>? contactinvoices_association 
	{
		get => GetValue<List<contactInput>?>("contactinvoices_association");
		set => SetValue("contactinvoices_association", value);
	}
    public contactInput? customerid_contact 
	{
		get => GetValue<contactInput?>("customerid_contact");
		set => SetValue("customerid_contact", value);
	}
    public opportunityInput? opportunityid 
	{
		get => GetValue<opportunityInput?>("opportunityid");
		set => SetValue("opportunityid", value);
	}
    public pricelevelInput? pricelevelid 
	{
		get => GetValue<pricelevelInput?>("pricelevelid");
		set => SetValue("pricelevelid", value);
	}
    public salesorderInput? salesorderid 
	{
		get => GetValue<salesorderInput?>("salesorderid");
		set => SetValue("salesorderid", value);
	}
    public slaInput? slainvokedid_invoice_sla 
	{
		get => GetValue<slaInput?>("slainvokedid_invoice_sla");
		set => SetValue("slainvokedid_invoice_sla", value);
	}
    public slaInput? sla_invoice_sla 
	{
		get => GetValue<slaInput?>("sla_invoice_sla");
		set => SetValue("sla_invoice_sla", value);
	}
    public List<msdyn_playbookinstanceInput>? msdyn_playbookinstance_invoice 
	{
		get => GetValue<List<msdyn_playbookinstanceInput>?>("msdyn_playbookinstance_invoice");
		set => SetValue("msdyn_playbookinstance_invoice", value);
	}
    public List<msfp_alertInput>? invoice_msfp_alerts 
	{
		get => GetValue<List<msfp_alertInput>?>("invoice_msfp_alerts");
		set => SetValue("invoice_msfp_alerts", value);
	}
    public List<msdyn_bookingalertInput>? invoice_msdyn_bookingalerts 
	{
		get => GetValue<List<msdyn_bookingalertInput>?>("invoice_msdyn_bookingalerts");
		set => SetValue("invoice_msdyn_bookingalerts", value);
	}
    public List<msdyn_actualInput>? msdyn_invoice_msdyn_actual_Invoice 
	{
		get => GetValue<List<msdyn_actualInput>?>("msdyn_invoice_msdyn_actual_Invoice");
		set => SetValue("msdyn_invoice_msdyn_actual_Invoice", value);
	}
    public List<msdyn_agreementinvoicedateInput>? msdyn_invoice_msdyn_agreementinvoicedate_Invoice 
	{
		get => GetValue<List<msdyn_agreementinvoicedateInput>?>("msdyn_invoice_msdyn_agreementinvoicedate_Invoice");
		set => SetValue("msdyn_invoice_msdyn_agreementinvoicedate_Invoice", value);
	}
    public List<msdyn_orderinvoicingdateInput>? msdyn_invoice_msdyn_orderinvoicingdate_Invoice 
	{
		get => GetValue<List<msdyn_orderinvoicingdateInput>?>("msdyn_invoice_msdyn_orderinvoicingdate_Invoice");
		set => SetValue("msdyn_invoice_msdyn_orderinvoicingdate_Invoice", value);
	}
    public List<msdyn_orderinvoicingsetupdateInput>? msdyn_invoice_msdyn_orderinvoicingsetupdate_Invoice 
	{
		get => GetValue<List<msdyn_orderinvoicingsetupdateInput>?>("msdyn_invoice_msdyn_orderinvoicingsetupdate_Invoice");
		set => SetValue("msdyn_invoice_msdyn_orderinvoicingsetupdate_Invoice", value);
	}
    public List<msdyn_paymentdetailInput>? msdyn_invoice_msdyn_paymentdetail_Invoice 
	{
		get => GetValue<List<msdyn_paymentdetailInput>?>("msdyn_invoice_msdyn_paymentdetail_Invoice");
		set => SetValue("msdyn_invoice_msdyn_paymentdetail_Invoice", value);
	}
    public List<adx_alertsubscriptionInput>? invoice_adx_alertsubscriptions 
	{
		get => GetValue<List<adx_alertsubscriptionInput>?>("invoice_adx_alertsubscriptions");
		set => SetValue("invoice_adx_alertsubscriptions", value);
	}
    public List<adx_inviteredemptionInput>? invoice_adx_inviteredemptions 
	{
		get => GetValue<List<adx_inviteredemptionInput>?>("invoice_adx_inviteredemptions");
		set => SetValue("invoice_adx_inviteredemptions", value);
	}
    public List<adx_portalcommentInput>? invoice_adx_portalcomments 
	{
		get => GetValue<List<adx_portalcommentInput>?>("invoice_adx_portalcomments");
		set => SetValue("invoice_adx_portalcomments", value);
	}
    public List<chatInput>? invoice_chats 
	{
		get => GetValue<List<chatInput>?>("invoice_chats");
		set => SetValue("invoice_chats", value);
	}
    public List<msdyn_ocliveworkitemInput>? invoice_msdyn_ocliveworkitems 
	{
		get => GetValue<List<msdyn_ocliveworkitemInput>?>("invoice_msdyn_ocliveworkitems");
		set => SetValue("invoice_msdyn_ocliveworkitems", value);
	}
    public List<msdyn_ocsessionInput>? invoice_msdyn_ocsessions 
	{
		get => GetValue<List<msdyn_ocsessionInput>?>("invoice_msdyn_ocsessions");
		set => SetValue("invoice_msdyn_ocsessions", value);
	}
    public List<msdyn_copilottranscriptInput>? invoice_msdyn_copilottranscripts 
	{
		get => GetValue<List<msdyn_copilottranscriptInput>?>("invoice_msdyn_copilottranscripts");
		set => SetValue("invoice_msdyn_copilottranscripts", value);
	}
    public List<activitypartyInput>? invoice_activity_parties 
	{
		get => GetValue<List<activitypartyInput>?>("invoice_activity_parties");
		set => SetValue("invoice_activity_parties", value);
	}
    public List<asyncoperationInput>? Invoice_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("Invoice_AsyncOperations");
		set => SetValue("Invoice_AsyncOperations", value);
	}
    public List<bulkdeletefailureInput>? Invoice_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("Invoice_BulkDeleteFailures");
		set => SetValue("Invoice_BulkDeleteFailures", value);
	}
    public List<invoicedetailInput>? invoice_details 
	{
		get => GetValue<List<invoicedetailInput>?>("invoice_details");
		set => SetValue("invoice_details", value);
	}
    public List<principalobjectattributeaccessInput>? invoice_principalobjectattributeaccess 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("invoice_principalobjectattributeaccess");
		set => SetValue("invoice_principalobjectattributeaccess", value);
	}
    public List<processsessionInput>? Invoice_ProcessSessions 
	{
		get => GetValue<List<processsessionInput>?>("Invoice_ProcessSessions");
		set => SetValue("Invoice_ProcessSessions", value);
	}
    public List<slakpiinstanceInput>? slakpiinstance_invoice 
	{
		get => GetValue<List<slakpiinstanceInput>?>("slakpiinstance_invoice");
		set => SetValue("slakpiinstance_invoice", value);
	}
    public processstageInput? stageid_processstage 
	{
		get => GetValue<processstageInput?>("stageid_processstage");
		set => SetValue("stageid_processstage", value);
	}
    public transactioncurrencyInput? transactioncurrencyid 
	{
		get => GetValue<transactioncurrencyInput?>("transactioncurrencyid");
		set => SetValue("transactioncurrencyid", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public List<activitypointerInput>? Invoice_ActivityPointers 
	{
		get => GetValue<List<activitypointerInput>?>("Invoice_ActivityPointers");
		set => SetValue("Invoice_ActivityPointers", value);
	}
    public List<annotationInput>? Invoice_Annotation 
	{
		get => GetValue<List<annotationInput>?>("Invoice_Annotation");
		set => SetValue("Invoice_Annotation", value);
	}
    public List<zync_customerassetnoteInput>? invoice_zync_customerassetnotes 
	{
		get => GetValue<List<zync_customerassetnoteInput>?>("invoice_zync_customerassetnotes");
		set => SetValue("invoice_zync_customerassetnotes", value);
	}

}
