// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyncrm_columnstyle
/// </summary>
public partial class msdyncrm_columnstyleInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public string? msdyncrm_backgroundpositiony 
	{
		get => GetValue<string?>("msdyncrm_backgroundpositiony");
		set => SetValue("msdyncrm_backgroundpositiony", value);
	}
	// IsEnumType: False
    public string? msdyncrm_bordercolor 
	{
		get => GetValue<string?>("msdyncrm_bordercolor");
		set => SetValue("msdyncrm_bordercolor", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public string? msdyncrm_paddingbottom 
	{
		get => GetValue<string?>("msdyncrm_paddingbottom");
		set => SetValue("msdyncrm_paddingbottom", value);
	}
	// IsEnumType: False
    public string? msdyncrm_paddingright 
	{
		get => GetValue<string?>("msdyncrm_paddingright");
		set => SetValue("msdyncrm_paddingright", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public string? msdyncrm_marginbottom 
	{
		get => GetValue<string?>("msdyncrm_marginbottom");
		set => SetValue("msdyncrm_marginbottom", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public string? msdyncrm_marginleft 
	{
		get => GetValue<string?>("msdyncrm_marginleft");
		set => SetValue("msdyncrm_marginleft", value);
	}
	// IsEnumType: False
    public string? msdyncrm_verticalalign 
	{
		get => GetValue<string?>("msdyncrm_verticalalign");
		set => SetValue("msdyncrm_verticalalign", value);
	}
	// IsEnumType: False
    public int? msdyncrm_backgroundsize 
	{
		get => GetValue<int?>("msdyncrm_backgroundsize");
		set => SetValue("msdyncrm_backgroundsize", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public string? msdyncrm_backgroundpositionx 
	{
		get => GetValue<string?>("msdyncrm_backgroundpositionx");
		set => SetValue("msdyncrm_backgroundpositionx", value);
	}
	// IsEnumType: False
    public string? msdyncrm_paddingtop 
	{
		get => GetValue<string?>("msdyncrm_paddingtop");
		set => SetValue("msdyncrm_paddingtop", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public string? msdyncrm_marginright 
	{
		get => GetValue<string?>("msdyncrm_marginright");
		set => SetValue("msdyncrm_marginright", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public string? msdyncrm_paddingleft 
	{
		get => GetValue<string?>("msdyncrm_paddingleft");
		set => SetValue("msdyncrm_paddingleft", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? msdyncrm_roundedcorners 
	{
		get => GetValue<string?>("msdyncrm_roundedcorners");
		set => SetValue("msdyncrm_roundedcorners", value);
	}
	// IsEnumType: False
    public string? msdyncrm_bordersize 
	{
		get => GetValue<string?>("msdyncrm_bordersize");
		set => SetValue("msdyncrm_bordersize", value);
	}
	// IsEnumType: False
    public bool? msdyncrm_backgroundimage 
	{
		get => GetValue<bool?>("msdyncrm_backgroundimage");
		set => SetValue("msdyncrm_backgroundimage", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public string? msdyncrm_borderstyle 
	{
		get => GetValue<string?>("msdyncrm_borderstyle");
		set => SetValue("msdyncrm_borderstyle", value);
	}
	// IsEnumType: False
    public string? msdyncrm_margintop 
	{
		get => GetValue<string?>("msdyncrm_margintop");
		set => SetValue("msdyncrm_margintop", value);
	}
	// IsEnumType: False
    public string? msdyncrm_backgroundimagefileid 
	{
		get => GetValue<string?>("msdyncrm_backgroundimagefileid");
		set => SetValue("msdyncrm_backgroundimagefileid", value);
	}
	// IsEnumType: False
    public string? msdyncrm_name 
	{
		get => GetValue<string?>("msdyncrm_name");
		set => SetValue("msdyncrm_name", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public string? msdyncrm_image 
	{
		get => GetValue<string?>("msdyncrm_image");
		set => SetValue("msdyncrm_image", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public int? msdyncrm_assetsprovider 
	{
		get => GetValue<int?>("msdyncrm_assetsprovider");
		set => SetValue("msdyncrm_assetsprovider", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? msdyncrm_backgroundcolor 
	{
		get => GetValue<string?>("msdyncrm_backgroundcolor");
		set => SetValue("msdyncrm_backgroundcolor", value);
	}
	// IsEnumType: False
    public Guid? msdyncrm_columnstyleid 
	{
		get => GetValue<Guid?>("msdyncrm_columnstyleid");
		set => SetValue("msdyncrm_columnstyleid", value);
	}
	// IsEnumType: False
    public string? msdyncrm_emailcolorpalette 
	{
		get => GetValue<string?>("msdyncrm_emailcolorpalette");
		set => SetValue("msdyncrm_emailcolorpalette", value);
	}
	// IsEnumType: False
    public string? msdyncrm_alignment 
	{
		get => GetValue<string?>("msdyncrm_alignment");
		set => SetValue("msdyncrm_alignment", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyncrm_columnstyle_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyncrm_columnstyle_SyncErrors");
		set => SetValue("msdyncrm_columnstyle_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyncrm_columnstyle_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyncrm_columnstyle_DuplicateMatchingRecord");
		set => SetValue("msdyncrm_columnstyle_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyncrm_columnstyle_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyncrm_columnstyle_DuplicateBaseRecord");
		set => SetValue("msdyncrm_columnstyle_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyncrm_columnstyle_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyncrm_columnstyle_AsyncOperations");
		set => SetValue("msdyncrm_columnstyle_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyncrm_columnstyle_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyncrm_columnstyle_MailboxTrackingFolders");
		set => SetValue("msdyncrm_columnstyle_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyncrm_columnstyle_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyncrm_columnstyle_ProcessSession");
		set => SetValue("msdyncrm_columnstyle_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyncrm_columnstyle_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyncrm_columnstyle_BulkDeleteFailures");
		set => SetValue("msdyncrm_columnstyle_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyncrm_columnstyle_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyncrm_columnstyle_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyncrm_columnstyle_PrincipalObjectAttributeAccesses", value);
	}

}
