// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_appconfiguration_systemuser
/// </summary>
public partial class msdyn_appconfiguration_systemuserInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? systemuserid 
	{
		get => GetValue<Guid?>("systemuserid");
		set => SetValue("systemuserid", value);
	}
	// IsEnumType: False
    public Guid? msdyn_appconfigurationid 
	{
		get => GetValue<Guid?>("msdyn_appconfigurationid");
		set => SetValue("msdyn_appconfigurationid", value);
	}
	// IsEnumType: False
    public Guid? msdyn_appconfiguration_systemuserid 
	{
		get => GetValue<Guid?>("msdyn_appconfiguration_systemuserid");
		set => SetValue("msdyn_appconfiguration_systemuserid", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}

    //Navigations

}
