// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_bookableresourcebookingquicknote
/// </summary>
public partial class msdyn_bookableresourcebookingquicknoteInput : ODataInputBase
{
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? msdyn_image_url 
	{
		get => GetValue<string?>("msdyn_image_url");
		set => SetValue("msdyn_image_url", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public string? msdyn_text 
	{
		get => GetValue<string?>("msdyn_text");
		set => SetValue("msdyn_text", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_file 
	{
		get => GetValue<byte[]?>("msdyn_file");
		set => SetValue("msdyn_file", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_quicknote_lookup_entity_value 
	{
		get => GetValue<Guid?>("_msdyn_quicknote_lookup_entity_value");
		set => SetValue("_msdyn_quicknote_lookup_entity_value", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? msdyn_order 
	{
		get => GetValue<int?>("msdyn_order");
		set => SetValue("msdyn_order", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public int? msdyn_type 
	{
		get => GetValue<int?>("msdyn_type");
		set => SetValue("msdyn_type", value);
	}
	// IsEnumType: False
    public string? msdyn_file_name 
	{
		get => GetValue<string?>("msdyn_file_name");
		set => SetValue("msdyn_file_name", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public long? msdyn_image_timestamp 
	{
		get => GetValue<long?>("msdyn_image_timestamp");
		set => SetValue("msdyn_image_timestamp", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? msdyn_imageid 
	{
		get => GetValue<Guid?>("msdyn_imageid");
		set => SetValue("msdyn_imageid", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_image 
	{
		get => GetValue<byte[]?>("msdyn_image");
		set => SetValue("msdyn_image", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? msdyn_bookableresourcebookingquicknoteid 
	{
		get => GetValue<Guid?>("msdyn_bookableresourcebookingquicknoteid");
		set => SetValue("msdyn_bookableresourcebookingquicknoteid", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyn_bookableresourcebookingquicknote_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_bookableresourcebookingquicknote_SyncErrors");
		set => SetValue("msdyn_bookableresourcebookingquicknote_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_bookableresourcebookingquicknote_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_bookableresourcebookingquicknote_DuplicateMatchingRecord");
		set => SetValue("msdyn_bookableresourcebookingquicknote_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_bookableresourcebookingquicknote_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_bookableresourcebookingquicknote_DuplicateBaseRecord");
		set => SetValue("msdyn_bookableresourcebookingquicknote_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_bookableresourcebookingquicknote_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_bookableresourcebookingquicknote_AsyncOperations");
		set => SetValue("msdyn_bookableresourcebookingquicknote_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_bookableresourcebookingquicknote_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_bookableresourcebookingquicknote_MailboxTrackingFolders");
		set => SetValue("msdyn_bookableresourcebookingquicknote_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_bookableresourcebookingquicknote_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_bookableresourcebookingquicknote_ProcessSession");
		set => SetValue("msdyn_bookableresourcebookingquicknote_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_bookableresourcebookingquicknote_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_bookableresourcebookingquicknote_BulkDeleteFailures");
		set => SetValue("msdyn_bookableresourcebookingquicknote_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_bookableresourcebookingquicknote_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_bookableresourcebookingquicknote_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_bookableresourcebookingquicknote_PrincipalObjectAttributeAccesses", value);
	}
    public List<fileattachmentInput>? msdyn_bookableresourcebookingquicknote_FileAttachments 
	{
		get => GetValue<List<fileattachmentInput>?>("msdyn_bookableresourcebookingquicknote_FileAttachments");
		set => SetValue("msdyn_bookableresourcebookingquicknote_FileAttachments", value);
	}
    public bookableresourcebookingInput? msdyn_quicknote_lookup_entity 
	{
		get => GetValue<bookableresourcebookingInput?>("msdyn_quicknote_lookup_entity");
		set => SetValue("msdyn_quicknote_lookup_entity", value);
	}

}
