// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_purchaseorderreceipt
/// </summary>
public partial class msdyn_purchaseorderreceiptInput : ODataInputBase
{
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? processid 
	{
		get => GetValue<Guid?>("processid");
		set => SetValue("processid", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? traversedpath 
	{
		get => GetValue<string?>("traversedpath");
		set => SetValue("traversedpath", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_receivedby_value 
	{
		get => GetValue<Guid?>("_msdyn_receivedby_value");
		set => SetValue("_msdyn_receivedby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_datereceived 
	{
		get => GetValue<DateTimeOffset?>("msdyn_datereceived");
		set => SetValue("msdyn_datereceived", value);
	}
	// IsEnumType: False
    public Guid? _stageid_value 
	{
		get => GetValue<Guid?>("_stageid_value");
		set => SetValue("_stageid_value", value);
	}
	// IsEnumType: False
    public bool? zync_finished 
	{
		get => GetValue<bool?>("zync_finished");
		set => SetValue("zync_finished", value);
	}
	// IsEnumType: False
    public string? zync_division 
	{
		get => GetValue<string?>("zync_division");
		set => SetValue("zync_division", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public string? msdyn_note 
	{
		get => GetValue<string?>("msdyn_note");
		set => SetValue("msdyn_note", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public Guid? msdyn_purchaseorderreceiptid 
	{
		get => GetValue<Guid?>("msdyn_purchaseorderreceiptid");
		set => SetValue("msdyn_purchaseorderreceiptid", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_purchaseorder_value 
	{
		get => GetValue<Guid?>("_msdyn_purchaseorder_value");
		set => SetValue("_msdyn_purchaseorder_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_shipvia_value 
	{
		get => GetValue<Guid?>("_msdyn_shipvia_value");
		set => SetValue("_msdyn_shipvia_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<activitypointerInput>? msdyn_purchaseorderreceipt_ActivityPointers 
	{
		get => GetValue<List<activitypointerInput>?>("msdyn_purchaseorderreceipt_ActivityPointers");
		set => SetValue("msdyn_purchaseorderreceipt_ActivityPointers", value);
	}
    public List<li_inmailInput>? msdyn_purchaseorderreceipt_li_inmails 
	{
		get => GetValue<List<li_inmailInput>?>("msdyn_purchaseorderreceipt_li_inmails");
		set => SetValue("msdyn_purchaseorderreceipt_li_inmails", value);
	}
    public List<msfp_surveyinviteInput>? msdyn_purchaseorderreceipt_msfp_surveyinvites 
	{
		get => GetValue<List<msfp_surveyinviteInput>?>("msdyn_purchaseorderreceipt_msfp_surveyinvites");
		set => SetValue("msdyn_purchaseorderreceipt_msfp_surveyinvites", value);
	}
    public List<li_messageInput>? msdyn_purchaseorderreceipt_li_messages 
	{
		get => GetValue<List<li_messageInput>?>("msdyn_purchaseorderreceipt_li_messages");
		set => SetValue("msdyn_purchaseorderreceipt_li_messages", value);
	}
    public List<msfp_alertInput>? msdyn_purchaseorderreceipt_msfp_alerts 
	{
		get => GetValue<List<msfp_alertInput>?>("msdyn_purchaseorderreceipt_msfp_alerts");
		set => SetValue("msdyn_purchaseorderreceipt_msfp_alerts", value);
	}
    public List<msdyn_bookingalertInput>? msdyn_purchaseorderreceipt_msdyn_bookingalerts 
	{
		get => GetValue<List<msdyn_bookingalertInput>?>("msdyn_purchaseorderreceipt_msdyn_bookingalerts");
		set => SetValue("msdyn_purchaseorderreceipt_msdyn_bookingalerts", value);
	}
    public List<li_pointdrivepresentationviewedInput>? msdyn_purchaseorderreceipt_li_pointdrivepresentationvieweds 
	{
		get => GetValue<List<li_pointdrivepresentationviewedInput>?>("msdyn_purchaseorderreceipt_li_pointdrivepresentationvieweds");
		set => SetValue("msdyn_purchaseorderreceipt_li_pointdrivepresentationvieweds", value);
	}
    public List<zync_logInput>? msdyn_purchaseorderreceipt_zync_logs 
	{
		get => GetValue<List<zync_logInput>?>("msdyn_purchaseorderreceipt_zync_logs");
		set => SetValue("msdyn_purchaseorderreceipt_zync_logs", value);
	}
    public List<msfp_surveyresponseInput>? msdyn_purchaseorderreceipt_msfp_surveyresponses 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("msdyn_purchaseorderreceipt_msfp_surveyresponses");
		set => SetValue("msdyn_purchaseorderreceipt_msfp_surveyresponses", value);
	}
    public List<syncerrorInput>? msdyn_purchaseorderreceipt_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_purchaseorderreceipt_SyncErrors");
		set => SetValue("msdyn_purchaseorderreceipt_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_purchaseorderreceipt_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_purchaseorderreceipt_DuplicateMatchingRecord");
		set => SetValue("msdyn_purchaseorderreceipt_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_purchaseorderreceipt_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_purchaseorderreceipt_DuplicateBaseRecord");
		set => SetValue("msdyn_purchaseorderreceipt_DuplicateBaseRecord", value);
	}
    public List<sharepointdocumentlocationInput>? msdyn_purchaseorderreceipt_SharePointDocumentLocations 
	{
		get => GetValue<List<sharepointdocumentlocationInput>?>("msdyn_purchaseorderreceipt_SharePointDocumentLocations");
		set => SetValue("msdyn_purchaseorderreceipt_SharePointDocumentLocations", value);
	}
    public List<asyncoperationInput>? msdyn_purchaseorderreceipt_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_purchaseorderreceipt_AsyncOperations");
		set => SetValue("msdyn_purchaseorderreceipt_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_purchaseorderreceipt_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_purchaseorderreceipt_MailboxTrackingFolders");
		set => SetValue("msdyn_purchaseorderreceipt_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_purchaseorderreceipt_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_purchaseorderreceipt_ProcessSession");
		set => SetValue("msdyn_purchaseorderreceipt_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_purchaseorderreceipt_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_purchaseorderreceipt_BulkDeleteFailures");
		set => SetValue("msdyn_purchaseorderreceipt_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_purchaseorderreceipt_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_purchaseorderreceipt_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_purchaseorderreceipt_PrincipalObjectAttributeAccesses", value);
	}
    public processstageInput? stageid 
	{
		get => GetValue<processstageInput?>("stageid");
		set => SetValue("stageid", value);
	}
    public List<appointmentInput>? msdyn_purchaseorderreceipt_Appointments 
	{
		get => GetValue<List<appointmentInput>?>("msdyn_purchaseorderreceipt_Appointments");
		set => SetValue("msdyn_purchaseorderreceipt_Appointments", value);
	}
    public List<emailInput>? msdyn_purchaseorderreceipt_Emails 
	{
		get => GetValue<List<emailInput>?>("msdyn_purchaseorderreceipt_Emails");
		set => SetValue("msdyn_purchaseorderreceipt_Emails", value);
	}
    public List<faxInput>? msdyn_purchaseorderreceipt_Faxes 
	{
		get => GetValue<List<faxInput>?>("msdyn_purchaseorderreceipt_Faxes");
		set => SetValue("msdyn_purchaseorderreceipt_Faxes", value);
	}
    public List<letterInput>? msdyn_purchaseorderreceipt_Letters 
	{
		get => GetValue<List<letterInput>?>("msdyn_purchaseorderreceipt_Letters");
		set => SetValue("msdyn_purchaseorderreceipt_Letters", value);
	}
    public List<phonecallInput>? msdyn_purchaseorderreceipt_PhoneCalls 
	{
		get => GetValue<List<phonecallInput>?>("msdyn_purchaseorderreceipt_PhoneCalls");
		set => SetValue("msdyn_purchaseorderreceipt_PhoneCalls", value);
	}
    public List<taskInput>? msdyn_purchaseorderreceipt_Tasks 
	{
		get => GetValue<List<taskInput>?>("msdyn_purchaseorderreceipt_Tasks");
		set => SetValue("msdyn_purchaseorderreceipt_Tasks", value);
	}
    public List<recurringappointmentmasterInput>? msdyn_purchaseorderreceipt_RecurringAppointmentMasters 
	{
		get => GetValue<List<recurringappointmentmasterInput>?>("msdyn_purchaseorderreceipt_RecurringAppointmentMasters");
		set => SetValue("msdyn_purchaseorderreceipt_RecurringAppointmentMasters", value);
	}
    public List<socialactivityInput>? msdyn_purchaseorderreceipt_SocialActivities 
	{
		get => GetValue<List<socialactivityInput>?>("msdyn_purchaseorderreceipt_SocialActivities");
		set => SetValue("msdyn_purchaseorderreceipt_SocialActivities", value);
	}
    public List<connectionInput>? msdyn_purchaseorderreceipt_connections1 
	{
		get => GetValue<List<connectionInput>?>("msdyn_purchaseorderreceipt_connections1");
		set => SetValue("msdyn_purchaseorderreceipt_connections1", value);
	}
    public List<connectionInput>? msdyn_purchaseorderreceipt_connections2 
	{
		get => GetValue<List<connectionInput>?>("msdyn_purchaseorderreceipt_connections2");
		set => SetValue("msdyn_purchaseorderreceipt_connections2", value);
	}
    public List<annotationInput>? msdyn_purchaseorderreceipt_Annotations 
	{
		get => GetValue<List<annotationInput>?>("msdyn_purchaseorderreceipt_Annotations");
		set => SetValue("msdyn_purchaseorderreceipt_Annotations", value);
	}
    public List<serviceappointmentInput>? msdyn_purchaseorderreceipt_ServiceAppointments 
	{
		get => GetValue<List<serviceappointmentInput>?>("msdyn_purchaseorderreceipt_ServiceAppointments");
		set => SetValue("msdyn_purchaseorderreceipt_ServiceAppointments", value);
	}
    public msdyn_purchaseorderInput? msdyn_purchaseorder 
	{
		get => GetValue<msdyn_purchaseorderInput?>("msdyn_purchaseorder");
		set => SetValue("msdyn_purchaseorder", value);
	}
    public List<msdyn_purchaseorderreceiptproductInput>? msdyn_msdyn_purchaseorderreceipt_msdyn_purchaseorderreceiptproduct_PurchaseOrderReceipt 
	{
		get => GetValue<List<msdyn_purchaseorderreceiptproductInput>?>("msdyn_msdyn_purchaseorderreceipt_msdyn_purchaseorderreceiptproduct_PurchaseOrderReceipt");
		set => SetValue("msdyn_msdyn_purchaseorderreceipt_msdyn_purchaseorderreceiptproduct_PurchaseOrderReceipt", value);
	}
    public msdyn_shipviaInput? msdyn_shipvia 
	{
		get => GetValue<msdyn_shipviaInput?>("msdyn_shipvia");
		set => SetValue("msdyn_shipvia", value);
	}
    public systemuserInput? msdyn_receivedby 
	{
		get => GetValue<systemuserInput?>("msdyn_receivedby");
		set => SetValue("msdyn_receivedby", value);
	}
    public List<adx_alertsubscriptionInput>? msdyn_purchaseorderreceipt_adx_alertsubscriptions 
	{
		get => GetValue<List<adx_alertsubscriptionInput>?>("msdyn_purchaseorderreceipt_adx_alertsubscriptions");
		set => SetValue("msdyn_purchaseorderreceipt_adx_alertsubscriptions", value);
	}
    public List<adx_inviteredemptionInput>? msdyn_purchaseorderreceipt_adx_inviteredemptions 
	{
		get => GetValue<List<adx_inviteredemptionInput>?>("msdyn_purchaseorderreceipt_adx_inviteredemptions");
		set => SetValue("msdyn_purchaseorderreceipt_adx_inviteredemptions", value);
	}
    public List<adx_portalcommentInput>? msdyn_purchaseorderreceipt_adx_portalcomments 
	{
		get => GetValue<List<adx_portalcommentInput>?>("msdyn_purchaseorderreceipt_adx_portalcomments");
		set => SetValue("msdyn_purchaseorderreceipt_adx_portalcomments", value);
	}
    public List<chatInput>? msdyn_purchaseorderreceipt_chats 
	{
		get => GetValue<List<chatInput>?>("msdyn_purchaseorderreceipt_chats");
		set => SetValue("msdyn_purchaseorderreceipt_chats", value);
	}
    public List<msdyn_ocliveworkitemInput>? msdyn_purchaseorderreceipt_msdyn_ocliveworkitems 
	{
		get => GetValue<List<msdyn_ocliveworkitemInput>?>("msdyn_purchaseorderreceipt_msdyn_ocliveworkitems");
		set => SetValue("msdyn_purchaseorderreceipt_msdyn_ocliveworkitems", value);
	}
    public List<msdyn_ocsessionInput>? msdyn_purchaseorderreceipt_msdyn_ocsessions 
	{
		get => GetValue<List<msdyn_ocsessionInput>?>("msdyn_purchaseorderreceipt_msdyn_ocsessions");
		set => SetValue("msdyn_purchaseorderreceipt_msdyn_ocsessions", value);
	}
    public List<msdyn_copilottranscriptInput>? msdyn_purchaseorderreceipt_msdyn_copilottranscripts 
	{
		get => GetValue<List<msdyn_copilottranscriptInput>?>("msdyn_purchaseorderreceipt_msdyn_copilottranscripts");
		set => SetValue("msdyn_purchaseorderreceipt_msdyn_copilottranscripts", value);
	}
    public List<zync_customerassetnoteInput>? msdyn_purchaseorderreceipt_zync_customerassetnotes 
	{
		get => GetValue<List<zync_customerassetnoteInput>?>("msdyn_purchaseorderreceipt_zync_customerassetnotes");
		set => SetValue("msdyn_purchaseorderreceipt_zync_customerassetnotes", value);
	}
    public List<msdyn_bpf_2c5fe86acc8b414b8322ae571000c799Input>? bpf_msdyn_purchaseorderreceipt_msdyn_bpf_2c5fe86acc8b414b8322ae571000c799 
	{
		get => GetValue<List<msdyn_bpf_2c5fe86acc8b414b8322ae571000c799Input>?>("bpf_msdyn_purchaseorderreceipt_msdyn_bpf_2c5fe86acc8b414b8322ae571000c799");
		set => SetValue("bpf_msdyn_purchaseorderreceipt_msdyn_bpf_2c5fe86acc8b414b8322ae571000c799", value);
	}
    public List<new_bpf_865e91c2b850489694d9b020cb96959fInput>? bpf_msdyn_purchaseorderreceipt_new_bpf_865e91c2b850489694d9b020cb96959f 
	{
		get => GetValue<List<new_bpf_865e91c2b850489694d9b020cb96959fInput>?>("bpf_msdyn_purchaseorderreceipt_new_bpf_865e91c2b850489694d9b020cb96959f");
		set => SetValue("bpf_msdyn_purchaseorderreceipt_new_bpf_865e91c2b850489694d9b020cb96959f", value);
	}
    public List<zync_lotnumber_entityInput>? zync_msdyn_purchaseorderreceipt_zync_lotnumber_entity_PurchaseOrderReceipts_lookup 
	{
		get => GetValue<List<zync_lotnumber_entityInput>?>("zync_msdyn_purchaseorderreceipt_zync_lotnumber_entity_PurchaseOrderReceipts_lookup");
		set => SetValue("zync_msdyn_purchaseorderreceipt_zync_lotnumber_entity_PurchaseOrderReceipts_lookup", value);
	}

}
