// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_actual
/// </summary>
public partial class msdyn_actualInput : ODataInputBase
{
	// IsEnumType: False
    public decimal? msdyn_price_base 
	{
		get => GetValue<decimal?>("msdyn_price_base");
		set => SetValue("msdyn_price_base", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public int? msdyn_transactiontypecode 
	{
		get => GetValue<int?>("msdyn_transactiontypecode");
		set => SetValue("msdyn_transactiontypecode", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_workorder_value 
	{
		get => GetValue<Guid?>("_msdyn_workorder_value");
		set => SetValue("_msdyn_workorder_value", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_workordertype_value 
	{
		get => GetValue<Guid?>("_msdyn_workordertype_value");
		set => SetValue("_msdyn_workordertype_value", value);
	}
	// IsEnumType: False
    public Guid? msdyn_actualid 
	{
		get => GetValue<Guid?>("msdyn_actualid");
		set => SetValue("msdyn_actualid", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? msdyn_amountmethod 
	{
		get => GetValue<int?>("msdyn_amountmethod");
		set => SetValue("msdyn_amountmethod", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_documentdate 
	{
		get => GetValue<DateTimeOffset?>("msdyn_documentdate");
		set => SetValue("msdyn_documentdate", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public decimal? msdyn_basisamount_base 
	{
		get => GetValue<decimal?>("msdyn_basisamount_base");
		set => SetValue("msdyn_basisamount_base", value);
	}
	// IsEnumType: False
    public decimal? msdyn_amount_base 
	{
		get => GetValue<decimal?>("msdyn_amount_base");
		set => SetValue("msdyn_amount_base", value);
	}
	// IsEnumType: False
    public decimal? msdyn_quantity 
	{
		get => GetValue<decimal?>("msdyn_quantity");
		set => SetValue("msdyn_quantity", value);
	}
	// IsEnumType: False
    public Guid? _transactioncurrencyid_value 
	{
		get => GetValue<Guid?>("_transactioncurrencyid_value");
		set => SetValue("_transactioncurrencyid_value", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_warehouse_value 
	{
		get => GetValue<Guid?>("_msdyn_warehouse_value");
		set => SetValue("_msdyn_warehouse_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? msdyn_salescontractline 
	{
		get => GetValue<string?>("msdyn_salescontractline");
		set => SetValue("msdyn_salescontractline", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_incidenttype_value 
	{
		get => GetValue<Guid?>("_msdyn_incidenttype_value");
		set => SetValue("_msdyn_incidenttype_value", value);
	}
	// IsEnumType: False
    public decimal? msdyn_basisprice_base 
	{
		get => GetValue<decimal?>("msdyn_basisprice_base");
		set => SetValue("msdyn_basisprice_base", value);
	}
	// IsEnumType: False
    public int? msdyn_journaltype 
	{
		get => GetValue<int?>("msdyn_journaltype");
		set => SetValue("msdyn_journaltype", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_unitschedule_value 
	{
		get => GetValue<Guid?>("_msdyn_unitschedule_value");
		set => SetValue("_msdyn_unitschedule_value", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public string? msdyn_description 
	{
		get => GetValue<string?>("msdyn_description");
		set => SetValue("msdyn_description", value);
	}
	// IsEnumType: False
    public string? msdyn_externaldescription 
	{
		get => GetValue<string?>("msdyn_externaldescription");
		set => SetValue("msdyn_externaldescription", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_externalreferencedate 
	{
		get => GetValue<DateTimeOffset?>("msdyn_externalreferencedate");
		set => SetValue("msdyn_externalreferencedate", value);
	}
	// IsEnumType: False
    public bool? msdyn_isjournalized 
	{
		get => GetValue<bool?>("msdyn_isjournalized");
		set => SetValue("msdyn_isjournalized", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_startdatetime 
	{
		get => GetValue<DateTimeOffset?>("msdyn_startdatetime");
		set => SetValue("msdyn_startdatetime", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_agreement_value 
	{
		get => GetValue<Guid?>("_msdyn_agreement_value");
		set => SetValue("_msdyn_agreement_value", value);
	}
	// IsEnumType: False
    public decimal? msdyn_price 
	{
		get => GetValue<decimal?>("msdyn_price");
		set => SetValue("msdyn_price", value);
	}
	// IsEnumType: False
    public decimal? msdyn_amount 
	{
		get => GetValue<decimal?>("msdyn_amount");
		set => SetValue("msdyn_amount", value);
	}
	// IsEnumType: False
    public int? msdyn_worklocation 
	{
		get => GetValue<int?>("msdyn_worklocation");
		set => SetValue("msdyn_worklocation", value);
	}
	// IsEnumType: False
    public decimal? msdyn_percent 
	{
		get => GetValue<decimal?>("msdyn_percent");
		set => SetValue("msdyn_percent", value);
	}
	// IsEnumType: False
    public int? msdyn_producttype 
	{
		get => GetValue<int?>("msdyn_producttype");
		set => SetValue("msdyn_producttype", value);
	}
	// IsEnumType: False
    public decimal? exchangerate 
	{
		get => GetValue<decimal?>("exchangerate");
		set => SetValue("exchangerate", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_product_value 
	{
		get => GetValue<Guid?>("_msdyn_product_value");
		set => SetValue("_msdyn_product_value", value);
	}
	// IsEnumType: False
    public int? msdyn_vendortype 
	{
		get => GetValue<int?>("msdyn_vendortype");
		set => SetValue("msdyn_vendortype", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_bookableresource_value 
	{
		get => GetValue<Guid?>("_msdyn_bookableresource_value");
		set => SetValue("_msdyn_bookableresource_value", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_unit_value 
	{
		get => GetValue<Guid?>("_msdyn_unit_value");
		set => SetValue("_msdyn_unit_value", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? msdyn_adjustmentstatus 
	{
		get => GetValue<int?>("msdyn_adjustmentstatus");
		set => SetValue("msdyn_adjustmentstatus", value);
	}
	// IsEnumType: False
    public int? msdyn_billingstatus 
	{
		get => GetValue<int?>("msdyn_billingstatus");
		set => SetValue("msdyn_billingstatus", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_exchangeratedate 
	{
		get => GetValue<DateTimeOffset?>("msdyn_exchangeratedate");
		set => SetValue("msdyn_exchangeratedate", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_accountvendor_value 
	{
		get => GetValue<Guid?>("_msdyn_accountvendor_value");
		set => SetValue("_msdyn_accountvendor_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_accountingdate 
	{
		get => GetValue<DateTimeOffset?>("msdyn_accountingdate");
		set => SetValue("msdyn_accountingdate", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_serviceaccount_value 
	{
		get => GetValue<Guid?>("_msdyn_serviceaccount_value");
		set => SetValue("_msdyn_serviceaccount_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public int? msdyn_customertype 
	{
		get => GetValue<int?>("msdyn_customertype");
		set => SetValue("msdyn_customertype", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_taxcode_value 
	{
		get => GetValue<Guid?>("_msdyn_taxcode_value");
		set => SetValue("_msdyn_taxcode_value", value);
	}
	// IsEnumType: False
    public int? msdyn_billingtype 
	{
		get => GetValue<int?>("msdyn_billingtype");
		set => SetValue("msdyn_billingtype", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_invoice_value 
	{
		get => GetValue<Guid?>("_msdyn_invoice_value");
		set => SetValue("_msdyn_invoice_value", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_pricelist_value 
	{
		get => GetValue<Guid?>("_msdyn_pricelist_value");
		set => SetValue("_msdyn_pricelist_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_accountcustomer_value 
	{
		get => GetValue<Guid?>("_msdyn_accountcustomer_value");
		set => SetValue("_msdyn_accountcustomer_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_enddatetime 
	{
		get => GetValue<DateTimeOffset?>("msdyn_enddatetime");
		set => SetValue("msdyn_enddatetime", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_serviceterritory_value 
	{
		get => GetValue<Guid?>("_msdyn_serviceterritory_value");
		set => SetValue("_msdyn_serviceterritory_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public string? msdyn_externalreferenceid 
	{
		get => GetValue<string?>("msdyn_externalreferenceid");
		set => SetValue("msdyn_externalreferenceid", value);
	}
	// IsEnumType: False
    public decimal? msdyn_basisquantity 
	{
		get => GetValue<decimal?>("msdyn_basisquantity");
		set => SetValue("msdyn_basisquantity", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_contactcustomer_value 
	{
		get => GetValue<Guid?>("_msdyn_contactcustomer_value");
		set => SetValue("_msdyn_contactcustomer_value", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_salescontract_value 
	{
		get => GetValue<Guid?>("_msdyn_salescontract_value");
		set => SetValue("_msdyn_salescontract_value", value);
	}
	// IsEnumType: False
    public int? msdyn_transactionclassification 
	{
		get => GetValue<int?>("msdyn_transactionclassification");
		set => SetValue("msdyn_transactionclassification", value);
	}
	// IsEnumType: False
    public decimal? msdyn_basisprice 
	{
		get => GetValue<decimal?>("msdyn_basisprice");
		set => SetValue("msdyn_basisprice", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public decimal? msdyn_basisamount 
	{
		get => GetValue<decimal?>("msdyn_basisamount");
		set => SetValue("msdyn_basisamount", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_contactvendor_value 
	{
		get => GetValue<Guid?>("_msdyn_contactvendor_value");
		set => SetValue("_msdyn_contactvendor_value", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyn_actual_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_actual_SyncErrors");
		set => SetValue("msdyn_actual_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_actual_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_actual_DuplicateMatchingRecord");
		set => SetValue("msdyn_actual_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_actual_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_actual_DuplicateBaseRecord");
		set => SetValue("msdyn_actual_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_actual_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_actual_AsyncOperations");
		set => SetValue("msdyn_actual_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_actual_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_actual_MailboxTrackingFolders");
		set => SetValue("msdyn_actual_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_actual_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_actual_ProcessSession");
		set => SetValue("msdyn_actual_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_actual_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_actual_BulkDeleteFailures");
		set => SetValue("msdyn_actual_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_actual_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_actual_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_actual_PrincipalObjectAttributeAccesses", value);
	}
    public transactioncurrencyInput? transactioncurrencyid 
	{
		get => GetValue<transactioncurrencyInput?>("transactioncurrencyid");
		set => SetValue("transactioncurrencyid", value);
	}
    public List<annotationInput>? msdyn_actual_Annotations 
	{
		get => GetValue<List<annotationInput>?>("msdyn_actual_Annotations");
		set => SetValue("msdyn_actual_Annotations", value);
	}
    public accountInput? msdyn_AccountCustomer 
	{
		get => GetValue<accountInput?>("msdyn_AccountCustomer");
		set => SetValue("msdyn_AccountCustomer", value);
	}
    public accountInput? msdyn_AccountVendor 
	{
		get => GetValue<accountInput?>("msdyn_AccountVendor");
		set => SetValue("msdyn_AccountVendor", value);
	}
    public bookableresourceInput? msdyn_bookableresource 
	{
		get => GetValue<bookableresourceInput?>("msdyn_bookableresource");
		set => SetValue("msdyn_bookableresource", value);
	}
    public contactInput? msdyn_ContactCustomer 
	{
		get => GetValue<contactInput?>("msdyn_ContactCustomer");
		set => SetValue("msdyn_ContactCustomer", value);
	}
    public contactInput? msdyn_ContactVendor 
	{
		get => GetValue<contactInput?>("msdyn_ContactVendor");
		set => SetValue("msdyn_ContactVendor", value);
	}
    public invoiceInput? msdyn_Invoice 
	{
		get => GetValue<invoiceInput?>("msdyn_Invoice");
		set => SetValue("msdyn_Invoice", value);
	}
    public pricelevelInput? msdyn_PriceList 
	{
		get => GetValue<pricelevelInput?>("msdyn_PriceList");
		set => SetValue("msdyn_PriceList", value);
	}
    public productInput? msdyn_Product 
	{
		get => GetValue<productInput?>("msdyn_Product");
		set => SetValue("msdyn_Product", value);
	}
    public salesorderInput? msdyn_SalesContract 
	{
		get => GetValue<salesorderInput?>("msdyn_SalesContract");
		set => SetValue("msdyn_SalesContract", value);
	}
    public uomInput? msdyn_Unit 
	{
		get => GetValue<uomInput?>("msdyn_Unit");
		set => SetValue("msdyn_Unit", value);
	}
    public uomscheduleInput? msdyn_UnitSchedule 
	{
		get => GetValue<uomscheduleInput?>("msdyn_UnitSchedule");
		set => SetValue("msdyn_UnitSchedule", value);
	}
    public accountInput? msdyn_ServiceAccount 
	{
		get => GetValue<accountInput?>("msdyn_ServiceAccount");
		set => SetValue("msdyn_ServiceAccount", value);
	}
    public msdyn_agreementInput? msdyn_Agreement 
	{
		get => GetValue<msdyn_agreementInput?>("msdyn_Agreement");
		set => SetValue("msdyn_Agreement", value);
	}
    public msdyn_incidenttypeInput? msdyn_IncidentType 
	{
		get => GetValue<msdyn_incidenttypeInput?>("msdyn_IncidentType");
		set => SetValue("msdyn_IncidentType", value);
	}
    public msdyn_taxcodeInput? msdyn_TaxCode 
	{
		get => GetValue<msdyn_taxcodeInput?>("msdyn_TaxCode");
		set => SetValue("msdyn_TaxCode", value);
	}
    public msdyn_warehouseInput? msdyn_Warehouse 
	{
		get => GetValue<msdyn_warehouseInput?>("msdyn_Warehouse");
		set => SetValue("msdyn_Warehouse", value);
	}
    public msdyn_workorderInput? msdyn_WorkOrder 
	{
		get => GetValue<msdyn_workorderInput?>("msdyn_WorkOrder");
		set => SetValue("msdyn_WorkOrder", value);
	}
    public msdyn_workordertypeInput? msdyn_WorkOrderType 
	{
		get => GetValue<msdyn_workordertypeInput?>("msdyn_WorkOrderType");
		set => SetValue("msdyn_WorkOrderType", value);
	}
    public territoryInput? msdyn_ServiceTerritory 
	{
		get => GetValue<territoryInput?>("msdyn_ServiceTerritory");
		set => SetValue("msdyn_ServiceTerritory", value);
	}

}
