// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_AutonomousSQA_GetEngageAndReadinessAgentResultResponse
/// </summary>
public partial class msdyn_AutonomousSQA_GetEngageAndReadinessAgentResultResponseInput : ODataInputBase
{
	// IsEnumType: False
    public string? msdyn_Response 
	{
		get => GetValue<string?>("msdyn_Response");
		set => SetValue("msdyn_Response", value);
	}

    //Navigations

}
