// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdynmkt_ValidatePlaceholdersResponse
/// </summary>
public partial class msdynmkt_ValidatePlaceholdersResponseInput : ODataInputBase
{
	// IsEnumType: False
    public string? ValidatePlaceholdersResult 
	{
		get => GetValue<string?>("ValidatePlaceholdersResult");
		set => SetValue("ValidatePlaceholdersResult", value);
	}

    //Navigations

}
