// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_mobileapp
/// </summary>
public partial class msdyn_mobileappInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? _msdyn_primarypublishedappname_value 
	{
		get => GetValue<Guid?>("_msdyn_primarypublishedappname_value");
		set => SetValue("_msdyn_primarypublishedappname_value", value);
	}
	// IsEnumType: False
    public string? msdyn_appicon1024x1024_name 
	{
		get => GetValue<string?>("msdyn_appicon1024x1024_name");
		set => SetValue("msdyn_appicon1024x1024_name", value);
	}
	// IsEnumType: False
    public string? msdyn_appiconxdpi_name 
	{
		get => GetValue<string?>("msdyn_appiconxdpi_name");
		set => SetValue("msdyn_appiconxdpi_name", value);
	}
	// IsEnumType: False
    public string? msdyn_buttoncolor 
	{
		get => GetValue<string?>("msdyn_buttoncolor");
		set => SetValue("msdyn_buttoncolor", value);
	}
	// IsEnumType: False
    public string? msdyn_appicon152x152_name 
	{
		get => GetValue<string?>("msdyn_appicon152x152_name");
		set => SetValue("msdyn_appicon152x152_name", value);
	}
	// IsEnumType: False
    public string? msdyn_appicon180x180_name 
	{
		get => GetValue<string?>("msdyn_appicon180x180_name");
		set => SetValue("msdyn_appicon180x180_name", value);
	}
	// IsEnumType: False
    public string? msdyn_displayname 
	{
		get => GetValue<string?>("msdyn_displayname");
		set => SetValue("msdyn_displayname", value);
	}
	// IsEnumType: False
    public string? msdyn_uniquename 
	{
		get => GetValue<string?>("msdyn_uniquename");
		set => SetValue("msdyn_uniquename", value);
	}
	// IsEnumType: False
    public string? msdyn_builddetails 
	{
		get => GetValue<string?>("msdyn_builddetails");
		set => SetValue("msdyn_builddetails", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appicon167x167 
	{
		get => GetValue<byte[]?>("msdyn_appicon167x167");
		set => SetValue("msdyn_appicon167x167", value);
	}
	// IsEnumType: False
    public string? msdyn_appcenterappidipa 
	{
		get => GetValue<string?>("msdyn_appcenterappidipa");
		set => SetValue("msdyn_appcenterappidipa", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_androidappcenterapitoken 
	{
		get => GetValue<string?>("msdyn_androidappcenterapitoken");
		set => SetValue("msdyn_androidappcenterapitoken", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public string? msdyn_appiconmdpi_name 
	{
		get => GetValue<string?>("msdyn_appiconmdpi_name");
		set => SetValue("msdyn_appiconmdpi_name", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public string? msdyn_headingtextcolor 
	{
		get => GetValue<string?>("msdyn_headingtextcolor");
		set => SetValue("msdyn_headingtextcolor", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_tenantsplashimage 
	{
		get => GetValue<byte[]?>("msdyn_tenantsplashimage");
		set => SetValue("msdyn_tenantsplashimage", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appiconmdpi 
	{
		get => GetValue<byte[]?>("msdyn_appiconmdpi");
		set => SetValue("msdyn_appiconmdpi", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appiconxxhdpi 
	{
		get => GetValue<byte[]?>("msdyn_appiconxxhdpi");
		set => SetValue("msdyn_appiconxxhdpi", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appiconxxxhdpi 
	{
		get => GetValue<byte[]?>("msdyn_appiconxxxhdpi");
		set => SetValue("msdyn_appiconxxxhdpi", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public string? msdyn_azureblobstorageaccountname 
	{
		get => GetValue<string?>("msdyn_azureblobstorageaccountname");
		set => SetValue("msdyn_azureblobstorageaccountname", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appicon1024x1024 
	{
		get => GetValue<byte[]?>("msdyn_appicon1024x1024");
		set => SetValue("msdyn_appicon1024x1024", value);
	}
	// IsEnumType: False
    public string? msdyn_customdimensions 
	{
		get => GetValue<string?>("msdyn_customdimensions");
		set => SetValue("msdyn_customdimensions", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appiconhdpi 
	{
		get => GetValue<byte[]?>("msdyn_appiconhdpi");
		set => SetValue("msdyn_appiconhdpi", value);
	}
	// IsEnumType: False
    public string? msdyn_appiconhdpi_name 
	{
		get => GetValue<string?>("msdyn_appiconhdpi_name");
		set => SetValue("msdyn_appiconhdpi_name", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appicon120x120 
	{
		get => GetValue<byte[]?>("msdyn_appicon120x120");
		set => SetValue("msdyn_appicon120x120", value);
	}
	// IsEnumType: False
    public string? msdyn_appiconxxhdpi_name 
	{
		get => GetValue<string?>("msdyn_appiconxxhdpi_name");
		set => SetValue("msdyn_appiconxxhdpi_name", value);
	}
	// IsEnumType: False
    public string? msdyn_pushnotificationsandroidjson_name 
	{
		get => GetValue<string?>("msdyn_pushnotificationsandroidjson_name");
		set => SetValue("msdyn_pushnotificationsandroidjson_name", value);
	}
	// IsEnumType: False
    public string? msdyn_prodev_custompackage_name 
	{
		get => GetValue<string?>("msdyn_prodev_custompackage_name");
		set => SetValue("msdyn_prodev_custompackage_name", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public string? msdyn_appicon120x120_name 
	{
		get => GetValue<string?>("msdyn_appicon120x120_name");
		set => SetValue("msdyn_appicon120x120_name", value);
	}
	// IsEnumType: False
    public int? componentstate 
	{
		get => GetValue<int?>("componentstate");
		set => SetValue("componentstate", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appiconxdpi 
	{
		get => GetValue<byte[]?>("msdyn_appiconxdpi");
		set => SetValue("msdyn_appiconxdpi", value);
	}
	// IsEnumType: False
    public string? msdyn_actionbuttonhighlight 
	{
		get => GetValue<string?>("msdyn_actionbuttonhighlight");
		set => SetValue("msdyn_actionbuttonhighlight", value);
	}
	// IsEnumType: False
    public string? msdyn_androidappcenterapitokensaved 
	{
		get => GetValue<string?>("msdyn_androidappcenterapitokensaved");
		set => SetValue("msdyn_androidappcenterapitokensaved", value);
	}
	// IsEnumType: False
    public string? msdyn_platformtype 
	{
		get => GetValue<string?>("msdyn_platformtype");
		set => SetValue("msdyn_platformtype", value);
	}
	// IsEnumType: False
    public string? msdyn_appicon167x167_name 
	{
		get => GetValue<string?>("msdyn_appicon167x167_name");
		set => SetValue("msdyn_appicon167x167_name", value);
	}
	// IsEnumType: False
    public Guid? msdyn_mobileappid 
	{
		get => GetValue<Guid?>("msdyn_mobileappid");
		set => SetValue("msdyn_mobileappid", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_launchappresources 
	{
		get => GetValue<byte[]?>("msdyn_launchappresources");
		set => SetValue("msdyn_launchappresources", value);
	}
	// IsEnumType: False
    public string? msdyn_launchappresources_name 
	{
		get => GetValue<string?>("msdyn_launchappresources_name");
		set => SetValue("msdyn_launchappresources_name", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_mobileappdefinitionios 
	{
		get => GetValue<byte[]?>("msdyn_mobileappdefinitionios");
		set => SetValue("msdyn_mobileappdefinitionios", value);
	}
	// IsEnumType: False
    public string? msdyn_branch 
	{
		get => GetValue<string?>("msdyn_branch");
		set => SetValue("msdyn_branch", value);
	}
	// IsEnumType: False
    public string? msdyn_tenantsplashimage_name 
	{
		get => GetValue<string?>("msdyn_tenantsplashimage_name");
		set => SetValue("msdyn_tenantsplashimage_name", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_mobileappdefinitionandroid 
	{
		get => GetValue<byte[]?>("msdyn_mobileappdefinitionandroid");
		set => SetValue("msdyn_mobileappdefinitionandroid", value);
	}
	// IsEnumType: False
    public string? msdyn_pushnotificationsenabled_ios 
	{
		get => GetValue<string?>("msdyn_pushnotificationsenabled_ios");
		set => SetValue("msdyn_pushnotificationsenabled_ios", value);
	}
	// IsEnumType: False
    public string? msdyn_pushnotificationsenabled_android 
	{
		get => GetValue<string?>("msdyn_pushnotificationsenabled_android");
		set => SetValue("msdyn_pushnotificationsenabled_android", value);
	}
	// IsEnumType: False
    public BooleanManagedPropertyInput? iscustomizable 
	{
		get => GetValue<BooleanManagedPropertyInput?>("iscustomizable");
		set => SetValue("iscustomizable", value);
	}
	// IsEnumType: False
    public string? msdyn_recentbuild 
	{
		get => GetValue<string?>("msdyn_recentbuild");
		set => SetValue("msdyn_recentbuild", value);
	}
	// IsEnumType: False
    public string? msdyn_hyperlinkcolor 
	{
		get => GetValue<string?>("msdyn_hyperlinkcolor");
		set => SetValue("msdyn_hyperlinkcolor", value);
	}
	// IsEnumType: False
    public string? msdyn_adalredirecturi 
	{
		get => GetValue<string?>("msdyn_adalredirecturi");
		set => SetValue("msdyn_adalredirecturi", value);
	}
	// IsEnumType: False
    public string? msdyn_appcenterappidapk 
	{
		get => GetValue<string?>("msdyn_appcenterappidapk");
		set => SetValue("msdyn_appcenterappidapk", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public string? msdyn_azureblobstoragecontainername 
	{
		get => GetValue<string?>("msdyn_azureblobstoragecontainername");
		set => SetValue("msdyn_azureblobstoragecontainername", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overwritetime 
	{
		get => GetValue<DateTimeOffset?>("overwritetime");
		set => SetValue("overwritetime", value);
	}
	// IsEnumType: False
    public string? msdyn_isappsigningenabled 
	{
		get => GetValue<string?>("msdyn_isappsigningenabled");
		set => SetValue("msdyn_isappsigningenabled", value);
	}
	// IsEnumType: False
    public string? msdyn_appiconxxxhdpi_name 
	{
		get => GetValue<string?>("msdyn_appiconxxxhdpi_name");
		set => SetValue("msdyn_appiconxxxhdpi_name", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_pushnotificationsiosplist 
	{
		get => GetValue<byte[]?>("msdyn_pushnotificationsiosplist");
		set => SetValue("msdyn_pushnotificationsiosplist", value);
	}
	// IsEnumType: False
    public Guid? componentidunique 
	{
		get => GetValue<Guid?>("componentidunique");
		set => SetValue("componentidunique", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public bool? ismanaged 
	{
		get => GetValue<bool?>("ismanaged");
		set => SetValue("ismanaged", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_prodev_custompackage 
	{
		get => GetValue<byte[]?>("msdyn_prodev_custompackage");
		set => SetValue("msdyn_prodev_custompackage", value);
	}
	// IsEnumType: False
    public string? msdyn_orgname 
	{
		get => GetValue<string?>("msdyn_orgname");
		set => SetValue("msdyn_orgname", value);
	}
	// IsEnumType: False
    public string? msdyn_secondaryapps 
	{
		get => GetValue<string?>("msdyn_secondaryapps");
		set => SetValue("msdyn_secondaryapps", value);
	}
	// IsEnumType: False
    public string? msdyn_iosenterprisesigningenabled 
	{
		get => GetValue<string?>("msdyn_iosenterprisesigningenabled");
		set => SetValue("msdyn_iosenterprisesigningenabled", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? msdyn_mobileappdefinitionios_name 
	{
		get => GetValue<string?>("msdyn_mobileappdefinitionios_name");
		set => SetValue("msdyn_mobileappdefinitionios_name", value);
	}
	// IsEnumType: False
    public string? msdyn_pushnotificationsiosplist_name 
	{
		get => GetValue<string?>("msdyn_pushnotificationsiosplist_name");
		set => SetValue("msdyn_pushnotificationsiosplist_name", value);
	}
	// IsEnumType: False
    public string? msdyn_keyvaulturi 
	{
		get => GetValue<string?>("msdyn_keyvaulturi");
		set => SetValue("msdyn_keyvaulturi", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appicon152x152 
	{
		get => GetValue<byte[]?>("msdyn_appicon152x152");
		set => SetValue("msdyn_appicon152x152", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? msdyn_statusbarcontentcolormode 
	{
		get => GetValue<string?>("msdyn_statusbarcontentcolormode");
		set => SetValue("msdyn_statusbarcontentcolormode", value);
	}
	// IsEnumType: False
    public string? msdyn_iosappcenterapitoken 
	{
		get => GetValue<string?>("msdyn_iosappcenterapitoken");
		set => SetValue("msdyn_iosappcenterapitoken", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_tenantwelcomeimage_name 
	{
		get => GetValue<string?>("msdyn_tenantwelcomeimage_name");
		set => SetValue("msdyn_tenantwelcomeimage_name", value);
	}
	// IsEnumType: False
    public string? msdyn_iosappcenterapitokensaved 
	{
		get => GetValue<string?>("msdyn_iosappcenterapitokensaved");
		set => SetValue("msdyn_iosappcenterapitokensaved", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_appicon180x180 
	{
		get => GetValue<byte[]?>("msdyn_appicon180x180");
		set => SetValue("msdyn_appicon180x180", value);
	}
	// IsEnumType: False
    public string? msdyn_appcenterappidaab 
	{
		get => GetValue<string?>("msdyn_appcenterappidaab");
		set => SetValue("msdyn_appcenterappidaab", value);
	}
	// IsEnumType: False
    public string? msdyn_adalclientid 
	{
		get => GetValue<string?>("msdyn_adalclientid");
		set => SetValue("msdyn_adalclientid", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? msdyn_secondarypublishedappnames 
	{
		get => GetValue<string?>("msdyn_secondarypublishedappnames");
		set => SetValue("msdyn_secondarypublishedappnames", value);
	}
	// IsEnumType: False
    public string? msdyn_storagetypeforupload 
	{
		get => GetValue<string?>("msdyn_storagetypeforupload");
		set => SetValue("msdyn_storagetypeforupload", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_tenantwelcomeimage 
	{
		get => GetValue<byte[]?>("msdyn_tenantwelcomeimage");
		set => SetValue("msdyn_tenantwelcomeimage", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public string? msdyn_fillcolor 
	{
		get => GetValue<string?>("msdyn_fillcolor");
		set => SetValue("msdyn_fillcolor", value);
	}
	// IsEnumType: False
    public byte[]? msdyn_pushnotificationsandroidjson 
	{
		get => GetValue<byte[]?>("msdyn_pushnotificationsandroidjson");
		set => SetValue("msdyn_pushnotificationsandroidjson", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public string? msdyn_bundleidentifier 
	{
		get => GetValue<string?>("msdyn_bundleidentifier");
		set => SetValue("msdyn_bundleidentifier", value);
	}
	// IsEnumType: False
    public string? msdyn_mobileappdefinitionandroid_name 
	{
		get => GetValue<string?>("msdyn_mobileappdefinitionandroid_name");
		set => SetValue("msdyn_mobileappdefinitionandroid_name", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyn_mobileapp_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_mobileapp_SyncErrors");
		set => SetValue("msdyn_mobileapp_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_mobileapp_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_mobileapp_DuplicateMatchingRecord");
		set => SetValue("msdyn_mobileapp_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_mobileapp_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_mobileapp_DuplicateBaseRecord");
		set => SetValue("msdyn_mobileapp_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_mobileapp_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_mobileapp_AsyncOperations");
		set => SetValue("msdyn_mobileapp_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_mobileapp_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_mobileapp_MailboxTrackingFolders");
		set => SetValue("msdyn_mobileapp_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_mobileapp_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_mobileapp_ProcessSession");
		set => SetValue("msdyn_mobileapp_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_mobileapp_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_mobileapp_BulkDeleteFailures");
		set => SetValue("msdyn_mobileapp_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_mobileapp_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_mobileapp_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_mobileapp_PrincipalObjectAttributeAccesses", value);
	}
    public List<fileattachmentInput>? msdyn_mobileapp_FileAttachments 
	{
		get => GetValue<List<fileattachmentInput>?>("msdyn_mobileapp_FileAttachments");
		set => SetValue("msdyn_mobileapp_FileAttachments", value);
	}
    public canvasappInput? msdyn_primaryPublishedAppName 
	{
		get => GetValue<canvasappInput?>("msdyn_primaryPublishedAppName");
		set => SetValue("msdyn_primaryPublishedAppName", value);
	}

}
