// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_entityderivedinsight
/// </summary>
public partial class msdyn_entityderivedinsightInput : ODataInputBase
{
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public string? msdyn_insightsdata 
	{
		get => GetValue<string?>("msdyn_insightsdata");
		set => SetValue("msdyn_insightsdata", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public string? msdyn_externalcrmorgid 
	{
		get => GetValue<string?>("msdyn_externalcrmorgid");
		set => SetValue("msdyn_externalcrmorgid", value);
	}
	// IsEnumType: False
    public string? msdyn_entitytypename 
	{
		get => GetValue<string?>("msdyn_entitytypename");
		set => SetValue("msdyn_entitytypename", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? msdyn_entityderivedinsightid 
	{
		get => GetValue<Guid?>("msdyn_entityderivedinsightid");
		set => SetValue("msdyn_entityderivedinsightid", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? msdyn_entityrecordid 
	{
		get => GetValue<string?>("msdyn_entityrecordid");
		set => SetValue("msdyn_entityrecordid", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? msdyn_processingretrycount 
	{
		get => GetValue<int?>("msdyn_processingretrycount");
		set => SetValue("msdyn_processingretrycount", value);
	}
	// IsEnumType: False
    public string? msdyn_dataformatversion 
	{
		get => GetValue<string?>("msdyn_dataformatversion");
		set => SetValue("msdyn_dataformatversion", value);
	}
	// IsEnumType: False
    public string? msdyn_status 
	{
		get => GetValue<string?>("msdyn_status");
		set => SetValue("msdyn_status", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public Guid? _organizationid_value 
	{
		get => GetValue<Guid?>("_organizationid_value");
		set => SetValue("_organizationid_value", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_processedtimestamp 
	{
		get => GetValue<DateTimeOffset?>("msdyn_processedtimestamp");
		set => SetValue("msdyn_processedtimestamp", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public organizationInput? organizationid 
	{
		get => GetValue<organizationInput?>("organizationid");
		set => SetValue("organizationid", value);
	}
    public List<syncerrorInput>? msdyn_entityderivedinsight_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_entityderivedinsight_SyncErrors");
		set => SetValue("msdyn_entityderivedinsight_SyncErrors", value);
	}
    public List<asyncoperationInput>? msdyn_entityderivedinsight_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_entityderivedinsight_AsyncOperations");
		set => SetValue("msdyn_entityderivedinsight_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_entityderivedinsight_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_entityderivedinsight_MailboxTrackingFolders");
		set => SetValue("msdyn_entityderivedinsight_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_entityderivedinsight_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_entityderivedinsight_ProcessSession");
		set => SetValue("msdyn_entityderivedinsight_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_entityderivedinsight_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_entityderivedinsight_BulkDeleteFailures");
		set => SetValue("msdyn_entityderivedinsight_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_entityderivedinsight_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_entityderivedinsight_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_entityderivedinsight_PrincipalObjectAttributeAccesses", value);
	}
    public List<msdyn_derivedinsightsrelatedentityInput>? msdyn_derivedinsightsrelatedentity_derivedinsight_msdyn_entityderivedinsight 
	{
		get => GetValue<List<msdyn_derivedinsightsrelatedentityInput>?>("msdyn_derivedinsightsrelatedentity_derivedinsight_msdyn_entityderivedinsight");
		set => SetValue("msdyn_derivedinsightsrelatedentity_derivedinsight_msdyn_entityderivedinsight", value);
	}

}
