// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_conversationaction
/// </summary>
public partial class msdyn_conversationactionInput : ODataInputBase
{
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public string? msdyn_functionname 
	{
		get => GetValue<string?>("msdyn_functionname");
		set => SetValue("msdyn_functionname", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? msdyn_conversationactionid 
	{
		get => GetValue<Guid?>("msdyn_conversationactionid");
		set => SetValue("msdyn_conversationactionid", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public string? msdyn_webresource 
	{
		get => GetValue<string?>("msdyn_webresource");
		set => SetValue("msdyn_webresource", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public int? msdyn_eventname 
	{
		get => GetValue<int?>("msdyn_eventname");
		set => SetValue("msdyn_eventname", value);
	}
	// IsEnumType: False
    public string? msdyn_eventparameter 
	{
		get => GetValue<string?>("msdyn_eventparameter");
		set => SetValue("msdyn_eventparameter", value);
	}
	// IsEnumType: False
    public int? msdyn_order 
	{
		get => GetValue<int?>("msdyn_order");
		set => SetValue("msdyn_order", value);
	}
	// IsEnumType: False
    public string? msdyn_icon 
	{
		get => GetValue<string?>("msdyn_icon");
		set => SetValue("msdyn_icon", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyn_conversationaction_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_conversationaction_SyncErrors");
		set => SetValue("msdyn_conversationaction_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_conversationaction_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_conversationaction_DuplicateMatchingRecord");
		set => SetValue("msdyn_conversationaction_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_conversationaction_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_conversationaction_DuplicateBaseRecord");
		set => SetValue("msdyn_conversationaction_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_conversationaction_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_conversationaction_AsyncOperations");
		set => SetValue("msdyn_conversationaction_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_conversationaction_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_conversationaction_MailboxTrackingFolders");
		set => SetValue("msdyn_conversationaction_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_conversationaction_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_conversationaction_ProcessSession");
		set => SetValue("msdyn_conversationaction_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_conversationaction_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_conversationaction_BulkDeleteFailures");
		set => SetValue("msdyn_conversationaction_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_conversationaction_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_conversationaction_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_conversationaction_PrincipalObjectAttributeAccesses", value);
	}
    public List<msdyn_channelcapabilityInput>? msdyn_msdyn_conversationaction_msdyn_channelcapability_ConversationAction 
	{
		get => GetValue<List<msdyn_channelcapabilityInput>?>("msdyn_msdyn_conversationaction_msdyn_channelcapability_ConversationAction");
		set => SetValue("msdyn_msdyn_conversationaction_msdyn_channelcapability_ConversationAction", value);
	}
    public List<msdyn_conversationactionlocaleInput>? msdyn_msdyn_conversationaction_msdyn_conversationactionlocale_CAkey 
	{
		get => GetValue<List<msdyn_conversationactionlocaleInput>?>("msdyn_msdyn_conversationaction_msdyn_conversationactionlocale_CAkey");
		set => SetValue("msdyn_msdyn_conversationaction_msdyn_conversationactionlocale_CAkey", value);
	}

}
