// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_customerfeedbacksurvey
/// </summary>
public partial class msdyn_customerfeedbacksurveyInput : ODataInputBase
{
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public Guid? _organizationid_value 
	{
		get => GetValue<Guid?>("_organizationid_value");
		set => SetValue("_organizationid_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_customerfeedbacksurveyurl 
	{
		get => GetValue<string?>("msdyn_customerfeedbacksurveyurl");
		set => SetValue("msdyn_customerfeedbacksurveyurl", value);
	}
	// IsEnumType: False
    public string? msdyn_customerfeedbacksurveyname 
	{
		get => GetValue<string?>("msdyn_customerfeedbacksurveyname");
		set => SetValue("msdyn_customerfeedbacksurveyname", value);
	}
	// IsEnumType: False
    public string? msdyn_customconfig 
	{
		get => GetValue<string?>("msdyn_customconfig");
		set => SetValue("msdyn_customconfig", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public int? msdyn_customerfeedbackbotstatus 
	{
		get => GetValue<int?>("msdyn_customerfeedbackbotstatus");
		set => SetValue("msdyn_customerfeedbackbotstatus", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_microsoftcopilotstudiobot_value 
	{
		get => GetValue<Guid?>("_msdyn_microsoftcopilotstudiobot_value");
		set => SetValue("_msdyn_microsoftcopilotstudiobot_value", value);
	}
	// IsEnumType: False
    public int? msdyn_customerfeedbacksurveyprovider 
	{
		get => GetValue<int?>("msdyn_customerfeedbacksurveyprovider");
		set => SetValue("msdyn_customerfeedbacksurveyprovider", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? msdyn_customerfeedbacksurveyid 
	{
		get => GetValue<Guid?>("msdyn_customerfeedbacksurveyid");
		set => SetValue("msdyn_customerfeedbacksurveyid", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public string? msdyn_customhosturl 
	{
		get => GetValue<string?>("msdyn_customhosturl");
		set => SetValue("msdyn_customhosturl", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public organizationInput? organizationid 
	{
		get => GetValue<organizationInput?>("organizationid");
		set => SetValue("organizationid", value);
	}
    public List<syncerrorInput>? msdyn_customerfeedbacksurvey_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_customerfeedbacksurvey_SyncErrors");
		set => SetValue("msdyn_customerfeedbacksurvey_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_customerfeedbacksurvey_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_customerfeedbacksurvey_DuplicateMatchingRecord");
		set => SetValue("msdyn_customerfeedbacksurvey_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_customerfeedbacksurvey_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_customerfeedbacksurvey_DuplicateBaseRecord");
		set => SetValue("msdyn_customerfeedbacksurvey_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_customerfeedbacksurvey_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_customerfeedbacksurvey_AsyncOperations");
		set => SetValue("msdyn_customerfeedbacksurvey_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_customerfeedbacksurvey_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_customerfeedbacksurvey_MailboxTrackingFolders");
		set => SetValue("msdyn_customerfeedbacksurvey_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_customerfeedbacksurvey_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_customerfeedbacksurvey_ProcessSession");
		set => SetValue("msdyn_customerfeedbacksurvey_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_customerfeedbacksurvey_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_customerfeedbacksurvey_BulkDeleteFailures");
		set => SetValue("msdyn_customerfeedbacksurvey_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_customerfeedbacksurvey_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_customerfeedbacksurvey_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_customerfeedbacksurvey_PrincipalObjectAttributeAccesses", value);
	}
    public botInput? msdyn_microsoftcopilotstudiobot 
	{
		get => GetValue<botInput?>("msdyn_microsoftcopilotstudiobot");
		set => SetValue("msdyn_microsoftcopilotstudiobot", value);
	}
    public List<msdyn_customerfeedbacksurveyinviteInput>? msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyinvite 
	{
		get => GetValue<List<msdyn_customerfeedbacksurveyinviteInput>?>("msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyinvite");
		set => SetValue("msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyinvite", value);
	}
    public List<msdyn_customerfeedbacksurveyresponseInput>? msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyresponse 
	{
		get => GetValue<List<msdyn_customerfeedbacksurveyresponseInput>?>("msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyresponse");
		set => SetValue("msdyn_customerfeedbacksurvey_msdyn_customerfeedbacksurveyresponse", value);
	}
    public List<msdyn_surveyconfigInput>? msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_agentsurveyid 
	{
		get => GetValue<List<msdyn_surveyconfigInput>?>("msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_agentsurveyid");
		set => SetValue("msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_agentsurveyid", value);
	}
    public List<msdyn_surveyconfigInput>? msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_botsurveyid 
	{
		get => GetValue<List<msdyn_surveyconfigInput>?>("msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_botsurveyid");
		set => SetValue("msdyn_customerfeedbacksurvey_msdyn_surveyconfig_msdyn_botsurveyid", value);
	}
    public List<msdyn_surveysettingInput>? msdyn_customerfeedbacksurvey_msdyn_surveysetting 
	{
		get => GetValue<List<msdyn_surveysettingInput>?>("msdyn_customerfeedbacksurvey_msdyn_surveysetting");
		set => SetValue("msdyn_customerfeedbacksurvey_msdyn_surveysetting", value);
	}

}
