// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_agreementinvoicesetup
/// </summary>
public partial class msdyn_agreementinvoicesetupInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? msdyn_agreementinvoicesetupid 
	{
		get => GetValue<Guid?>("msdyn_agreementinvoicesetupid");
		set => SetValue("msdyn_agreementinvoicesetupid", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public string? traversedpath 
	{
		get => GetValue<string?>("traversedpath");
		set => SetValue("traversedpath", value);
	}
	// IsEnumType: False
    public Guid? _stageid_value 
	{
		get => GetValue<Guid?>("_stageid_value");
		set => SetValue("_stageid_value", value);
	}
	// IsEnumType: False
    public string? msdyn_recurrencesettings 
	{
		get => GetValue<string?>("msdyn_recurrencesettings");
		set => SetValue("msdyn_recurrencesettings", value);
	}
	// IsEnumType: False
    public string? msdyn_description 
	{
		get => GetValue<string?>("msdyn_description");
		set => SetValue("msdyn_description", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_processstartedon 
	{
		get => GetValue<DateTimeOffset?>("msdyn_processstartedon");
		set => SetValue("msdyn_processstartedon", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public string? msdyn_internalflags 
	{
		get => GetValue<string?>("msdyn_internalflags");
		set => SetValue("msdyn_internalflags", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? msdyn_revision 
	{
		get => GetValue<int?>("msdyn_revision");
		set => SetValue("msdyn_revision", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msdyn_postponegenerationuntil 
	{
		get => GetValue<DateTimeOffset?>("msdyn_postponegenerationuntil");
		set => SetValue("msdyn_postponegenerationuntil", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? processid 
	{
		get => GetValue<Guid?>("processid");
		set => SetValue("processid", value);
	}
	// IsEnumType: False
    public Guid? _msdyn_agreement_value 
	{
		get => GetValue<Guid?>("_msdyn_agreement_value");
		set => SetValue("_msdyn_agreement_value", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<activitypointerInput>? msdyn_agreementinvoicesetup_ActivityPointers 
	{
		get => GetValue<List<activitypointerInput>?>("msdyn_agreementinvoicesetup_ActivityPointers");
		set => SetValue("msdyn_agreementinvoicesetup_ActivityPointers", value);
	}
    public List<li_inmailInput>? msdyn_agreementinvoicesetup_li_inmails 
	{
		get => GetValue<List<li_inmailInput>?>("msdyn_agreementinvoicesetup_li_inmails");
		set => SetValue("msdyn_agreementinvoicesetup_li_inmails", value);
	}
    public List<msfp_surveyinviteInput>? msdyn_agreementinvoicesetup_msfp_surveyinvites 
	{
		get => GetValue<List<msfp_surveyinviteInput>?>("msdyn_agreementinvoicesetup_msfp_surveyinvites");
		set => SetValue("msdyn_agreementinvoicesetup_msfp_surveyinvites", value);
	}
    public List<li_messageInput>? msdyn_agreementinvoicesetup_li_messages 
	{
		get => GetValue<List<li_messageInput>?>("msdyn_agreementinvoicesetup_li_messages");
		set => SetValue("msdyn_agreementinvoicesetup_li_messages", value);
	}
    public List<msfp_alertInput>? msdyn_agreementinvoicesetup_msfp_alerts 
	{
		get => GetValue<List<msfp_alertInput>?>("msdyn_agreementinvoicesetup_msfp_alerts");
		set => SetValue("msdyn_agreementinvoicesetup_msfp_alerts", value);
	}
    public List<msdyn_bookingalertInput>? msdyn_agreementinvoicesetup_msdyn_bookingalerts 
	{
		get => GetValue<List<msdyn_bookingalertInput>?>("msdyn_agreementinvoicesetup_msdyn_bookingalerts");
		set => SetValue("msdyn_agreementinvoicesetup_msdyn_bookingalerts", value);
	}
    public List<li_pointdrivepresentationviewedInput>? msdyn_agreementinvoicesetup_li_pointdrivepresentationvieweds 
	{
		get => GetValue<List<li_pointdrivepresentationviewedInput>?>("msdyn_agreementinvoicesetup_li_pointdrivepresentationvieweds");
		set => SetValue("msdyn_agreementinvoicesetup_li_pointdrivepresentationvieweds", value);
	}
    public List<zync_logInput>? msdyn_agreementinvoicesetup_zync_logs 
	{
		get => GetValue<List<zync_logInput>?>("msdyn_agreementinvoicesetup_zync_logs");
		set => SetValue("msdyn_agreementinvoicesetup_zync_logs", value);
	}
    public List<msfp_surveyresponseInput>? msdyn_agreementinvoicesetup_msfp_surveyresponses 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("msdyn_agreementinvoicesetup_msfp_surveyresponses");
		set => SetValue("msdyn_agreementinvoicesetup_msfp_surveyresponses", value);
	}
    public List<syncerrorInput>? msdyn_agreementinvoicesetup_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_agreementinvoicesetup_SyncErrors");
		set => SetValue("msdyn_agreementinvoicesetup_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_agreementinvoicesetup_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_agreementinvoicesetup_DuplicateMatchingRecord");
		set => SetValue("msdyn_agreementinvoicesetup_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_agreementinvoicesetup_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_agreementinvoicesetup_DuplicateBaseRecord");
		set => SetValue("msdyn_agreementinvoicesetup_DuplicateBaseRecord", value);
	}
    public List<sharepointdocumentlocationInput>? msdyn_agreementinvoicesetup_SharePointDocumentLocations 
	{
		get => GetValue<List<sharepointdocumentlocationInput>?>("msdyn_agreementinvoicesetup_SharePointDocumentLocations");
		set => SetValue("msdyn_agreementinvoicesetup_SharePointDocumentLocations", value);
	}
    public List<asyncoperationInput>? msdyn_agreementinvoicesetup_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_agreementinvoicesetup_AsyncOperations");
		set => SetValue("msdyn_agreementinvoicesetup_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_agreementinvoicesetup_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_agreementinvoicesetup_MailboxTrackingFolders");
		set => SetValue("msdyn_agreementinvoicesetup_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_agreementinvoicesetup_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_agreementinvoicesetup_ProcessSession");
		set => SetValue("msdyn_agreementinvoicesetup_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_agreementinvoicesetup_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_agreementinvoicesetup_BulkDeleteFailures");
		set => SetValue("msdyn_agreementinvoicesetup_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_agreementinvoicesetup_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_agreementinvoicesetup_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_agreementinvoicesetup_PrincipalObjectAttributeAccesses", value);
	}
    public processstageInput? stageid 
	{
		get => GetValue<processstageInput?>("stageid");
		set => SetValue("stageid", value);
	}
    public List<appointmentInput>? msdyn_agreementinvoicesetup_Appointments 
	{
		get => GetValue<List<appointmentInput>?>("msdyn_agreementinvoicesetup_Appointments");
		set => SetValue("msdyn_agreementinvoicesetup_Appointments", value);
	}
    public List<emailInput>? msdyn_agreementinvoicesetup_Emails 
	{
		get => GetValue<List<emailInput>?>("msdyn_agreementinvoicesetup_Emails");
		set => SetValue("msdyn_agreementinvoicesetup_Emails", value);
	}
    public List<faxInput>? msdyn_agreementinvoicesetup_Faxes 
	{
		get => GetValue<List<faxInput>?>("msdyn_agreementinvoicesetup_Faxes");
		set => SetValue("msdyn_agreementinvoicesetup_Faxes", value);
	}
    public List<letterInput>? msdyn_agreementinvoicesetup_Letters 
	{
		get => GetValue<List<letterInput>?>("msdyn_agreementinvoicesetup_Letters");
		set => SetValue("msdyn_agreementinvoicesetup_Letters", value);
	}
    public List<phonecallInput>? msdyn_agreementinvoicesetup_PhoneCalls 
	{
		get => GetValue<List<phonecallInput>?>("msdyn_agreementinvoicesetup_PhoneCalls");
		set => SetValue("msdyn_agreementinvoicesetup_PhoneCalls", value);
	}
    public List<taskInput>? msdyn_agreementinvoicesetup_Tasks 
	{
		get => GetValue<List<taskInput>?>("msdyn_agreementinvoicesetup_Tasks");
		set => SetValue("msdyn_agreementinvoicesetup_Tasks", value);
	}
    public List<recurringappointmentmasterInput>? msdyn_agreementinvoicesetup_RecurringAppointmentMasters 
	{
		get => GetValue<List<recurringappointmentmasterInput>?>("msdyn_agreementinvoicesetup_RecurringAppointmentMasters");
		set => SetValue("msdyn_agreementinvoicesetup_RecurringAppointmentMasters", value);
	}
    public List<socialactivityInput>? msdyn_agreementinvoicesetup_SocialActivities 
	{
		get => GetValue<List<socialactivityInput>?>("msdyn_agreementinvoicesetup_SocialActivities");
		set => SetValue("msdyn_agreementinvoicesetup_SocialActivities", value);
	}
    public List<connectionInput>? msdyn_agreementinvoicesetup_connections1 
	{
		get => GetValue<List<connectionInput>?>("msdyn_agreementinvoicesetup_connections1");
		set => SetValue("msdyn_agreementinvoicesetup_connections1", value);
	}
    public List<connectionInput>? msdyn_agreementinvoicesetup_connections2 
	{
		get => GetValue<List<connectionInput>?>("msdyn_agreementinvoicesetup_connections2");
		set => SetValue("msdyn_agreementinvoicesetup_connections2", value);
	}
    public List<queueitemInput>? msdyn_agreementinvoicesetup_QueueItems 
	{
		get => GetValue<List<queueitemInput>?>("msdyn_agreementinvoicesetup_QueueItems");
		set => SetValue("msdyn_agreementinvoicesetup_QueueItems", value);
	}
    public List<annotationInput>? msdyn_agreementinvoicesetup_Annotations 
	{
		get => GetValue<List<annotationInput>?>("msdyn_agreementinvoicesetup_Annotations");
		set => SetValue("msdyn_agreementinvoicesetup_Annotations", value);
	}
    public List<serviceappointmentInput>? msdyn_agreementinvoicesetup_ServiceAppointments 
	{
		get => GetValue<List<serviceappointmentInput>?>("msdyn_agreementinvoicesetup_ServiceAppointments");
		set => SetValue("msdyn_agreementinvoicesetup_ServiceAppointments", value);
	}
    public msdyn_agreementInput? msdyn_agreement 
	{
		get => GetValue<msdyn_agreementInput?>("msdyn_agreement");
		set => SetValue("msdyn_agreement", value);
	}
    public List<msdyn_agreementinvoiceproductInput>? msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoiceproduct_AgreementInvoiceSetup 
	{
		get => GetValue<List<msdyn_agreementinvoiceproductInput>?>("msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoiceproduct_AgreementInvoiceSetup");
		set => SetValue("msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoiceproduct_AgreementInvoiceSetup", value);
	}
    public List<msdyn_agreementinvoicedateInput>? msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoicedate_InvoiceSetup 
	{
		get => GetValue<List<msdyn_agreementinvoicedateInput>?>("msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoicedate_InvoiceSetup");
		set => SetValue("msdyn_msdyn_agreementinvoicesetup_msdyn_agreementinvoicedate_InvoiceSetup", value);
	}
    public List<adx_alertsubscriptionInput>? msdyn_agreementinvoicesetup_adx_alertsubscriptions 
	{
		get => GetValue<List<adx_alertsubscriptionInput>?>("msdyn_agreementinvoicesetup_adx_alertsubscriptions");
		set => SetValue("msdyn_agreementinvoicesetup_adx_alertsubscriptions", value);
	}
    public List<adx_inviteredemptionInput>? msdyn_agreementinvoicesetup_adx_inviteredemptions 
	{
		get => GetValue<List<adx_inviteredemptionInput>?>("msdyn_agreementinvoicesetup_adx_inviteredemptions");
		set => SetValue("msdyn_agreementinvoicesetup_adx_inviteredemptions", value);
	}
    public List<adx_portalcommentInput>? msdyn_agreementinvoicesetup_adx_portalcomments 
	{
		get => GetValue<List<adx_portalcommentInput>?>("msdyn_agreementinvoicesetup_adx_portalcomments");
		set => SetValue("msdyn_agreementinvoicesetup_adx_portalcomments", value);
	}
    public List<chatInput>? msdyn_agreementinvoicesetup_chats 
	{
		get => GetValue<List<chatInput>?>("msdyn_agreementinvoicesetup_chats");
		set => SetValue("msdyn_agreementinvoicesetup_chats", value);
	}
    public List<msdyn_ocliveworkitemInput>? msdyn_agreementinvoicesetup_msdyn_ocliveworkitems 
	{
		get => GetValue<List<msdyn_ocliveworkitemInput>?>("msdyn_agreementinvoicesetup_msdyn_ocliveworkitems");
		set => SetValue("msdyn_agreementinvoicesetup_msdyn_ocliveworkitems", value);
	}
    public List<msdyn_ocsessionInput>? msdyn_agreementinvoicesetup_msdyn_ocsessions 
	{
		get => GetValue<List<msdyn_ocsessionInput>?>("msdyn_agreementinvoicesetup_msdyn_ocsessions");
		set => SetValue("msdyn_agreementinvoicesetup_msdyn_ocsessions", value);
	}
    public List<msdyn_copilottranscriptInput>? msdyn_agreementinvoicesetup_msdyn_copilottranscripts 
	{
		get => GetValue<List<msdyn_copilottranscriptInput>?>("msdyn_agreementinvoicesetup_msdyn_copilottranscripts");
		set => SetValue("msdyn_agreementinvoicesetup_msdyn_copilottranscripts", value);
	}
    public List<zync_customerassetnoteInput>? msdyn_agreementinvoicesetup_zync_customerassetnotes 
	{
		get => GetValue<List<zync_customerassetnoteInput>?>("msdyn_agreementinvoicesetup_zync_customerassetnotes");
		set => SetValue("msdyn_agreementinvoicesetup_zync_customerassetnotes", value);
	}
    public List<msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3Input>? bpf_msdyn_agreementinvoicesetup_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3 
	{
		get => GetValue<List<msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3Input>?>("bpf_msdyn_agreementinvoicesetup_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3");
		set => SetValue("bpf_msdyn_agreementinvoicesetup_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3", value);
	}

}
