// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msdyn_ocpaymentprofile
/// </summary>
public partial class msdyn_ocpaymentprofileInput : ODataInputBase
{
	// IsEnumType: False
    public int? msdyn_occhanneltype 
	{
		get => GetValue<int?>("msdyn_occhanneltype");
		set => SetValue("msdyn_occhanneltype", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public BooleanManagedPropertyInput? iscustomizable 
	{
		get => GetValue<BooleanManagedPropertyInput?>("iscustomizable");
		set => SetValue("iscustomizable", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? msdyn_name 
	{
		get => GetValue<string?>("msdyn_name");
		set => SetValue("msdyn_name", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overwritetime 
	{
		get => GetValue<DateTimeOffset?>("overwritetime");
		set => SetValue("overwritetime", value);
	}
	// IsEnumType: False
    public string? msdyn_ocpaymentprofilename 
	{
		get => GetValue<string?>("msdyn_ocpaymentprofilename");
		set => SetValue("msdyn_ocpaymentprofilename", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? componentstate 
	{
		get => GetValue<int?>("componentstate");
		set => SetValue("componentstate", value);
	}
	// IsEnumType: False
    public bool? ismanaged 
	{
		get => GetValue<bool?>("ismanaged");
		set => SetValue("ismanaged", value);
	}
	// IsEnumType: False
    public Guid? componentidunique 
	{
		get => GetValue<Guid?>("componentidunique");
		set => SetValue("componentidunique", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? msdyn_ocpaymentprofileid 
	{
		get => GetValue<Guid?>("msdyn_ocpaymentprofileid");
		set => SetValue("msdyn_ocpaymentprofileid", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? msdyn_ocpaymentprofile_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msdyn_ocpaymentprofile_SyncErrors");
		set => SetValue("msdyn_ocpaymentprofile_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msdyn_ocpaymentprofile_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_ocpaymentprofile_DuplicateMatchingRecord");
		set => SetValue("msdyn_ocpaymentprofile_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msdyn_ocpaymentprofile_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msdyn_ocpaymentprofile_DuplicateBaseRecord");
		set => SetValue("msdyn_ocpaymentprofile_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msdyn_ocpaymentprofile_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msdyn_ocpaymentprofile_AsyncOperations");
		set => SetValue("msdyn_ocpaymentprofile_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msdyn_ocpaymentprofile_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msdyn_ocpaymentprofile_MailboxTrackingFolders");
		set => SetValue("msdyn_ocpaymentprofile_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msdyn_ocpaymentprofile_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msdyn_ocpaymentprofile_ProcessSession");
		set => SetValue("msdyn_ocpaymentprofile_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msdyn_ocpaymentprofile_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msdyn_ocpaymentprofile_BulkDeleteFailures");
		set => SetValue("msdyn_ocpaymentprofile_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msdyn_ocpaymentprofile_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msdyn_ocpaymentprofile_PrincipalObjectAttributeAccesses");
		set => SetValue("msdyn_ocpaymentprofile_PrincipalObjectAttributeAccesses", value);
	}
    public List<msdyn_ocrichobjectmapInput>? msdyn_msdyn_ocpaymentprofile_msdyn_ocrichobjectmap_ocpaymentprofileid 
	{
		get => GetValue<List<msdyn_ocrichobjectmapInput>?>("msdyn_msdyn_ocpaymentprofile_msdyn_ocrichobjectmap_ocpaymentprofileid");
		set => SetValue("msdyn_msdyn_ocpaymentprofile_msdyn_ocrichobjectmap_ocpaymentprofileid", value);
	}

}
