// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msfp_surveyresponse
/// </summary>
public partial class msfp_surveyresponseInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? _msfp_surveyinviteid_value 
	{
		get => GetValue<Guid?>("_msfp_surveyinviteid_value");
		set => SetValue("_msfp_surveyinviteid_value", value);
	}
	// IsEnumType: False
    public string? msfp_otherproperties 
	{
		get => GetValue<string?>("msfp_otherproperties");
		set => SetValue("msfp_otherproperties", value);
	}
	// IsEnumType: False
    public string? msfp_name 
	{
		get => GetValue<string?>("msfp_name");
		set => SetValue("msfp_name", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? msfp_sentiment 
	{
		get => GetValue<int?>("msfp_sentiment");
		set => SetValue("msfp_sentiment", value);
	}
	// IsEnumType: False
    public string? msfp_respondentemailaddress 
	{
		get => GetValue<string?>("msfp_respondentemailaddress");
		set => SetValue("msfp_respondentemailaddress", value);
	}
	// IsEnumType: False
    public string? msfp_respondent 
	{
		get => GetValue<string?>("msfp_respondent");
		set => SetValue("msfp_respondent", value);
	}
	// IsEnumType: False
    public string? msfp_surveyresponse 
	{
		get => GetValue<string?>("msfp_surveyresponse");
		set => SetValue("msfp_surveyresponse", value);
	}
	// IsEnumType: False
    public string? msfp_responsetype 
	{
		get => GetValue<string?>("msfp_responsetype");
		set => SetValue("msfp_responsetype", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msfp_submitdate 
	{
		get => GetValue<DateTimeOffset?>("msfp_submitdate");
		set => SetValue("msfp_submitdate", value);
	}
	// IsEnumType: False
    public int? msfp_npsscore 
	{
		get => GetValue<int?>("msfp_npsscore");
		set => SetValue("msfp_npsscore", value);
	}
	// IsEnumType: False
    public Guid? _msfp_parentsurveyresponse_value 
	{
		get => GetValue<Guid?>("_msfp_parentsurveyresponse_value");
		set => SetValue("_msfp_parentsurveyresponse_value", value);
	}
	// IsEnumType: False
    public bool? msfp_satisfactionmetriccalculated 
	{
		get => GetValue<bool?>("msfp_satisfactionmetriccalculated");
		set => SetValue("msfp_satisfactionmetriccalculated", value);
	}
	// IsEnumType: False
    public string? msfp_locale 
	{
		get => GetValue<string?>("msfp_locale");
		set => SetValue("msfp_locale", value);
	}
	// IsEnumType: False
    public string? msfp_sourceresponseidentifier 
	{
		get => GetValue<string?>("msfp_sourceresponseidentifier");
		set => SetValue("msfp_sourceresponseidentifier", value);
	}
	// IsEnumType: False
    public string? msfp_sourcesurveyidentifier 
	{
		get => GetValue<string?>("msfp_sourcesurveyidentifier");
		set => SetValue("msfp_sourcesurveyidentifier", value);
	}
	// IsEnumType: False
    public string? msfp_satisfactionmetricvalue 
	{
		get => GetValue<string?>("msfp_satisfactionmetricvalue");
		set => SetValue("msfp_satisfactionmetricvalue", value);
	}
	// IsEnumType: False
    public Guid? _msfp_surveyid_value 
	{
		get => GetValue<Guid?>("_msfp_surveyid_value");
		set => SetValue("_msfp_surveyid_value", value);
	}
	// IsEnumType: False
    public string? msfp_embedcontextparameters 
	{
		get => GetValue<string?>("msfp_embedcontextparameters");
		set => SetValue("msfp_embedcontextparameters", value);
	}
	// IsEnumType: False
    public bool? msfp_isquestionresponsesgenerated 
	{
		get => GetValue<bool?>("msfp_isquestionresponsesgenerated");
		set => SetValue("msfp_isquestionresponsesgenerated", value);
	}
	// IsEnumType: False
    public string? msfp_questionresponseslist 
	{
		get => GetValue<string?>("msfp_questionresponseslist");
		set => SetValue("msfp_questionresponseslist", value);
	}
	// IsEnumType: False
    public DateTimeOffset? msfp_startdate 
	{
		get => GetValue<DateTimeOffset?>("msfp_startdate");
		set => SetValue("msfp_startdate", value);
	}
	// IsEnumType: False
    public Guid? _msfp_parent_survey_response_new_value 
	{
		get => GetValue<Guid?>("_msfp_parent_survey_response_new_value");
		set => SetValue("_msfp_parent_survey_response_new_value", value);
	}
	// IsEnumType: False
    public bool? msfp_isquestionresponsegenerated 
	{
		get => GetValue<bool?>("msfp_isquestionresponsegenerated");
		set => SetValue("msfp_isquestionresponsegenerated", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public string? msfp_language 
	{
		get => GetValue<string?>("msfp_language");
		set => SetValue("msfp_language", value);
	}
	// IsEnumType: False
    public string? msfp_surveyresponseurl 
	{
		get => GetValue<string?>("msfp_surveyresponseurl");
		set => SetValue("msfp_surveyresponseurl", value);
	}

    //Navigations
    public do_dynamicspdfInput? regardingobjectid_do_dynamicspdf_msfp_surveyresponse 
	{
		get => GetValue<do_dynamicspdfInput?>("regardingobjectid_do_dynamicspdf_msfp_surveyresponse");
		set => SetValue("regardingobjectid_do_dynamicspdf_msfp_surveyresponse", value);
	}
    public zync_objectInput? regardingobjectid_zync_object_msfp_surveyresponse 
	{
		get => GetValue<zync_objectInput?>("regardingobjectid_zync_object_msfp_surveyresponse");
		set => SetValue("regardingobjectid_zync_object_msfp_surveyresponse", value);
	}
    public leadInput? regardingobjectid_lead_msfp_surveyresponse 
	{
		get => GetValue<leadInput?>("regardingobjectid_lead_msfp_surveyresponse");
		set => SetValue("regardingobjectid_lead_msfp_surveyresponse", value);
	}
    public bookableresourcebookingInput? regardingobjectid_bookableresourcebooking_msfp_surveyresponse 
	{
		get => GetValue<bookableresourcebookingInput?>("regardingobjectid_bookableresourcebooking_msfp_surveyresponse");
		set => SetValue("regardingobjectid_bookableresourcebooking_msfp_surveyresponse", value);
	}
    public bookableresourcebookingheaderInput? regardingobjectid_bookableresourcebookingheader_msfp_surveyresponse 
	{
		get => GetValue<bookableresourcebookingheaderInput?>("regardingobjectid_bookableresourcebookingheader_msfp_surveyresponse");
		set => SetValue("regardingobjectid_bookableresourcebookingheader_msfp_surveyresponse", value);
	}
    public bulkoperationInput? regardingobjectid_bulkoperation_msfp_surveyresponse 
	{
		get => GetValue<bulkoperationInput?>("regardingobjectid_bulkoperation_msfp_surveyresponse");
		set => SetValue("regardingobjectid_bulkoperation_msfp_surveyresponse", value);
	}
    public campaignInput? regardingobjectid_campaign_msfp_surveyresponse 
	{
		get => GetValue<campaignInput?>("regardingobjectid_campaign_msfp_surveyresponse");
		set => SetValue("regardingobjectid_campaign_msfp_surveyresponse", value);
	}
    public campaignactivityInput? regardingobjectid_campaignactivity_msfp_surveyresponse 
	{
		get => GetValue<campaignactivityInput?>("regardingobjectid_campaignactivity_msfp_surveyresponse");
		set => SetValue("regardingobjectid_campaignactivity_msfp_surveyresponse", value);
	}
    public contractInput? regardingobjectid_contract_msfp_surveyresponse 
	{
		get => GetValue<contractInput?>("regardingobjectid_contract_msfp_surveyresponse");
		set => SetValue("regardingobjectid_contract_msfp_surveyresponse", value);
	}
    public entitlementInput? regardingobjectid_entitlement_msfp_surveyresponse 
	{
		get => GetValue<entitlementInput?>("regardingobjectid_entitlement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_entitlement_msfp_surveyresponse", value);
	}
    public entitlementtemplateInput? regardingobjectid_entitlementtemplate_msfp_surveyresponse 
	{
		get => GetValue<entitlementtemplateInput?>("regardingobjectid_entitlementtemplate_msfp_surveyresponse");
		set => SetValue("regardingobjectid_entitlementtemplate_msfp_surveyresponse", value);
	}
    public incidentInput? regardingobjectid_incident_msfp_surveyresponse 
	{
		get => GetValue<incidentInput?>("regardingobjectid_incident_msfp_surveyresponse");
		set => SetValue("regardingobjectid_incident_msfp_surveyresponse", value);
	}
    public siteInput? regardingobjectid_site_msfp_surveyresponse 
	{
		get => GetValue<siteInput?>("regardingobjectid_site_msfp_surveyresponse");
		set => SetValue("regardingobjectid_site_msfp_surveyresponse", value);
	}
    public serviceInput? serviceid_msfp_surveyresponse 
	{
		get => GetValue<serviceInput?>("serviceid_msfp_surveyresponse");
		set => SetValue("serviceid_msfp_surveyresponse", value);
	}
    public invoiceInput? regardingobjectid_invoice_msfp_surveyresponse 
	{
		get => GetValue<invoiceInput?>("regardingobjectid_invoice_msfp_surveyresponse");
		set => SetValue("regardingobjectid_invoice_msfp_surveyresponse", value);
	}
    public opportunityInput? regardingobjectid_opportunity_msfp_surveyresponse 
	{
		get => GetValue<opportunityInput?>("regardingobjectid_opportunity_msfp_surveyresponse");
		set => SetValue("regardingobjectid_opportunity_msfp_surveyresponse", value);
	}
    public quoteInput? regardingobjectid_quote_msfp_surveyresponse 
	{
		get => GetValue<quoteInput?>("regardingobjectid_quote_msfp_surveyresponse");
		set => SetValue("regardingobjectid_quote_msfp_surveyresponse", value);
	}
    public salesorderInput? regardingobjectid_salesorder_msfp_surveyresponse 
	{
		get => GetValue<salesorderInput?>("regardingobjectid_salesorder_msfp_surveyresponse");
		set => SetValue("regardingobjectid_salesorder_msfp_surveyresponse", value);
	}
    public msdyn_postalbumInput? regardingobjectid_msdyn_postalbum_msfp_surveyresponse 
	{
		get => GetValue<msdyn_postalbumInput?>("regardingobjectid_msdyn_postalbum_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_postalbum_msfp_surveyresponse", value);
	}
    public msdyn_playbookinstanceInput? regardingobjectid_msdyn_playbookinstance_msfp_surveyresponse 
	{
		get => GetValue<msdyn_playbookinstanceInput?>("regardingobjectid_msdyn_playbookinstance_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_playbookinstance_msfp_surveyresponse", value);
	}
    public interactionforemailInput? regardingobjectid_new_interactionforemail_msfp_surveyresponse 
	{
		get => GetValue<interactionforemailInput?>("regardingobjectid_new_interactionforemail_msfp_surveyresponse");
		set => SetValue("regardingobjectid_new_interactionforemail_msfp_surveyresponse", value);
	}
    public knowledgebaserecordInput? regardingobjectid_knowledgebaserecord_msfp_surveyresponse 
	{
		get => GetValue<knowledgebaserecordInput?>("regardingobjectid_knowledgebaserecord_msfp_surveyresponse");
		set => SetValue("regardingobjectid_knowledgebaserecord_msfp_surveyresponse", value);
	}
    public accountInput? regardingobjectid_account_msfp_surveyresponse 
	{
		get => GetValue<accountInput?>("regardingobjectid_account_msfp_surveyresponse");
		set => SetValue("regardingobjectid_account_msfp_surveyresponse", value);
	}
    public systemuserInput? createdby_msfp_surveyresponse 
	{
		get => GetValue<systemuserInput?>("createdby_msfp_surveyresponse");
		set => SetValue("createdby_msfp_surveyresponse", value);
	}
    public contactInput? regardingobjectid_contact_msfp_surveyresponse 
	{
		get => GetValue<contactInput?>("regardingobjectid_contact_msfp_surveyresponse");
		set => SetValue("regardingobjectid_contact_msfp_surveyresponse", value);
	}
    public mailboxInput? sendermailboxid_msfp_surveyresponse 
	{
		get => GetValue<mailboxInput?>("sendermailboxid_msfp_surveyresponse");
		set => SetValue("sendermailboxid_msfp_surveyresponse", value);
	}
    public transactioncurrencyInput? transactioncurrencyid_msfp_surveyresponse 
	{
		get => GetValue<transactioncurrencyInput?>("transactioncurrencyid_msfp_surveyresponse");
		set => SetValue("transactioncurrencyid_msfp_surveyresponse", value);
	}
    public principalInput? ownerid_msfp_surveyresponse 
	{
		get => GetValue<principalInput?>("ownerid_msfp_surveyresponse");
		set => SetValue("ownerid_msfp_surveyresponse", value);
	}
    public systemuserInput? owninguser_msfp_surveyresponse 
	{
		get => GetValue<systemuserInput?>("owninguser_msfp_surveyresponse");
		set => SetValue("owninguser_msfp_surveyresponse", value);
	}
    public slaInput? sla_activitypointer_sla_msfp_surveyresponse 
	{
		get => GetValue<slaInput?>("sla_activitypointer_sla_msfp_surveyresponse");
		set => SetValue("sla_activitypointer_sla_msfp_surveyresponse", value);
	}
    public businessunitInput? owningbusinessunit_msfp_surveyresponse 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit_msfp_surveyresponse");
		set => SetValue("owningbusinessunit_msfp_surveyresponse", value);
	}
    public knowledgearticleInput? regardingobjectid_knowledgearticle_msfp_surveyresponse 
	{
		get => GetValue<knowledgearticleInput?>("regardingobjectid_knowledgearticle_msfp_surveyresponse");
		set => SetValue("regardingobjectid_knowledgearticle_msfp_surveyresponse", value);
	}
    public systemuserInput? modifiedonbehalfby_msfp_surveyresponse 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby_msfp_surveyresponse");
		set => SetValue("modifiedonbehalfby_msfp_surveyresponse", value);
	}
    public systemuserInput? createdonbehalfby_msfp_surveyresponse 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby_msfp_surveyresponse");
		set => SetValue("createdonbehalfby_msfp_surveyresponse", value);
	}
    public systemuserInput? modifiedby_msfp_surveyresponse 
	{
		get => GetValue<systemuserInput?>("modifiedby_msfp_surveyresponse");
		set => SetValue("modifiedby_msfp_surveyresponse", value);
	}
    public teamInput? owningteam_msfp_surveyresponse 
	{
		get => GetValue<teamInput?>("owningteam_msfp_surveyresponse");
		set => SetValue("owningteam_msfp_surveyresponse", value);
	}
    public slaInput? slainvokedid_activitypointer_sla_msfp_surveyresponse 
	{
		get => GetValue<slaInput?>("slainvokedid_activitypointer_sla_msfp_surveyresponse");
		set => SetValue("slainvokedid_activitypointer_sla_msfp_surveyresponse", value);
	}
    public activitypointerInput? activityid_msfp_surveyresponse 
	{
		get => GetValue<activitypointerInput?>("activityid_msfp_surveyresponse");
		set => SetValue("activityid_msfp_surveyresponse", value);
	}
    public List<activitypartyInput>? msfp_surveyresponse_activity_parties 
	{
		get => GetValue<List<activitypartyInput>?>("msfp_surveyresponse_activity_parties");
		set => SetValue("msfp_surveyresponse_activity_parties", value);
	}
    public List<campaignresponseInput>? CampaignResponse_msfp_surveyresponses 
	{
		get => GetValue<List<campaignresponseInput>?>("CampaignResponse_msfp_surveyresponses");
		set => SetValue("CampaignResponse_msfp_surveyresponses", value);
	}
    public List<actioncardInput>? msfp_surveyresponse_ActionCards 
	{
		get => GetValue<List<actioncardInput>?>("msfp_surveyresponse_ActionCards");
		set => SetValue("msfp_surveyresponse_ActionCards", value);
	}
    public List<syncerrorInput>? msfp_surveyresponse_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msfp_surveyresponse_SyncErrors");
		set => SetValue("msfp_surveyresponse_SyncErrors", value);
	}
    public List<duplicaterecordInput>? msfp_surveyresponse_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msfp_surveyresponse_DuplicateMatchingRecord");
		set => SetValue("msfp_surveyresponse_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? msfp_surveyresponse_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("msfp_surveyresponse_DuplicateBaseRecord");
		set => SetValue("msfp_surveyresponse_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? msfp_surveyresponse_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msfp_surveyresponse_AsyncOperations");
		set => SetValue("msfp_surveyresponse_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msfp_surveyresponse_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msfp_surveyresponse_MailboxTrackingFolders");
		set => SetValue("msfp_surveyresponse_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msfp_surveyresponse_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msfp_surveyresponse_ProcessSession");
		set => SetValue("msfp_surveyresponse_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msfp_surveyresponse_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msfp_surveyresponse_BulkDeleteFailures");
		set => SetValue("msfp_surveyresponse_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msfp_surveyresponse_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msfp_surveyresponse_PrincipalObjectAttributeAccesses");
		set => SetValue("msfp_surveyresponse_PrincipalObjectAttributeAccesses", value);
	}
    public List<connectionInput>? msfp_surveyresponse_connections1 
	{
		get => GetValue<List<connectionInput>?>("msfp_surveyresponse_connections1");
		set => SetValue("msfp_surveyresponse_connections1", value);
	}
    public List<connectionInput>? msfp_surveyresponse_connections2 
	{
		get => GetValue<List<connectionInput>?>("msfp_surveyresponse_connections2");
		set => SetValue("msfp_surveyresponse_connections2", value);
	}
    public List<queueitemInput>? msfp_surveyresponse_QueueItems 
	{
		get => GetValue<List<queueitemInput>?>("msfp_surveyresponse_QueueItems");
		set => SetValue("msfp_surveyresponse_QueueItems", value);
	}
    public List<annotationInput>? msfp_surveyresponse_Annotations 
	{
		get => GetValue<List<annotationInput>?>("msfp_surveyresponse_Annotations");
		set => SetValue("msfp_surveyresponse_Annotations", value);
	}
    public List<feedbackInput>? msfp_surveyresponse_Feedback 
	{
		get => GetValue<List<feedbackInput>?>("msfp_surveyresponse_Feedback");
		set => SetValue("msfp_surveyresponse_Feedback", value);
	}
    public msfp_surveyInput? msfp_surveyid_msfp_surveyresponse 
	{
		get => GetValue<msfp_surveyInput?>("msfp_surveyid_msfp_surveyresponse");
		set => SetValue("msfp_surveyid_msfp_surveyresponse", value);
	}
    public msfp_surveyinviteInput? msfp_surveyinviteid_msfp_surveyresponse 
	{
		get => GetValue<msfp_surveyinviteInput?>("msfp_surveyinviteid_msfp_surveyresponse");
		set => SetValue("msfp_surveyinviteid_msfp_surveyresponse", value);
	}
    public List<msfp_questionresponseInput>? msfp_msfp_surveyresponse_msfp_questionresponse_surveyresponseid 
	{
		get => GetValue<List<msfp_questionresponseInput>?>("msfp_msfp_surveyresponse_msfp_questionresponse_surveyresponseid");
		set => SetValue("msfp_msfp_surveyresponse_msfp_questionresponse_surveyresponseid", value);
	}
    public msdyn_customerassetInput? regardingobjectid_msdyn_customerasset_msfp_surveyresponse 
	{
		get => GetValue<msdyn_customerassetInput?>("regardingobjectid_msdyn_customerasset_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_customerasset_msfp_surveyresponse", value);
	}
    public List<msfp_alertInput>? msfp_msfp_surveyresponse_msfp_alert_surveyresponse 
	{
		get => GetValue<List<msfp_alertInput>?>("msfp_msfp_surveyresponse_msfp_alert_surveyresponse");
		set => SetValue("msfp_msfp_surveyresponse_msfp_alert_surveyresponse", value);
	}
    public msdyn_bookingalertstatusInput? regardingobjectid_msdyn_bookingalertstatus_msfp_surveyresponse 
	{
		get => GetValue<msdyn_bookingalertstatusInput?>("regardingobjectid_msdyn_bookingalertstatus_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_bookingalertstatus_msfp_surveyresponse", value);
	}
    public msdyn_bookingruleInput? regardingobjectid_msdyn_bookingrule_msfp_surveyresponse 
	{
		get => GetValue<msdyn_bookingruleInput?>("regardingobjectid_msdyn_bookingrule_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_bookingrule_msfp_surveyresponse", value);
	}
    public msdyn_resourceterritoryInput? regardingobjectid_msdyn_resourceterritory_msfp_surveyresponse 
	{
		get => GetValue<msdyn_resourceterritoryInput?>("regardingobjectid_msdyn_resourceterritory_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_resourceterritory_msfp_surveyresponse", value);
	}
    public msdyn_systemuserschedulersettingInput? regardingobjectid_msdyn_systemuserschedulersetting_msfp_surveyresponse 
	{
		get => GetValue<msdyn_systemuserschedulersettingInput?>("regardingobjectid_msdyn_systemuserschedulersetting_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_systemuserschedulersetting_msfp_surveyresponse", value);
	}
    public msdyn_timegroupInput? regardingobjectid_msdyn_timegroup_msfp_surveyresponse 
	{
		get => GetValue<msdyn_timegroupInput?>("regardingobjectid_msdyn_timegroup_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_timegroup_msfp_surveyresponse", value);
	}
    public msdyn_timegroupdetailInput? regardingobjectid_msdyn_timegroupdetail_msfp_surveyresponse 
	{
		get => GetValue<msdyn_timegroupdetailInput?>("regardingobjectid_msdyn_timegroupdetail_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_timegroupdetail_msfp_surveyresponse", value);
	}
    public msdyn_agreementInput? regardingobjectid_msdyn_agreement_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementInput?>("regardingobjectid_msdyn_agreement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreement_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingdateInput? regardingobjectid_msdyn_agreementbookingdate_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingdateInput?>("regardingobjectid_msdyn_agreementbookingdate_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingdate_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingincidentInput? regardingobjectid_msdyn_agreementbookingincident_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingincidentInput?>("regardingobjectid_msdyn_agreementbookingincident_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingincident_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingproductInput? regardingobjectid_msdyn_agreementbookingproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingproductInput?>("regardingobjectid_msdyn_agreementbookingproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingproduct_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingserviceInput? regardingobjectid_msdyn_agreementbookingservice_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingserviceInput?>("regardingobjectid_msdyn_agreementbookingservice_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingservice_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingservicetaskInput? regardingobjectid_msdyn_agreementbookingservicetask_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingservicetaskInput?>("regardingobjectid_msdyn_agreementbookingservicetask_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingservicetask_msfp_surveyresponse", value);
	}
    public msdyn_agreementbookingsetupInput? regardingobjectid_msdyn_agreementbookingsetup_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementbookingsetupInput?>("regardingobjectid_msdyn_agreementbookingsetup_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementbookingsetup_msfp_surveyresponse", value);
	}
    public msdyn_agreementinvoicedateInput? regardingobjectid_msdyn_agreementinvoicedate_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementinvoicedateInput?>("regardingobjectid_msdyn_agreementinvoicedate_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementinvoicedate_msfp_surveyresponse", value);
	}
    public msdyn_agreementinvoiceproductInput? regardingobjectid_msdyn_agreementinvoiceproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementinvoiceproductInput?>("regardingobjectid_msdyn_agreementinvoiceproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementinvoiceproduct_msfp_surveyresponse", value);
	}
    public msdyn_agreementinvoicesetupInput? regardingobjectid_msdyn_agreementinvoicesetup_msfp_surveyresponse 
	{
		get => GetValue<msdyn_agreementinvoicesetupInput?>("regardingobjectid_msdyn_agreementinvoicesetup_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_agreementinvoicesetup_msfp_surveyresponse", value);
	}
    public msdyn_bookingtimestampInput? regardingobjectid_msdyn_bookingtimestamp_msfp_surveyresponse 
	{
		get => GetValue<msdyn_bookingtimestampInput?>("regardingobjectid_msdyn_bookingtimestamp_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_bookingtimestamp_msfp_surveyresponse", value);
	}
    public msdyn_fieldservicesettingInput? regardingobjectid_msdyn_fieldservicesetting_msfp_surveyresponse 
	{
		get => GetValue<msdyn_fieldservicesettingInput?>("regardingobjectid_msdyn_fieldservicesetting_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_fieldservicesetting_msfp_surveyresponse", value);
	}
    public msdyn_incidenttypecharacteristicInput? regardingobjectid_msdyn_incidenttypecharacteristic_msfp_surveyresponse 
	{
		get => GetValue<msdyn_incidenttypecharacteristicInput?>("regardingobjectid_msdyn_incidenttypecharacteristic_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_incidenttypecharacteristic_msfp_surveyresponse", value);
	}
    public msdyn_incidenttypeproductInput? regardingobjectid_msdyn_incidenttypeproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_incidenttypeproductInput?>("regardingobjectid_msdyn_incidenttypeproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_incidenttypeproduct_msfp_surveyresponse", value);
	}
    public msdyn_incidenttypeserviceInput? regardingobjectid_msdyn_incidenttypeservice_msfp_surveyresponse 
	{
		get => GetValue<msdyn_incidenttypeserviceInput?>("regardingobjectid_msdyn_incidenttypeservice_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_incidenttypeservice_msfp_surveyresponse", value);
	}
    public msdyn_inventoryadjustmentInput? regardingobjectid_msdyn_inventoryadjustment_msfp_surveyresponse 
	{
		get => GetValue<msdyn_inventoryadjustmentInput?>("regardingobjectid_msdyn_inventoryadjustment_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_inventoryadjustment_msfp_surveyresponse", value);
	}
    public msdyn_inventoryadjustmentproductInput? regardingobjectid_msdyn_inventoryadjustmentproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_inventoryadjustmentproductInput?>("regardingobjectid_msdyn_inventoryadjustmentproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_inventoryadjustmentproduct_msfp_surveyresponse", value);
	}
    public msdyn_inventoryjournalInput? regardingobjectid_msdyn_inventoryjournal_msfp_surveyresponse 
	{
		get => GetValue<msdyn_inventoryjournalInput?>("regardingobjectid_msdyn_inventoryjournal_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_inventoryjournal_msfp_surveyresponse", value);
	}
    public msdyn_inventorytransferInput? regardingobjectid_msdyn_inventorytransfer_msfp_surveyresponse 
	{
		get => GetValue<msdyn_inventorytransferInput?>("regardingobjectid_msdyn_inventorytransfer_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_inventorytransfer_msfp_surveyresponse", value);
	}
    public msdyn_paymentInput? regardingobjectid_msdyn_payment_msfp_surveyresponse 
	{
		get => GetValue<msdyn_paymentInput?>("regardingobjectid_msdyn_payment_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_payment_msfp_surveyresponse", value);
	}
    public msdyn_paymentdetailInput? regardingobjectid_msdyn_paymentdetail_msfp_surveyresponse 
	{
		get => GetValue<msdyn_paymentdetailInput?>("regardingobjectid_msdyn_paymentdetail_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_paymentdetail_msfp_surveyresponse", value);
	}
    public msdyn_paymentmethodInput? regardingobjectid_msdyn_paymentmethod_msfp_surveyresponse 
	{
		get => GetValue<msdyn_paymentmethodInput?>("regardingobjectid_msdyn_paymentmethod_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_paymentmethod_msfp_surveyresponse", value);
	}
    public msdyn_paymenttermInput? regardingobjectid_msdyn_paymentterm_msfp_surveyresponse 
	{
		get => GetValue<msdyn_paymenttermInput?>("regardingobjectid_msdyn_paymentterm_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_paymentterm_msfp_surveyresponse", value);
	}
    public msdyn_postalcodeInput? regardingobjectid_msdyn_postalcode_msfp_surveyresponse 
	{
		get => GetValue<msdyn_postalcodeInput?>("regardingobjectid_msdyn_postalcode_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_postalcode_msfp_surveyresponse", value);
	}
    public msdyn_productinventoryInput? regardingobjectid_msdyn_productinventory_msfp_surveyresponse 
	{
		get => GetValue<msdyn_productinventoryInput?>("regardingobjectid_msdyn_productinventory_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_productinventory_msfp_surveyresponse", value);
	}
    public msdyn_purchaseorderInput? regardingobjectid_msdyn_purchaseorder_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseorderInput?>("regardingobjectid_msdyn_purchaseorder_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseorder_msfp_surveyresponse", value);
	}
    public msdyn_purchaseorderbillInput? regardingobjectid_msdyn_purchaseorderbill_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseorderbillInput?>("regardingobjectid_msdyn_purchaseorderbill_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseorderbill_msfp_surveyresponse", value);
	}
    public msdyn_purchaseorderproductInput? regardingobjectid_msdyn_purchaseorderproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseorderproductInput?>("regardingobjectid_msdyn_purchaseorderproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseorderproduct_msfp_surveyresponse", value);
	}
    public msdyn_purchaseorderreceiptInput? regardingobjectid_msdyn_purchaseorderreceipt_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseorderreceiptInput?>("regardingobjectid_msdyn_purchaseorderreceipt_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseorderreceipt_msfp_surveyresponse", value);
	}
    public msdyn_purchaseorderreceiptproductInput? regardingobjectid_msdyn_purchaseorderreceiptproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseorderreceiptproductInput?>("regardingobjectid_msdyn_purchaseorderreceiptproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseorderreceiptproduct_msfp_surveyresponse", value);
	}
    public msdyn_purchaseordersubstatusInput? regardingobjectid_msdyn_purchaseordersubstatus_msfp_surveyresponse 
	{
		get => GetValue<msdyn_purchaseordersubstatusInput?>("regardingobjectid_msdyn_purchaseordersubstatus_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_purchaseordersubstatus_msfp_surveyresponse", value);
	}
    public msdyn_quotebookingincidentInput? regardingobjectid_msdyn_quotebookingincident_msfp_surveyresponse 
	{
		get => GetValue<msdyn_quotebookingincidentInput?>("regardingobjectid_msdyn_quotebookingincident_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_quotebookingincident_msfp_surveyresponse", value);
	}
    public msdyn_quotebookingproductInput? regardingobjectid_msdyn_quotebookingproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_quotebookingproductInput?>("regardingobjectid_msdyn_quotebookingproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_quotebookingproduct_msfp_surveyresponse", value);
	}
    public msdyn_quotebookingserviceInput? regardingobjectid_msdyn_quotebookingservice_msfp_surveyresponse 
	{
		get => GetValue<msdyn_quotebookingserviceInput?>("regardingobjectid_msdyn_quotebookingservice_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_quotebookingservice_msfp_surveyresponse", value);
	}
    public msdyn_quotebookingservicetaskInput? regardingobjectid_msdyn_quotebookingservicetask_msfp_surveyresponse 
	{
		get => GetValue<msdyn_quotebookingservicetaskInput?>("regardingobjectid_msdyn_quotebookingservicetask_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_quotebookingservicetask_msfp_surveyresponse", value);
	}
    public msdyn_rmaInput? regardingobjectid_msdyn_rma_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rmaInput?>("regardingobjectid_msdyn_rma_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rma_msfp_surveyresponse", value);
	}
    public msdyn_rmaproductInput? regardingobjectid_msdyn_rmaproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rmaproductInput?>("regardingobjectid_msdyn_rmaproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rmaproduct_msfp_surveyresponse", value);
	}
    public msdyn_rmareceiptInput? regardingobjectid_msdyn_rmareceipt_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rmareceiptInput?>("regardingobjectid_msdyn_rmareceipt_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rmareceipt_msfp_surveyresponse", value);
	}
    public msdyn_rmareceiptproductInput? regardingobjectid_msdyn_rmareceiptproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rmareceiptproductInput?>("regardingobjectid_msdyn_rmareceiptproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rmareceiptproduct_msfp_surveyresponse", value);
	}
    public msdyn_rmasubstatusInput? regardingobjectid_msdyn_rmasubstatus_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rmasubstatusInput?>("regardingobjectid_msdyn_rmasubstatus_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rmasubstatus_msfp_surveyresponse", value);
	}
    public msdyn_rtvInput? regardingobjectid_msdyn_rtv_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rtvInput?>("regardingobjectid_msdyn_rtv_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rtv_msfp_surveyresponse", value);
	}
    public msdyn_rtvproductInput? regardingobjectid_msdyn_rtvproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rtvproductInput?>("regardingobjectid_msdyn_rtvproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rtvproduct_msfp_surveyresponse", value);
	}
    public msdyn_rtvsubstatusInput? regardingobjectid_msdyn_rtvsubstatus_msfp_surveyresponse 
	{
		get => GetValue<msdyn_rtvsubstatusInput?>("regardingobjectid_msdyn_rtvsubstatus_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_rtvsubstatus_msfp_surveyresponse", value);
	}
    public msdyn_shipviaInput? regardingobjectid_msdyn_shipvia_msfp_surveyresponse 
	{
		get => GetValue<msdyn_shipviaInput?>("regardingobjectid_msdyn_shipvia_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_shipvia_msfp_surveyresponse", value);
	}
    public msdyn_timeoffrequestInput? regardingobjectid_msdyn_timeoffrequest_msfp_surveyresponse 
	{
		get => GetValue<msdyn_timeoffrequestInput?>("regardingobjectid_msdyn_timeoffrequest_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_timeoffrequest_msfp_surveyresponse", value);
	}
    public msdyn_warehouseInput? regardingobjectid_msdyn_warehouse_msfp_surveyresponse 
	{
		get => GetValue<msdyn_warehouseInput?>("regardingobjectid_msdyn_warehouse_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_warehouse_msfp_surveyresponse", value);
	}
    public msdyn_workorderInput? regardingobjectid_msdyn_workorder_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderInput?>("regardingobjectid_msdyn_workorder_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorder_msfp_surveyresponse", value);
	}
    public msdyn_workordercharacteristicInput? regardingobjectid_msdyn_workordercharacteristic_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workordercharacteristicInput?>("regardingobjectid_msdyn_workordercharacteristic_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workordercharacteristic_msfp_surveyresponse", value);
	}
    public msdyn_workorderincidentInput? regardingobjectid_msdyn_workorderincident_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderincidentInput?>("regardingobjectid_msdyn_workorderincident_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorderincident_msfp_surveyresponse", value);
	}
    public msdyn_workorderproductInput? regardingobjectid_msdyn_workorderproduct_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderproductInput?>("regardingobjectid_msdyn_workorderproduct_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorderproduct_msfp_surveyresponse", value);
	}
    public msdyn_workorderresourcerestrictionInput? regardingobjectid_msdyn_workorderresourcerestriction_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderresourcerestrictionInput?>("regardingobjectid_msdyn_workorderresourcerestriction_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorderresourcerestriction_msfp_surveyresponse", value);
	}
    public msdyn_workorderserviceInput? regardingobjectid_msdyn_workorderservice_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderserviceInput?>("regardingobjectid_msdyn_workorderservice_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorderservice_msfp_surveyresponse", value);
	}
    public msdyn_workorderservicetaskInput? regardingobjectid_msdyn_workorderservicetask_msfp_surveyresponse 
	{
		get => GetValue<msdyn_workorderservicetaskInput?>("regardingobjectid_msdyn_workorderservicetask_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_workorderservicetask_msfp_surveyresponse", value);
	}
    public adx_webpageInput? regardingobjectid_adx_webpage_msfp_surveyresponse 
	{
		get => GetValue<adx_webpageInput?>("regardingobjectid_adx_webpage_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_webpage_msfp_surveyresponse", value);
	}
    public adx_websiteInput? regardingobjectid_adx_website_msfp_surveyresponse 
	{
		get => GetValue<adx_websiteInput?>("regardingobjectid_adx_website_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_website_msfp_surveyresponse", value);
	}
    public adx_adInput? regardingobjectid_adx_ad_msfp_surveyresponse 
	{
		get => GetValue<adx_adInput?>("regardingobjectid_adx_ad_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_ad_msfp_surveyresponse", value);
	}
    public adx_adplacementInput? regardingobjectid_adx_adplacement_msfp_surveyresponse 
	{
		get => GetValue<adx_adplacementInput?>("regardingobjectid_adx_adplacement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_adplacement_msfp_surveyresponse", value);
	}
    public adx_invitationInput? regardingobjectid_adx_invitation_msfp_surveyresponse 
	{
		get => GetValue<adx_invitationInput?>("regardingobjectid_adx_invitation_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_invitation_msfp_surveyresponse", value);
	}
    public adx_pollInput? regardingobjectid_adx_poll_msfp_surveyresponse 
	{
		get => GetValue<adx_pollInput?>("regardingobjectid_adx_poll_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_poll_msfp_surveyresponse", value);
	}
    public adx_polloptionInput? regardingobjectid_adx_polloption_msfp_surveyresponse 
	{
		get => GetValue<adx_polloptionInput?>("regardingobjectid_adx_polloption_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_polloption_msfp_surveyresponse", value);
	}
    public adx_pollplacementInput? regardingobjectid_adx_pollplacement_msfp_surveyresponse 
	{
		get => GetValue<adx_pollplacementInput?>("regardingobjectid_adx_pollplacement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_pollplacement_msfp_surveyresponse", value);
	}
    public adx_pollsubmissionInput? regardingobjectid_adx_pollsubmission_msfp_surveyresponse 
	{
		get => GetValue<adx_pollsubmissionInput?>("regardingobjectid_adx_pollsubmission_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_pollsubmission_msfp_surveyresponse", value);
	}
    public adx_publishingstatetransitionruleInput? regardingobjectid_adx_publishingstatetransitionrule_msfp_surveyresponse 
	{
		get => GetValue<adx_publishingstatetransitionruleInput?>("regardingobjectid_adx_publishingstatetransitionrule_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_publishingstatetransitionrule_msfp_surveyresponse", value);
	}
    public adx_redirectInput? regardingobjectid_adx_redirect_msfp_surveyresponse 
	{
		get => GetValue<adx_redirectInput?>("regardingobjectid_adx_redirect_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_redirect_msfp_surveyresponse", value);
	}
    public adx_shortcutInput? regardingobjectid_adx_shortcut_msfp_surveyresponse 
	{
		get => GetValue<adx_shortcutInput?>("regardingobjectid_adx_shortcut_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_shortcut_msfp_surveyresponse", value);
	}
    public adx_communityforumaccesspermissionInput? regardingobjectid_adx_communityforumaccesspermission_msfp_surveyresponse 
	{
		get => GetValue<adx_communityforumaccesspermissionInput?>("regardingobjectid_adx_communityforumaccesspermission_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_communityforumaccesspermission_msfp_surveyresponse", value);
	}
    public adx_communityforumalertInput? regardingobjectid_adx_communityforumalert_msfp_surveyresponse 
	{
		get => GetValue<adx_communityforumalertInput?>("regardingobjectid_adx_communityforumalert_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_communityforumalert_msfp_surveyresponse", value);
	}
    public adx_casedeflectionInput? regardingobjectid_adx_casedeflection_msfp_surveyresponse 
	{
		get => GetValue<adx_casedeflectionInput?>("regardingobjectid_adx_casedeflection_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_casedeflection_msfp_surveyresponse", value);
	}
    public adx_contentaccesslevelInput? regardingobjectid_adx_contentaccesslevel_msfp_surveyresponse 
	{
		get => GetValue<adx_contentaccesslevelInput?>("regardingobjectid_adx_contentaccesslevel_msfp_surveyresponse");
		set => SetValue("regardingobjectid_adx_contentaccesslevel_msfp_surveyresponse", value);
	}
    public msfp_surveyresponseInput? msfp_parent_survey_response_new_msfp_surveyresponse 
	{
		get => GetValue<msfp_surveyresponseInput?>("msfp_parent_survey_response_new_msfp_surveyresponse");
		set => SetValue("msfp_parent_survey_response_new_msfp_surveyresponse", value);
	}
    public List<msfp_surveyresponseInput>? msfp_msfp_surveyresponse_msfp_surveyresponse_parent_survey_response_new 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("msfp_msfp_surveyresponse_msfp_surveyresponse_parent_survey_response_new");
		set => SetValue("msfp_msfp_surveyresponse_msfp_surveyresponse_parent_survey_response_new", value);
	}
    public msdyn_salessuggestionInput? regardingobjectid_msdyn_salessuggestion_msfp_surveyresponse 
	{
		get => GetValue<msdyn_salessuggestionInput?>("regardingobjectid_msdyn_salessuggestion_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_salessuggestion_msfp_surveyresponse", value);
	}
    public msfp_surveyresponseInput? msfp_parentsurveyresponse_msfp_surveyresponse 
	{
		get => GetValue<msfp_surveyresponseInput?>("msfp_parentsurveyresponse_msfp_surveyresponse");
		set => SetValue("msfp_parentsurveyresponse_msfp_surveyresponse", value);
	}
    public List<msfp_surveyresponseInput>? msfp_msfp_surveyresponse_msfp_surveyresponse_parentsurveyresponse 
	{
		get => GetValue<List<msfp_surveyresponseInput>?>("msfp_msfp_surveyresponse_msfp_surveyresponse_parentsurveyresponse");
		set => SetValue("msfp_msfp_surveyresponse_msfp_surveyresponse_parentsurveyresponse", value);
	}
    public msdyn_swarmInput? regardingobjectid_msdyn_swarm_msfp_surveyresponse 
	{
		get => GetValue<msdyn_swarmInput?>("regardingobjectid_msdyn_swarm_msfp_surveyresponse");
		set => SetValue("regardingobjectid_msdyn_swarm_msfp_surveyresponse", value);
	}
    public zync_accountplanInput? regardingobjectid_zync_accountplan_msfp_surveyresponse 
	{
		get => GetValue<zync_accountplanInput?>("regardingobjectid_zync_accountplan_msfp_surveyresponse");
		set => SetValue("regardingobjectid_zync_accountplan_msfp_surveyresponse", value);
	}
    public mspp_adplacementInput? regardingobjectid_mspp_adplacement_msfp_surveyresponse 
	{
		get => GetValue<mspp_adplacementInput?>("regardingobjectid_mspp_adplacement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_adplacement_msfp_surveyresponse", value);
	}
    public mspp_pollplacementInput? regardingobjectid_mspp_pollplacement_msfp_surveyresponse 
	{
		get => GetValue<mspp_pollplacementInput?>("regardingobjectid_mspp_pollplacement_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_pollplacement_msfp_surveyresponse", value);
	}
    public mspp_publishingstatetransitionruleInput? regardingobjectid_mspp_publishingstatetransitionrule_msfp_surveyresponse 
	{
		get => GetValue<mspp_publishingstatetransitionruleInput?>("regardingobjectid_mspp_publishingstatetransitionrule_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_publishingstatetransitionrule_msfp_surveyresponse", value);
	}
    public mspp_redirectInput? regardingobjectid_mspp_redirect_msfp_surveyresponse 
	{
		get => GetValue<mspp_redirectInput?>("regardingobjectid_mspp_redirect_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_redirect_msfp_surveyresponse", value);
	}
    public mspp_shortcutInput? regardingobjectid_mspp_shortcut_msfp_surveyresponse 
	{
		get => GetValue<mspp_shortcutInput?>("regardingobjectid_mspp_shortcut_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_shortcut_msfp_surveyresponse", value);
	}
    public mspp_websiteInput? regardingobjectid_mspp_website_msfp_surveyresponse 
	{
		get => GetValue<mspp_websiteInput?>("regardingobjectid_mspp_website_msfp_surveyresponse");
		set => SetValue("regardingobjectid_mspp_website_msfp_surveyresponse", value);
	}
    public zync_projectphaseInput? regardingobjectid_zync_projectphase_msfp_surveyresponse 
	{
		get => GetValue<zync_projectphaseInput?>("regardingobjectid_zync_projectphase_msfp_surveyresponse");
		set => SetValue("regardingobjectid_zync_projectphase_msfp_surveyresponse", value);
	}

}
