// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: msgraphresourcetosubscription
/// </summary>
public partial class msgraphresourcetosubscriptionInput : ODataInputBase
{
	// IsEnumType: False
    public string? resourceid 
	{
		get => GetValue<string?>("resourceid");
		set => SetValue("resourceid", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? msgraphresourcetosubscriptionid 
	{
		get => GetValue<Guid?>("msgraphresourcetosubscriptionid");
		set => SetValue("msgraphresourcetosubscriptionid", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdingraphon 
	{
		get => GetValue<DateTimeOffset?>("createdingraphon");
		set => SetValue("createdingraphon", value);
	}
	// IsEnumType: False
    public int? resourcetype 
	{
		get => GetValue<int?>("resourcetype");
		set => SetValue("resourcetype", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public string? subscriptionid 
	{
		get => GetValue<string?>("subscriptionid");
		set => SetValue("subscriptionid", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}

    //Navigations
    public List<syncerrorInput>? msgraphresourcetosubscription_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("msgraphresourcetosubscription_SyncErrors");
		set => SetValue("msgraphresourcetosubscription_SyncErrors", value);
	}
    public List<asyncoperationInput>? msgraphresourcetosubscription_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("msgraphresourcetosubscription_AsyncOperations");
		set => SetValue("msgraphresourcetosubscription_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? msgraphresourcetosubscription_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("msgraphresourcetosubscription_MailboxTrackingFolders");
		set => SetValue("msgraphresourcetosubscription_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? msgraphresourcetosubscription_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("msgraphresourcetosubscription_ProcessSession");
		set => SetValue("msgraphresourcetosubscription_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? msgraphresourcetosubscription_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("msgraphresourcetosubscription_BulkDeleteFailures");
		set => SetValue("msgraphresourcetosubscription_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? msgraphresourcetosubscription_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("msgraphresourcetosubscription_PrincipalObjectAttributeAccesses");
		set => SetValue("msgraphresourcetosubscription_PrincipalObjectAttributeAccesses", value);
	}

}
