// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: mspp_columnpermission
/// </summary>
public partial class mspp_columnpermissionInput : ODataInputBase
{
	// IsEnumType: False
    public string? mspp_permissions 
	{
		get => GetValue<string?>("mspp_permissions");
		set => SetValue("mspp_permissions", value);
	}
	// IsEnumType: False
    public DateTimeOffset? mspp_modifiedon 
	{
		get => GetValue<DateTimeOffset?>("mspp_modifiedon");
		set => SetValue("mspp_modifiedon", value);
	}
	// IsEnumType: False
    public Guid? mspp_columnpermissionid 
	{
		get => GetValue<Guid?>("mspp_columnpermissionid");
		set => SetValue("mspp_columnpermissionid", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _mspp_modifiedby_value 
	{
		get => GetValue<Guid?>("_mspp_modifiedby_value");
		set => SetValue("_mspp_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _mspp_createdby_value 
	{
		get => GetValue<Guid?>("_mspp_createdby_value");
		set => SetValue("_mspp_createdby_value", value);
	}
	// IsEnumType: False
    public string? mspp_columnname 
	{
		get => GetValue<string?>("mspp_columnname");
		set => SetValue("mspp_columnname", value);
	}
	// IsEnumType: False
    public DateTimeOffset? mspp_createdon 
	{
		get => GetValue<DateTimeOffset?>("mspp_createdon");
		set => SetValue("mspp_createdon", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public Guid? _mspp_columnpermissionprofileid_value 
	{
		get => GetValue<Guid?>("_mspp_columnpermissionprofileid_value");
		set => SetValue("_mspp_columnpermissionprofileid_value", value);
	}

    //Navigations
    public mspp_columnpermissionprofileInput? mspp_columnpermissionprofileid 
	{
		get => GetValue<mspp_columnpermissionprofileInput?>("mspp_columnpermissionprofileid");
		set => SetValue("mspp_columnpermissionprofileid", value);
	}
    public systemuserInput? mspp_createdby 
	{
		get => GetValue<systemuserInput?>("mspp_createdby");
		set => SetValue("mspp_createdby", value);
	}
    public systemuserInput? mspp_modifiedby 
	{
		get => GetValue<systemuserInput?>("mspp_modifiedby");
		set => SetValue("mspp_modifiedby", value);
	}

}
