// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: powerbimashupparameter
/// </summary>
public partial class powerbimashupparameterInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? _owninguser_value 
	{
		get => GetValue<Guid?>("_owninguser_value");
		set => SetValue("_owninguser_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public Guid? _datasetid_value 
	{
		get => GetValue<Guid?>("_datasetid_value");
		set => SetValue("_datasetid_value", value);
	}
	// IsEnumType: False
    public string? parameterliteralvalue 
	{
		get => GetValue<string?>("parameterliteralvalue");
		set => SetValue("parameterliteralvalue", value);
	}
	// IsEnumType: False
    public BooleanManagedPropertyInput? iscustomizable 
	{
		get => GetValue<BooleanManagedPropertyInput?>("iscustomizable");
		set => SetValue("iscustomizable", value);
	}
	// IsEnumType: False
    public Guid? _ownerid_value 
	{
		get => GetValue<Guid?>("_ownerid_value");
		set => SetValue("_ownerid_value", value);
	}
	// IsEnumType: False
    public string? uniquename 
	{
		get => GetValue<string?>("uniquename");
		set => SetValue("uniquename", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public Guid? componentidunique 
	{
		get => GetValue<Guid?>("componentidunique");
		set => SetValue("componentidunique", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public int? parametervaluesource 
	{
		get => GetValue<int?>("parametervaluesource");
		set => SetValue("parametervaluesource", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overwritetime 
	{
		get => GetValue<DateTimeOffset?>("overwritetime");
		set => SetValue("overwritetime", value);
	}
	// IsEnumType: False
    public bool? ismanaged 
	{
		get => GetValue<bool?>("ismanaged");
		set => SetValue("ismanaged", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public string? parametername 
	{
		get => GetValue<string?>("parametername");
		set => SetValue("parametername", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? componentstate 
	{
		get => GetValue<int?>("componentstate");
		set => SetValue("componentstate", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _owningteam_value 
	{
		get => GetValue<Guid?>("_owningteam_value");
		set => SetValue("_owningteam_value", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? _environmentvariableid_value 
	{
		get => GetValue<Guid?>("_environmentvariableid_value");
		set => SetValue("_environmentvariableid_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? powerbimashupparameterid 
	{
		get => GetValue<Guid?>("powerbimashupparameterid");
		set => SetValue("powerbimashupparameterid", value);
	}
	// IsEnumType: False
    public Guid? _owningbusinessunit_value 
	{
		get => GetValue<Guid?>("_owningbusinessunit_value");
		set => SetValue("_owningbusinessunit_value", value);
	}
	// IsEnumType: False
    public bool? isnotrequired 
	{
		get => GetValue<bool?>("isnotrequired");
		set => SetValue("isnotrequired", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public systemuserInput? owninguser 
	{
		get => GetValue<systemuserInput?>("owninguser");
		set => SetValue("owninguser", value);
	}
    public teamInput? owningteam 
	{
		get => GetValue<teamInput?>("owningteam");
		set => SetValue("owningteam", value);
	}
    public principalInput? ownerid 
	{
		get => GetValue<principalInput?>("ownerid");
		set => SetValue("ownerid", value);
	}
    public businessunitInput? owningbusinessunit 
	{
		get => GetValue<businessunitInput?>("owningbusinessunit");
		set => SetValue("owningbusinessunit", value);
	}
    public List<syncerrorInput>? powerbimashupparameter_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("powerbimashupparameter_SyncErrors");
		set => SetValue("powerbimashupparameter_SyncErrors", value);
	}
    public List<duplicaterecordInput>? powerbimashupparameter_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("powerbimashupparameter_DuplicateMatchingRecord");
		set => SetValue("powerbimashupparameter_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? powerbimashupparameter_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("powerbimashupparameter_DuplicateBaseRecord");
		set => SetValue("powerbimashupparameter_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? powerbimashupparameter_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("powerbimashupparameter_AsyncOperations");
		set => SetValue("powerbimashupparameter_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? powerbimashupparameter_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("powerbimashupparameter_MailboxTrackingFolders");
		set => SetValue("powerbimashupparameter_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? powerbimashupparameter_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("powerbimashupparameter_ProcessSession");
		set => SetValue("powerbimashupparameter_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? powerbimashupparameter_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("powerbimashupparameter_BulkDeleteFailures");
		set => SetValue("powerbimashupparameter_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? powerbimashupparameter_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("powerbimashupparameter_PrincipalObjectAttributeAccesses");
		set => SetValue("powerbimashupparameter_PrincipalObjectAttributeAccesses", value);
	}
    public environmentvariabledefinitionInput? EnvironmentVariableId 
	{
		get => GetValue<environmentvariabledefinitionInput?>("EnvironmentVariableId");
		set => SetValue("EnvironmentVariableId", value);
	}
    public powerbidatasetInput? DatasetId 
	{
		get => GetValue<powerbidatasetInput?>("DatasetId");
		set => SetValue("DatasetId", value);
	}

}
