// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: principalentitybusinessunitmap
/// </summary>
public partial class principalentitybusinessunitmapInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? principalid 
	{
		get => GetValue<Guid?>("principalid");
		set => SetValue("principalid", value);
	}
	// IsEnumType: False
    public string? objecttypecode 
	{
		get => GetValue<string?>("objecttypecode");
		set => SetValue("objecttypecode", value);
	}
	// IsEnumType: False
    public Guid? principalentitybusinessunitmapid 
	{
		get => GetValue<Guid?>("principalentitybusinessunitmapid");
		set => SetValue("principalentitybusinessunitmapid", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public Guid? businessunitid 
	{
		get => GetValue<Guid?>("businessunitid");
		set => SetValue("businessunitid", value);
	}

    //Navigations
    public businessunitInput? businessunitid_businessunit 
	{
		get => GetValue<businessunitInput?>("businessunitid_businessunit");
		set => SetValue("businessunitid_businessunit", value);
	}
    public principalInput? principalid_owner 
	{
		get => GetValue<principalInput?>("principalid_owner");
		set => SetValue("principalid_owner", value);
	}

}
