// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: ribbonmetadatatoprocess
/// </summary>
public partial class ribbonmetadatatoprocessInput : ODataInputBase
{
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? exceptionmessage 
	{
		get => GetValue<string?>("exceptionmessage");
		set => SetValue("exceptionmessage", value);
	}
	// IsEnumType: False
    public int? isdbupdate 
	{
		get => GetValue<int?>("isdbupdate");
		set => SetValue("isdbupdate", value);
	}
	// IsEnumType: False
    public string? solutionname 
	{
		get => GetValue<string?>("solutionname");
		set => SetValue("solutionname", value);
	}
	// IsEnumType: False
    public DateTimeOffset? processedon 
	{
		get => GetValue<DateTimeOffset?>("processedon");
		set => SetValue("processedon", value);
	}
	// IsEnumType: False
    public int? retrycount 
	{
		get => GetValue<int?>("retrycount");
		set => SetValue("retrycount", value);
	}
	// IsEnumType: False
    public string? entityname 
	{
		get => GetValue<string?>("entityname");
		set => SetValue("entityname", value);
	}
	// IsEnumType: False
    public DateTimeOffset? completedon 
	{
		get => GetValue<DateTimeOffset?>("completedon");
		set => SetValue("completedon", value);
	}
	// IsEnumType: False
    public int? status 
	{
		get => GetValue<int?>("status");
		set => SetValue("status", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public Guid? ribbonmetadatarowid 
	{
		get => GetValue<Guid?>("ribbonmetadatarowid");
		set => SetValue("ribbonmetadatarowid", value);
	}

    //Navigations

}
