// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: roleprivileges
/// </summary>
public partial class roleprivilegesInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? privilegeid 
	{
		get => GetValue<Guid?>("privilegeid");
		set => SetValue("privilegeid", value);
	}
	// IsEnumType: False
    public Guid? roleid 
	{
		get => GetValue<Guid?>("roleid");
		set => SetValue("roleid", value);
	}
	// IsEnumType: False
    public int? privilegedepthmask 
	{
		get => GetValue<int?>("privilegedepthmask");
		set => SetValue("privilegedepthmask", value);
	}
	// IsEnumType: False
    public bool? ismanaged 
	{
		get => GetValue<bool?>("ismanaged");
		set => SetValue("ismanaged", value);
	}
	// IsEnumType: False
    public BooleanManagedPropertyInput? canbedeleted 
	{
		get => GetValue<BooleanManagedPropertyInput?>("canbedeleted");
		set => SetValue("canbedeleted", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overwritetime 
	{
		get => GetValue<DateTimeOffset?>("overwritetime");
		set => SetValue("overwritetime", value);
	}
	// IsEnumType: False
    public Guid? roleprivilegeid 
	{
		get => GetValue<Guid?>("roleprivilegeid");
		set => SetValue("roleprivilegeid", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public int? componentstate 
	{
		get => GetValue<int?>("componentstate");
		set => SetValue("componentstate", value);
	}
	// IsEnumType: False
    public Guid? roleprivilegeidunique 
	{
		get => GetValue<Guid?>("roleprivilegeidunique");
		set => SetValue("roleprivilegeidunique", value);
	}
	// IsEnumType: False
    public Guid? _recordfilterid_value 
	{
		get => GetValue<Guid?>("_recordfilterid_value");
		set => SetValue("_recordfilterid_value", value);
	}

    //Navigations
    public recordfilterInput? RecordFilterId 
	{
		get => GetValue<recordfilterInput?>("RecordFilterId");
		set => SetValue("RecordFilterId", value);
	}

}
