// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: solutioncomponentattributeconfiguration
/// </summary>
public partial class solutioncomponentattributeconfigurationInput : ODataInputBase
{
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public string? fileextension 
	{
		get => GetValue<string?>("fileextension");
		set => SetValue("fileextension", value);
	}
	// IsEnumType: False
    public int? encodingformat 
	{
		get => GetValue<int?>("encodingformat");
		set => SetValue("encodingformat", value);
	}
	// IsEnumType: False
    public int? componentstate 
	{
		get => GetValue<int?>("componentstate");
		set => SetValue("componentstate", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public BooleanManagedPropertyInput? iscustomizable 
	{
		get => GetValue<BooleanManagedPropertyInput?>("iscustomizable");
		set => SetValue("iscustomizable", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public bool? invokesubstitutionforattribute 
	{
		get => GetValue<bool?>("invokesubstitutionforattribute");
		set => SetValue("invokesubstitutionforattribute", value);
	}
	// IsEnumType: False
    public string? name 
	{
		get => GetValue<string?>("name");
		set => SetValue("name", value);
	}
	// IsEnumType: False
    public bool? ismanaged 
	{
		get => GetValue<bool?>("ismanaged");
		set => SetValue("ismanaged", value);
	}
	// IsEnumType: False
    public int? dependencyremovalcapability 
	{
		get => GetValue<int?>("dependencyremovalcapability");
		set => SetValue("dependencyremovalcapability", value);
	}
	// IsEnumType: False
    public int? utcconversiontimezonecode 
	{
		get => GetValue<int?>("utcconversiontimezonecode");
		set => SetValue("utcconversiontimezonecode", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overriddencreatedon 
	{
		get => GetValue<DateTimeOffset?>("overriddencreatedon");
		set => SetValue("overriddencreatedon", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public Guid? _organizationid_value 
	{
		get => GetValue<Guid?>("_organizationid_value");
		set => SetValue("_organizationid_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? overwritetime 
	{
		get => GetValue<DateTimeOffset?>("overwritetime");
		set => SetValue("overwritetime", value);
	}
	// IsEnumType: False
    public int? custommanagedbehaviortype 
	{
		get => GetValue<int?>("custommanagedbehaviortype");
		set => SetValue("custommanagedbehaviortype", value);
	}
	// IsEnumType: False
    public bool? isexportdisabled 
	{
		get => GetValue<bool?>("isexportdisabled");
		set => SetValue("isexportdisabled", value);
	}
	// IsEnumType: False
    public Guid? _solutioncomponentconfigurationid_value 
	{
		get => GetValue<Guid?>("_solutioncomponentconfigurationid_value");
		set => SetValue("_solutioncomponentconfigurationid_value", value);
	}
	// IsEnumType: False
    public bool? isprefixedbytemplate 
	{
		get => GetValue<bool?>("isprefixedbytemplate");
		set => SetValue("isprefixedbytemplate", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}
	// IsEnumType: False
    public int? statuscode 
	{
		get => GetValue<int?>("statuscode");
		set => SetValue("statuscode", value);
	}
	// IsEnumType: False
    public int? importsequencenumber 
	{
		get => GetValue<int?>("importsequencenumber");
		set => SetValue("importsequencenumber", value);
	}
	// IsEnumType: False
    public int? statecode 
	{
		get => GetValue<int?>("statecode");
		set => SetValue("statecode", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public Guid? componentidunique 
	{
		get => GetValue<Guid?>("componentidunique");
		set => SetValue("componentidunique", value);
	}
	// IsEnumType: False
    public Guid? solutionid 
	{
		get => GetValue<Guid?>("solutionid");
		set => SetValue("solutionid", value);
	}
	// IsEnumType: False
    public bool? isexportedasfile 
	{
		get => GetValue<bool?>("isexportedasfile");
		set => SetValue("isexportedasfile", value);
	}
	// IsEnumType: False
    public Guid? solutioncomponentattributeconfigurationid 
	{
		get => GetValue<Guid?>("solutioncomponentattributeconfigurationid");
		set => SetValue("solutioncomponentattributeconfigurationid", value);
	}
	// IsEnumType: False
    public Guid? _attributeid_value 
	{
		get => GetValue<Guid?>("_attributeid_value");
		set => SetValue("_attributeid_value", value);
	}
	// IsEnumType: False
    public int? timezoneruleversionnumber 
	{
		get => GetValue<int?>("timezoneruleversionnumber");
		set => SetValue("timezoneruleversionnumber", value);
	}
	// IsEnumType: False
    public bool? isenabledfordependencyextraction 
	{
		get => GetValue<bool?>("isenabledfordependencyextraction");
		set => SetValue("isenabledfordependencyextraction", value);
	}

    //Navigations
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public organizationInput? organizationid 
	{
		get => GetValue<organizationInput?>("organizationid");
		set => SetValue("organizationid", value);
	}
    public List<syncerrorInput>? solutioncomponentattributeconfiguration_SyncErrors 
	{
		get => GetValue<List<syncerrorInput>?>("solutioncomponentattributeconfiguration_SyncErrors");
		set => SetValue("solutioncomponentattributeconfiguration_SyncErrors", value);
	}
    public List<duplicaterecordInput>? solutioncomponentattributeconfiguration_DuplicateMatchingRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("solutioncomponentattributeconfiguration_DuplicateMatchingRecord");
		set => SetValue("solutioncomponentattributeconfiguration_DuplicateMatchingRecord", value);
	}
    public List<duplicaterecordInput>? solutioncomponentattributeconfiguration_DuplicateBaseRecord 
	{
		get => GetValue<List<duplicaterecordInput>?>("solutioncomponentattributeconfiguration_DuplicateBaseRecord");
		set => SetValue("solutioncomponentattributeconfiguration_DuplicateBaseRecord", value);
	}
    public List<asyncoperationInput>? solutioncomponentattributeconfiguration_AsyncOperations 
	{
		get => GetValue<List<asyncoperationInput>?>("solutioncomponentattributeconfiguration_AsyncOperations");
		set => SetValue("solutioncomponentattributeconfiguration_AsyncOperations", value);
	}
    public List<mailboxtrackingfolderInput>? solutioncomponentattributeconfiguration_MailboxTrackingFolders 
	{
		get => GetValue<List<mailboxtrackingfolderInput>?>("solutioncomponentattributeconfiguration_MailboxTrackingFolders");
		set => SetValue("solutioncomponentattributeconfiguration_MailboxTrackingFolders", value);
	}
    public List<processsessionInput>? solutioncomponentattributeconfiguration_ProcessSession 
	{
		get => GetValue<List<processsessionInput>?>("solutioncomponentattributeconfiguration_ProcessSession");
		set => SetValue("solutioncomponentattributeconfiguration_ProcessSession", value);
	}
    public List<bulkdeletefailureInput>? solutioncomponentattributeconfiguration_BulkDeleteFailures 
	{
		get => GetValue<List<bulkdeletefailureInput>?>("solutioncomponentattributeconfiguration_BulkDeleteFailures");
		set => SetValue("solutioncomponentattributeconfiguration_BulkDeleteFailures", value);
	}
    public List<principalobjectattributeaccessInput>? solutioncomponentattributeconfiguration_PrincipalObjectAttributeAccesses 
	{
		get => GetValue<List<principalobjectattributeaccessInput>?>("solutioncomponentattributeconfiguration_PrincipalObjectAttributeAccesses");
		set => SetValue("solutioncomponentattributeconfiguration_PrincipalObjectAttributeAccesses", value);
	}
    public attributeInput? AttributeId 
	{
		get => GetValue<attributeInput?>("AttributeId");
		set => SetValue("AttributeId", value);
	}
    public solutioncomponentconfigurationInput? solutioncomponentconfigurationid 
	{
		get => GetValue<solutioncomponentconfigurationInput?>("solutioncomponentconfigurationid");
		set => SetValue("solutioncomponentconfigurationid", value);
	}

}
