// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: subscriptionstatisticsoutlook
/// </summary>
public partial class subscriptionstatisticsoutlookInput : ODataInputBase
{
	// IsEnumType: False
    public bool? fullsyncrequired 
	{
		get => GetValue<bool?>("fullsyncrequired");
		set => SetValue("fullsyncrequired", value);
	}
	// IsEnumType: False
    public Guid? subscriptionid 
	{
		get => GetValue<Guid?>("subscriptionid");
		set => SetValue("subscriptionid", value);
	}
	// IsEnumType: False
    public int? objecttypecode 
	{
		get => GetValue<int?>("objecttypecode");
		set => SetValue("objecttypecode", value);
	}

    //Navigations

}
