// <auto-generated>
//     This code was generated by Linq2OData, https://github.com/joadan/Linq2OData/ 
//     Changes to this sharedFile may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Linq2OData.Core;

namespace Large.Microsoft.Dynamics.CRM;

/// <summary>
/// OdataName: timezonedefinition
/// </summary>
public partial class timezonedefinitionInput : ODataInputBase
{
	// IsEnumType: False
    public int? timezonecode 
	{
		get => GetValue<int?>("timezonecode");
		set => SetValue("timezonecode", value);
	}
	// IsEnumType: False
    public long? versionnumber 
	{
		get => GetValue<long?>("versionnumber");
		set => SetValue("versionnumber", value);
	}
	// IsEnumType: False
    public string? userinterfacename 
	{
		get => GetValue<string?>("userinterfacename");
		set => SetValue("userinterfacename", value);
	}
	// IsEnumType: False
    public int? bias 
	{
		get => GetValue<int?>("bias");
		set => SetValue("bias", value);
	}
	// IsEnumType: False
    public int? retiredorder 
	{
		get => GetValue<int?>("retiredorder");
		set => SetValue("retiredorder", value);
	}
	// IsEnumType: False
    public Guid? _createdonbehalfby_value 
	{
		get => GetValue<Guid?>("_createdonbehalfby_value");
		set => SetValue("_createdonbehalfby_value", value);
	}
	// IsEnumType: False
    public DateTimeOffset? modifiedon 
	{
		get => GetValue<DateTimeOffset?>("modifiedon");
		set => SetValue("modifiedon", value);
	}
	// IsEnumType: False
    public DateTimeOffset? createdon 
	{
		get => GetValue<DateTimeOffset?>("createdon");
		set => SetValue("createdon", value);
	}
	// IsEnumType: False
    public string? standardname 
	{
		get => GetValue<string?>("standardname");
		set => SetValue("standardname", value);
	}
	// IsEnumType: False
    public string? daylightname 
	{
		get => GetValue<string?>("daylightname");
		set => SetValue("daylightname", value);
	}
	// IsEnumType: False
    public Guid? _createdby_value 
	{
		get => GetValue<Guid?>("_createdby_value");
		set => SetValue("_createdby_value", value);
	}
	// IsEnumType: False
    public Guid? timezonedefinitionid 
	{
		get => GetValue<Guid?>("timezonedefinitionid");
		set => SetValue("timezonedefinitionid", value);
	}
	// IsEnumType: False
    public Guid? _modifiedby_value 
	{
		get => GetValue<Guid?>("_modifiedby_value");
		set => SetValue("_modifiedby_value", value);
	}
	// IsEnumType: False
    public Guid? _organizationid_value 
	{
		get => GetValue<Guid?>("_organizationid_value");
		set => SetValue("_organizationid_value", value);
	}
	// IsEnumType: False
    public Guid? _modifiedonbehalfby_value 
	{
		get => GetValue<Guid?>("_modifiedonbehalfby_value");
		set => SetValue("_modifiedonbehalfby_value", value);
	}

    //Navigations
    public systemuserInput? modifiedby 
	{
		get => GetValue<systemuserInput?>("modifiedby");
		set => SetValue("modifiedby", value);
	}
    public List<timezonelocalizednameInput>? lk_timezonelocalizedname_timezonedefinitionid 
	{
		get => GetValue<List<timezonelocalizednameInput>?>("lk_timezonelocalizedname_timezonedefinitionid");
		set => SetValue("lk_timezonelocalizedname_timezonedefinitionid", value);
	}
    public systemuserInput? createdonbehalfby 
	{
		get => GetValue<systemuserInput?>("createdonbehalfby");
		set => SetValue("createdonbehalfby", value);
	}
    public systemuserInput? createdby 
	{
		get => GetValue<systemuserInput?>("createdby");
		set => SetValue("createdby", value);
	}
    public systemuserInput? modifiedonbehalfby 
	{
		get => GetValue<systemuserInput?>("modifiedonbehalfby");
		set => SetValue("modifiedonbehalfby", value);
	}
    public List<timezoneruleInput>? lk_timezonerule_timezonedefinitionid 
	{
		get => GetValue<List<timezoneruleInput>?>("lk_timezonerule_timezonedefinitionid");
		set => SetValue("lk_timezonerule_timezonedefinitionid", value);
	}

}
